"""document_pages

Revision ID: 0003_document_pages
Revises: 0002_upload_scope
Create Date: 2026-09-22 15:08:51.429127
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003_document_pages"
down_revision: str | None = "0002_upload_scope"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_pages",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "NATIVE_TEXT",
                "OCR",
                "BLANK",
                "FAILED",
                name="pageextractionmethod",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("text_quality_score", sa.Float(), nullable=False),
        sa.Column("ocr_required", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ocr_attempted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ocr_succeeded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "character_count >= 0", name=op.f("ck_document_pages_character_count_nonnegative")
        ),
        sa.CheckConstraint("page_number >= 1", name=op.f("ck_document_pages_page_number_positive")),
        sa.CheckConstraint(
            "text_quality_score >= 0 AND text_quality_score <= 1",
            name=op.f("ck_document_pages_quality_range"),
        ),
        sa.CheckConstraint(
            "word_count >= 0", name=op.f("ck_document_pages_word_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_document_pages_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_pages")),
        sa.UniqueConstraint("document_id", "page_number", name="uq_document_pages_document_page"),
    )
    op.create_index(
        "ix_document_pages_document_id", "document_pages", ["document_id"], unique=False
    )
    op.add_column(
        "documents",
        sa.Column(
            "parser_status",
            sa.Enum(
                "NOT_STARTED",
                "PARSING",
                "PARSED",
                "PARTIAL",
                "FAILED",
                "REVIEW_REQUIRED",
                name="parserstatus",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="NOT_STARTED",
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("page_count", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("parser_version", sa.String(length=100), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "extraction_method",
            sa.Enum(
                "NATIVE_TEXT",
                "OCR",
                "HYBRID",
                "BLANK",
                "FAILED",
                name="documentextractionmethod",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.add_column("documents", sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("documents", sa.Column("parse_error_code", sa.String(length=100), nullable=True))
    op.add_column(
        "documents", sa.Column("parse_error_message", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "parse_error_message")
    op.drop_column("documents", "parse_error_code")
    op.drop_column("documents", "parsed_at")
    op.drop_column("documents", "extraction_method")
    op.drop_column("documents", "parser_version")
    op.drop_column("documents", "page_count")
    op.drop_column("documents", "parser_status")
    op.drop_index("ix_document_pages_document_id", table_name="document_pages")
    op.drop_table("document_pages")
    # ### end Alembic commands ###
