"""company_profile

Revision ID: 0004_company_profile
Revises: 0003_document_pages
Create Date: 2026-09-22 16:21:24.311677
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004_company_profile"
down_revision: str | None = "0003_document_pages"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_profiles",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("reporting_period", sa.String(length=100), nullable=True),
        sa.Column("business_description", sa.String(length=1000), nullable=True),
        sa.Column("headquarters", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=2048), nullable=True),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "PARTIAL",
                "NEEDS_REVIEW",
                "CONFLICTING",
                name="profilestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "identity_match_status",
            sa.Enum(
                "MATCHED",
                "POSSIBLE_MATCH",
                "MISMATCH",
                "UNAVAILABLE",
                name="identitymatchstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "overall_confidence >= 0 AND overall_confidence <= 1",
            name=op.f("ck_company_profiles_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_company_profiles_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_company_profiles_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_company_profiles_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_profiles")),
        sa.UniqueConstraint(
            "document_id", "extractor_version", name="uq_company_profiles_document_version"
        ),
    )
    op.create_index(
        "ix_company_profiles_analysis_job_id", "company_profiles", ["analysis_job_id"], unique=False
    )
    op.create_index(
        "ix_company_profiles_company_id", "company_profiles", ["company_id"], unique=False
    )
    op.create_index(
        "ix_company_profiles_document_id", "company_profiles", ["document_id"], unique=False
    )
    op.create_table(
        "extracted_fields",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("field_group", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("data_type", sa.String(length=30), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("evidence_text", sa.String(length=1000), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "CONFLICTING",
                "UNAVAILABLE",
                name="fieldstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("extraction_method", sa.String(length=30), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_extracted_fields_confidence_range"),
        ),
        sa.CheckConstraint(
            "length(trim(evidence_text)) > 0", name=op.f("ck_extracted_fields_evidence_nonempty")
        ),
        sa.CheckConstraint(
            "page_number >= 1", name=op.f("ck_extracted_fields_page_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_extracted_fields_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_extracted_fields_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_extracted_fields_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
            name=op.f("fk_extracted_fields_document_page_id_document_pages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_fields")),
    )
    op.create_index(
        "ix_extracted_fields_document_id", "extracted_fields", ["document_id"], unique=False
    )
    op.create_index(
        "ix_extracted_fields_document_page_id",
        "extracted_fields",
        ["document_page_id"],
        unique=False,
    )
    op.create_index(
        "ix_extracted_fields_field_name", "extracted_fields", ["field_name"], unique=False
    )
    op.create_index("ix_extracted_fields_status", "extracted_fields", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_extracted_fields_status", table_name="extracted_fields")
    op.drop_index("ix_extracted_fields_field_name", table_name="extracted_fields")
    op.drop_index("ix_extracted_fields_document_page_id", table_name="extracted_fields")
    op.drop_index("ix_extracted_fields_document_id", table_name="extracted_fields")
    op.drop_table("extracted_fields")
    op.drop_index("ix_company_profiles_document_id", table_name="company_profiles")
    op.drop_index("ix_company_profiles_company_id", table_name="company_profiles")
    op.drop_index("ix_company_profiles_analysis_job_id", table_name="company_profiles")
    op.drop_table("company_profiles")
    # ### end Alembic commands ###
