"""domain_ml

Revision ID: 0005_domain_ml
Revises: 0004_company_profile
Create Date: 2026-09-22 16:54:42.314545
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005_domain_ml"
down_revision: str | None = "0004_company_profile"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_datasets",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.String(length=2048), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_datasets")),
        sa.UniqueConstraint("name", "version", name="uq_ml_datasets_name_version"),
    )
    op.create_table(
        "ml_runs",
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="mlrunstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parameters_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("artifact_uri", sa.String(length=2048), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["ml_datasets.id"], name=op.f("fk_ml_runs_dataset_id_ml_datasets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_runs")),
    )
    op.create_index("ix_ml_runs_status", "ml_runs", ["status"], unique=False)
    op.create_index("ix_ml_runs_task_type", "ml_runs", ["task_type"], unique=False)
    op.create_table(
        "ml_metrics",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("split", sa.String(length=30), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "metric_value >= 0 AND metric_value <= 1", name=op.f("ck_ml_metrics_value_range")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ml_runs.id"], name=op.f("fk_ml_metrics_run_id_ml_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_metrics")),
    )
    op.create_index("ix_ml_metrics_run_id", "ml_metrics", ["run_id"], unique=False)
    op.create_table(
        "ml_models",
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=2048), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("input_builder_version", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["ml_datasets.id"], name=op.f("fk_ml_models_dataset_id_ml_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ml_runs.id"], name=op.f("fk_ml_models_run_id_ml_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_models")),
        sa.UniqueConstraint("task_type", "model_version", name="uq_ml_models_task_version"),
    )
    op.create_index(
        "uq_ml_models_active_task",
        "ml_models",
        ["task_type"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "domain_classifications",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("sub_domain", sa.String(length=100), nullable=False),
        sa.Column("sector_confidence", sa.Float(), nullable=False),
        sa.Column("industry_confidence", sa.Float(), nullable=False),
        sa.Column("domain_confidence", sa.Float(), nullable=False),
        sa.Column("sub_domain_confidence", sa.Float(), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "UNAVAILABLE",
                "CONFLICTING",
                name="classificationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("alternative_sub_domain", sa.String(length=100), nullable=True),
        sa.Column("alternative_confidence", sa.Float(), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("input_builder_version", sa.String(length=100), nullable=False),
        sa.Column("input_text_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain_confidence >= 0 AND domain_confidence <= 1",
            name=op.f("ck_domain_classifications_domain_confidence_range"),
        ),
        sa.CheckConstraint(
            "industry_confidence >= 0 AND industry_confidence <= 1",
            name=op.f("ck_domain_classifications_industry_confidence_range"),
        ),
        sa.CheckConstraint(
            "overall_confidence >= 0 AND overall_confidence <= 1",
            name=op.f("ck_domain_classifications_overall_confidence_range"),
        ),
        sa.CheckConstraint(
            "sector_confidence >= 0 AND sector_confidence <= 1",
            name=op.f("ck_domain_classifications_sector_confidence_range"),
        ),
        sa.CheckConstraint(
            "sub_domain_confidence >= 0 AND sub_domain_confidence <= 1",
            name=op.f("ck_domain_classifications_sub_domain_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_domain_classifications_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_domain_classifications_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_domain_classifications_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_domain_classifications_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ml_models.id"],
            name=op.f("fk_domain_classifications_model_id_ml_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_classifications")),
        sa.UniqueConstraint(
            "company_profile_id",
            "model_id",
            "input_text_hash",
            "input_builder_version",
            name="uq_domain_classifications_input_model",
        ),
    )
    op.create_index(
        "ix_domain_classifications_company_profile_id",
        "domain_classifications",
        ["company_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_domain_classifications_document_id",
        "domain_classifications",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "domain_classification_evidence",
        sa.Column("domain_classification_id", sa.Uuid(), nullable=False),
        sa.Column("extracted_field_id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
            name=op.f("fk_domain_classification_evidence_document_page_id_document_pages"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_classification_id"],
            ["domain_classifications.id"],
            name=op.f(
                "fk_domain_classification_evidence_domain_classification_id_domain_classifications"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["extracted_field_id"],
            ["extracted_fields.id"],
            name=op.f("fk_domain_classification_evidence_extracted_field_id_extracted_fields"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_classification_evidence")),
        sa.UniqueConstraint(
            "domain_classification_id",
            "extracted_field_id",
            name="uq_domain_classification_evidence_field",
        ),
    )
    op.create_index(
        "ix_domain_classification_evidence_classification_id",
        "domain_classification_evidence",
        ["domain_classification_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_domain_classification_evidence_classification_id",
        table_name="domain_classification_evidence",
    )
    op.drop_table("domain_classification_evidence")
    op.drop_index("ix_domain_classifications_document_id", table_name="domain_classifications")
    op.drop_index(
        "ix_domain_classifications_company_profile_id", table_name="domain_classifications"
    )
    op.drop_table("domain_classifications")
    op.drop_index(
        "uq_ml_models_active_task", table_name="ml_models", postgresql_where=sa.text("is_active")
    )
    op.drop_table("ml_models")
    op.drop_index("ix_ml_metrics_run_id", table_name="ml_metrics")
    op.drop_table("ml_metrics")
    op.drop_index("ix_ml_runs_task_type", table_name="ml_runs")
    op.drop_index("ix_ml_runs_status", table_name="ml_runs")
    op.drop_table("ml_runs")
    op.drop_table("ml_datasets")
    # ### end Alembic commands ###
