"""financial_statements

Revision ID: 0006_financial_statements
Revises: 0005_domain_ml
Create Date: 2026-09-22 21:14:47.790506
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006_financial_statements"
down_revision: str | None = "0005_domain_ml"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_extraction_runs",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "PARTIAL",
                "NEEDS_REVIEW",
                "CONFLICTING",
                "UNAVAILABLE",
                "UNMAPPED",
                name="financialstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("statement_count", sa.Integer(), nullable=False),
        sa.Column("line_item_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statement_count >= 0 AND line_item_count >= 0",
            name=op.f("ck_financial_extraction_runs_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_extraction_runs_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_extraction_runs_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_extraction_runs")),
        sa.UniqueConstraint(
            "document_id",
            "extractor_version",
            "taxonomy_version",
            "input_hash",
            name="uq_financial_runs_input",
        ),
    )
    op.create_index(
        "ix_financial_runs_document_id", "financial_extraction_runs", ["document_id"], unique=False
    )
    op.create_table(
        "financial_statements",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_type",
            sa.Enum(
                "BALANCE_SHEET",
                "INCOME_STATEMENT",
                "CASH_FLOW_STATEMENT",
                name="financialstatementtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.String(length=20), nullable=True),
        sa.Column("period_label", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("raw_unit", sa.String(length=50), nullable=True),
        sa.Column("normalized_unit", sa.String(length=20), nullable=True),
        sa.Column("unit_multiplier", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("start_page_number", sa.Integer(), nullable=False),
        sa.Column("end_page_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "PARTIAL",
                "NEEDS_REVIEW",
                "CONFLICTING",
                "UNAVAILABLE",
                "UNMAPPED",
                name="financialstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_financial_statements_confidence_range"),
        ),
        sa.CheckConstraint(
            "start_page_number >= 1 AND end_page_number >= start_page_number",
            name=op.f("ck_financial_statements_page_range"),
        ),
        sa.CheckConstraint(
            "unit_multiplier > 0", name=op.f("ck_financial_statements_multiplier_positive")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_statements_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_statements_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_statements_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_extraction_runs.id"],
            name=op.f("fk_financial_statements_run_id_financial_extraction_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statements")),
    )
    op.create_index(
        "ix_financial_statements_document_id", "financial_statements", ["document_id"], unique=False
    )
    op.create_index(
        "ix_financial_statements_run_id", "financial_statements", ["run_id"], unique=False
    )
    op.create_table(
        "financial_line_items",
        sa.Column("financial_statement_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=100), nullable=True),
        sa.Column("raw_label", sa.String(length=500), nullable=False),
        sa.Column("measurement_type", sa.String(length=20), nullable=False),
        sa.Column("raw_value", sa.String(length=100), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("raw_column_header", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("raw_unit", sa.String(length=50), nullable=True),
        sa.Column("normalized_unit", sa.String(length=20), nullable=True),
        sa.Column("unit_multiplier", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.String(length=20), nullable=True),
        sa.Column("period_label", sa.String(length=100), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "PARTIAL",
                "NEEDS_REVIEW",
                "CONFLICTING",
                "UNAVAILABLE",
                "UNMAPPED",
                name="financialstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_priority", sa.Integer(), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_financial_line_items_confidence_range"),
        ),
        sa.CheckConstraint(
            "numeric_value IS NOT NULL OR status IN ('UNAVAILABLE', 'UNMAPPED')",
            name=op.f("ck_financial_line_items_null_numeric_status"),
        ),
        sa.CheckConstraint("page_number >= 1", name=op.f("ck_financial_line_items_page_positive")),
        sa.CheckConstraint(
            "unit_multiplier > 0", name=op.f("ck_financial_line_items_multiplier_positive")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_line_items_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_line_items_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_line_items_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
            name=op.f("fk_financial_line_items_document_page_id_document_pages"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_statement_id"],
            ["financial_statements.id"],
            name=op.f("fk_financial_line_items_financial_statement_id_financial_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_line_items")),
    )
    op.create_index(
        "ix_financial_line_items_document_page_id",
        "financial_line_items",
        ["document_page_id"],
        unique=False,
    )
    op.create_index(
        "ix_financial_line_items_statement_id",
        "financial_line_items",
        ["financial_statement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_financial_line_items_statement_id", table_name="financial_line_items")
    op.drop_index("ix_financial_line_items_document_page_id", table_name="financial_line_items")
    op.drop_table("financial_line_items")
    op.drop_index("ix_financial_statements_run_id", table_name="financial_statements")
    op.drop_index("ix_financial_statements_document_id", table_name="financial_statements")
    op.drop_table("financial_statements")
    op.drop_index("ix_financial_runs_document_id", table_name="financial_extraction_runs")
    op.drop_table("financial_extraction_runs")
    # ### end Alembic commands ###
