"""financial_analysis

Revision ID: 0007_financial_analysis
Revises: 0006_financial_statements
Create Date: 2026-09-23 22:47:56.057819
"""
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0007_financial_analysis"
down_revision: str | None = "0006_financial_statements"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_analysis_runs",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("normalized_value_count", sa.Integer(), nullable=False),
        sa.Column("derived_value_count", sa.Integer(), nullable=False),
        sa.Column("ratio_count", sa.Integer(), nullable=False),
        sa.Column("validator_version", sa.String(length=100), nullable=False),
        sa.Column("calculator_version", sa.String(length=100), nullable=False),
        sa.Column("ratio_taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completeness_score >= 0 AND completeness_score <= 1",
            name=op.f("ck_financial_analysis_runs_completeness_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_analysis_runs_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_analysis_runs_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_analysis_runs")),
        sa.UniqueConstraint(
            "document_id",
            "input_hash",
            "validator_version",
            "calculator_version",
            "ratio_taxonomy_version",
            name="uq_financial_analysis_runs_input",
        ),
    )
    op.create_index(
        "ix_financial_analysis_runs_document_id",
        "financial_analysis_runs",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "financial_ratios",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("ratio_name", sa.String(length=100), nullable=False),
        sa.Column("ratio_category", sa.String(length=50), nullable=False),
        sa.Column("ratio_value", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("ratio_unit", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "UNAVAILABLE",
                "NOT_MEANINGFUL",
                "CONFLICTING",
                name="ratiostatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("calculation_basis", sa.String(length=30), nullable=False),
        sa.Column("formula", sa.String(length=500), nullable=False),
        sa.Column("formula_version", sa.String(length=100), nullable=False),
        sa.Column("ratio_taxonomy_version", sa.String(length=100), nullable=False),
        sa.Column("calculator_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_financial_ratios_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_ratios_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_financial_ratios_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_ratios_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_financial_ratios_run_id_financial_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_ratios")),
        sa.UniqueConstraint(
            "run_id",
            "statement_scope",
            "fiscal_year",
            "ratio_name",
            name="uq_financial_ratios_run_scope_year_name",
        ),
    )
    op.create_index(
        "ix_financial_ratios_document_scope_year",
        "financial_ratios",
        ["document_id", "statement_scope", "fiscal_year"],
        unique=False,
    )
    op.create_table(
        "financial_validation_issues",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("issue_type", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="validationseverity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("related_line_item_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_value_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expected_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("actual_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("difference", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("tolerance", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PASS",
                "WARNING",
                "FAIL",
                "SKIPPED",
                name="validationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("validator_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_validation_issues_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_validation_issues_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_validation_issues_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_financial_validation_issues_run_id_financial_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_validation_issues")),
    )
    op.create_index(
        "ix_financial_validation_issues_document_id",
        "financial_validation_issues",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_financial_validation_issues_run_id",
        "financial_validation_issues",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "normalized_financial_values",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("financial_line_item_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=100), nullable=False),
        sa.Column("statement_type", sa.String(length=30), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("measurement_type", sa.String(length=20), nullable=False),
        sa.Column("raw_numeric_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("normalized_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("normalized_currency", sa.String(length=3), nullable=True),
        sa.Column("raw_unit", sa.String(length=50), nullable=True),
        sa.Column("canonical_unit", sa.String(length=30), nullable=False),
        sa.Column("unit_multiplier", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column(
            "normalization_status",
            sa.Enum(
                "NORMALIZED",
                "NEEDS_REVIEW",
                "UNAVAILABLE",
                "CONFLICTING",
                "CURRENCY_MISMATCH",
                "INVALID_VALUE",
                name="normalizationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("normalization_confidence", sa.Float(), nullable=False),
        sa.Column(
            "value_origin",
            sa.Enum(
                "EXTRACTED",
                "DERIVED",
                name="valueorigin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("formula", sa.String(length=500), nullable=True),
        sa.Column("input_value_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "normalization_confidence >= 0 AND normalization_confidence <= 1",
            name=op.f("ck_normalized_financial_values_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_normalized_financial_values_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_normalized_financial_values_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_normalized_financial_values_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_line_item_id"],
            ["financial_line_items.id"],
            name=op.f("fk_normalized_financial_values_financial_line_item_id_financial_line_items"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_normalized_financial_values_run_id_financial_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_financial_values")),
        sa.UniqueConstraint(
            "run_id",
            "statement_scope",
            "fiscal_year",
            "canonical_name",
            name="uq_normalized_financial_values_run_scope_year_name",
        ),
    )
    op.create_index(
        "ix_normalized_financial_values_lookup",
        "normalized_financial_values",
        ["document_id", "statement_scope", "fiscal_year", "canonical_name"],
        unique=False,
    )
    op.create_index(
        "ix_normalized_financial_values_run_id",
        "normalized_financial_values",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "financial_ratio_inputs",
        sa.Column("financial_ratio_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_financial_value_id", sa.Uuid(), nullable=False),
        sa.Column("input_role", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["financial_ratio_id"],
            ["financial_ratios.id"],
            name=op.f("fk_financial_ratio_inputs_financial_ratio_id_financial_ratios"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_financial_value_id"],
            ["normalized_financial_values.id"],
            name=op.f(
                "fk_financial_ratio_inputs_normalized_financial_value_id_normalized_financial_values"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_ratio_inputs")),
        sa.UniqueConstraint(
            "financial_ratio_id",
            "normalized_financial_value_id",
            "input_role",
            name="uq_financial_ratio_inputs_role",
        ),
    )
    op.create_index(
        "ix_financial_ratio_inputs_ratio_id",
        "financial_ratio_inputs",
        ["financial_ratio_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_financial_ratio_inputs_ratio_id", table_name="financial_ratio_inputs")
    op.drop_table("financial_ratio_inputs")
    op.drop_index("ix_normalized_financial_values_run_id", table_name="normalized_financial_values")
    op.drop_index("ix_normalized_financial_values_lookup", table_name="normalized_financial_values")
    op.drop_table("normalized_financial_values")
    op.drop_index("ix_financial_validation_issues_run_id", table_name="financial_validation_issues")
    op.drop_index(
        "ix_financial_validation_issues_document_id", table_name="financial_validation_issues"
    )
    op.drop_table("financial_validation_issues")
    op.drop_index("ix_financial_ratios_document_scope_year", table_name="financial_ratios")
    op.drop_table("financial_ratios")
    op.drop_index("ix_financial_analysis_runs_document_id", table_name="financial_analysis_runs")
    op.drop_table("financial_analysis_runs")
    # ### end Alembic commands ###
