"""financial_trends

Revision ID: 0008_financial_trends
Revises: 0007_financial_analysis
Create Date: 2026-09-24 12:19:48.188944
"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0008_financial_trends"
down_revision: str | None = "0007_financial_analysis"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_trend_runs",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("financial_analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("trend_calculator_version", sa.String(length=100), nullable=False),
        sa.Column("anomaly_rule_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("trend_count", sa.Integer(), nullable=False),
        sa.Column("anomaly_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_trend_runs_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_trend_runs_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_trend_runs_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_analysis_run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_financial_trend_runs_financial_analysis_run_id_financial_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_trend_runs")),
        sa.UniqueConstraint(
            "document_id",
            "input_hash",
            "trend_calculator_version",
            "anomaly_rule_version",
            name="uq_financial_trend_runs_input",
        ),
    )
    op.create_index(
        "ix_financial_trend_runs_document_id", "financial_trend_runs", ["document_id"], unique=False
    )
    op.create_table(
        "financial_anomalies",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("anomaly_type", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="anomalyseverity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("end_fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "UNAVAILABLE",
                "CONFLICTING",
                name="anomalystatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("persistence_count", sa.Integer(), nullable=False),
        sa.Column("rule_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_financial_anomalies_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_anomalies_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_anomalies_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_anomalies_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_trend_runs.id"],
            name=op.f("fk_financial_anomalies_run_id_financial_trend_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_anomalies")),
        sa.UniqueConstraint(
            "run_id",
            "statement_scope",
            "anomaly_type",
            "start_fiscal_year",
            "end_fiscal_year",
            name="uq_financial_anomalies_run_scope_type_period",
        ),
    )
    op.create_index(
        "ix_financial_anomalies_document_scope_severity",
        "financial_anomalies",
        ["document_id", "statement_scope", "severity"],
        unique=False,
    )
    op.create_table(
        "financial_trends",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column(
            "metric_source_type",
            sa.Enum(
                "NORMALIZED_VALUE",
                "RATIO",
                name="trendmetricsourcetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("end_fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("period_count", sa.Integer(), nullable=False),
        sa.Column("start_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("end_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("absolute_change", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("percentage_change", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("cagr", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("percentage_point_change", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "ABSOLUTE",
                "PERCENT",
                "PERCENTAGE_POINT",
                "MULTIPLE_CHANGE",
                "STATE_TRANSITION",
                name="changetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("state_transition", sa.String(length=30), nullable=True),
        sa.Column(
            "trend_direction",
            sa.Enum(
                "INCREASING",
                "DECREASING",
                "STABLE",
                "VOLATILE",
                "MIXED",
                "INSUFFICIENT_DATA",
                "STATE_CHANGE",
                name="trenddirection",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "trend_strength",
            sa.Enum(
                "WEAK",
                "MODERATE",
                "STRONG",
                name="trendstrength",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "UNAVAILABLE",
                "NOT_MEANINGFUL",
                "CONFLICTING",
                "INSUFFICIENT_DATA",
                name="trendstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("series", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_periods", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("calculator_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_financial_trends_confidence_range"),
        ),
        sa.CheckConstraint(
            "period_count >= 1", name=op.f("ck_financial_trends_period_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_financial_trends_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_financial_trends_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_financial_trends_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["financial_trend_runs.id"],
            name=op.f("fk_financial_trends_run_id_financial_trend_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_trends")),
        sa.UniqueConstraint(
            "run_id",
            "statement_scope",
            "metric_source_type",
            "metric_name",
            "currency",
            name="uq_financial_trends_run_scope_source_metric_currency",
        ),
    )
    op.create_index(
        "ix_financial_trends_document_scope_metric",
        "financial_trends",
        ["document_id", "statement_scope", "metric_name"],
        unique=False,
    )
    op.create_table(
        "financial_anomaly_inputs",
        sa.Column("financial_anomaly_id", sa.Uuid(), nullable=False),
        sa.Column("financial_trend_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_financial_value_id", sa.Uuid(), nullable=True),
        sa.Column("financial_ratio_id", sa.Uuid(), nullable=True),
        sa.Column("input_role", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(financial_trend_id, normalized_financial_value_id, financial_ratio_id) = 1",
            name=op.f("ck_financial_anomaly_inputs_exactly_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_anomaly_id"],
            ["financial_anomalies.id"],
            name=op.f("fk_financial_anomaly_inputs_financial_anomaly_id_financial_anomalies"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_ratio_id"],
            ["financial_ratios.id"],
            name=op.f("fk_financial_anomaly_inputs_financial_ratio_id_financial_ratios"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_trend_id"],
            ["financial_trends.id"],
            name=op.f("fk_financial_anomaly_inputs_financial_trend_id_financial_trends"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_financial_value_id"],
            ["normalized_financial_values.id"],
            name=op.f(
                "fk_financial_anomaly_inputs_normalized_financial_value_id_normalized_financial_values"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_anomaly_inputs")),
        sa.UniqueConstraint(
            "financial_anomaly_id",
            "financial_trend_id",
            "normalized_financial_value_id",
            "financial_ratio_id",
            "input_role",
            name="uq_financial_anomaly_inputs_source_role",
        ),
    )
    op.create_index(
        "ix_financial_anomaly_inputs_anomaly_id",
        "financial_anomaly_inputs",
        ["financial_anomaly_id"],
        unique=False,
    )
    op.create_table(
        "financial_trend_inputs",
        sa.Column("financial_trend_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_financial_value_id", sa.Uuid(), nullable=True),
        sa.Column("financial_ratio_id", sa.Uuid(), nullable=True),
        sa.Column("input_role", sa.String(length=100), nullable=False),
        sa.Column("fiscal_year", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(normalized_financial_value_id IS NOT NULL) <> (financial_ratio_id IS NOT NULL)",
            name=op.f("ck_financial_trend_inputs_exactly_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_ratio_id"],
            ["financial_ratios.id"],
            name=op.f("fk_financial_trend_inputs_financial_ratio_id_financial_ratios"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_trend_id"],
            ["financial_trends.id"],
            name=op.f("fk_financial_trend_inputs_financial_trend_id_financial_trends"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_financial_value_id"],
            ["normalized_financial_values.id"],
            name=op.f(
                "fk_financial_trend_inputs_normalized_financial_value_id_normalized_financial_values"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_trend_inputs")),
        sa.UniqueConstraint(
            "financial_trend_id",
            "normalized_financial_value_id",
            "financial_ratio_id",
            "input_role",
            name="uq_financial_trend_inputs_source_role",
        ),
    )
    op.create_index(
        "ix_financial_trend_inputs_trend_id",
        "financial_trend_inputs",
        ["financial_trend_id"],
        unique=False,
    )
    op.drop_constraint("analysisstage", "analysis_jobs", type_="check")
    op.alter_column(
        "analysis_jobs",
        "current_stage",
        existing_type=sa.VARCHAR(length=21),
        type_=sa.String(length=24),
        existing_nullable=False,
    )
    op.create_check_constraint(
        "analysisstage",
        "analysis_jobs",
        "current_stage IN ('CREATED','DOCUMENT_INGESTION','DOCUMENT_PARSING','COMPANY_EXTRACTION','DOMAIN_CLASSIFICATION','FINANCIAL_EXTRACTION','FINANCIAL_VALIDATION','FINANCIAL_TREND_ANALYSIS','CREDIT_ANALYSIS','RESEARCH','PEER_DISCOVERY','STOCK_ANALYSIS','REPORT_GENERATION')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE analysis_jobs SET current_stage = 'FINANCIAL_VALIDATION' "
        "WHERE current_stage = 'FINANCIAL_TREND_ANALYSIS'"
    )
    op.drop_constraint("analysisstage", "analysis_jobs", type_="check")
    op.alter_column(
        "analysis_jobs",
        "current_stage",
        existing_type=sa.String(length=24),
        type_=sa.String(length=21),
        existing_nullable=False,
    )
    op.create_check_constraint(
        "analysisstage",
        "analysis_jobs",
        "current_stage IN ('CREATED','DOCUMENT_INGESTION','DOCUMENT_PARSING','COMPANY_EXTRACTION','DOMAIN_CLASSIFICATION','FINANCIAL_EXTRACTION','FINANCIAL_VALIDATION','CREDIT_ANALYSIS','RESEARCH','PEER_DISCOVERY','STOCK_ANALYSIS','REPORT_GENERATION')",
    )
    op.drop_index("ix_financial_trend_inputs_trend_id", table_name="financial_trend_inputs")
    op.drop_table("financial_trend_inputs")
    op.drop_index("ix_financial_anomaly_inputs_anomaly_id", table_name="financial_anomaly_inputs")
    op.drop_table("financial_anomaly_inputs")
    op.drop_index("ix_financial_trends_document_scope_metric", table_name="financial_trends")
    op.drop_table("financial_trends")
    op.drop_index(
        "ix_financial_anomalies_document_scope_severity", table_name="financial_anomalies"
    )
    op.drop_table("financial_anomalies")
    op.drop_index("ix_financial_trend_runs_document_id", table_name="financial_trend_runs")
    op.drop_table("financial_trend_runs")
    # ### end Alembic commands ###
