"""credit_risk_engine

Revision ID: 0009_credit_risk
Revises: 0008_financial_trends
Create Date: 2026-09-24 12:58:57.916174
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009_credit_risk"
down_revision: str | None = "0008_financial_trends"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_assessments",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("financial_analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("financial_trend_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("overall_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "risk_band",
            sa.Enum(
                "LOW_RISK",
                "MODERATE_LOW_RISK",
                "MODERATE_RISK",
                "ELEVATED_RISK",
                "HIGH_RISK",
                name="creditriskband",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("component_coverage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "INSUFFICIENT_DATA",
                "CONFLICTING",
                "UNAVAILABLE",
                "FAILED",
                name="creditassessmentstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("feature_builder_version", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("score_engine_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(overall_score IS NULL AND risk_band IS NULL) OR "
            "(overall_score IS NOT NULL AND risk_band IS NOT NULL)",
            name=op.f("ck_credit_assessments_score_band_consistency"),
        ),
        sa.CheckConstraint(
            "component_coverage >= 0 AND component_coverage <= 1",
            name=op.f("ck_credit_assessments_component_coverage_range"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_credit_assessments_confidence_range"),
        ),
        sa.CheckConstraint(
            "overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)",
            name=op.f("ck_credit_assessments_overall_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_credit_assessments_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_credit_assessments_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_credit_assessments_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_analysis_run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_credit_assessments_financial_analysis_run_id_financial_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_trend_run_id"],
            ["financial_trend_runs.id"],
            name=op.f("fk_credit_assessments_financial_trend_run_id_financial_trend_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_assessments")),
        sa.UniqueConstraint(
            "document_id",
            "statement_scope",
            "input_hash",
            "policy_version",
            "feature_builder_version",
            "score_engine_version",
            name="uq_credit_assessments_input",
        ),
    )
    op.create_index(
        "ix_credit_assessments_document_scope",
        "credit_assessments",
        ["document_id", "statement_scope"],
        unique=False,
    )
    op.create_table(
        "credit_subscores",
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "component_name",
            sa.Enum(
                "FINANCIAL_STRENGTH",
                "REPAYMENT_CAPACITY",
                "BUSINESS_STABILITY",
                "DATA_QUALITY",
                "INDUSTRY_CONTEXT",
                name="creditcomponent",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("raw_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("normalized_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("weighted_score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("coverage_ratio", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "INSUFFICIENT_DATA",
                "CONFLICTING",
                "UNAVAILABLE",
                "FAILED",
                name="creditassessmentstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_credit_subscores_confidence_range"),
        ),
        sa.CheckConstraint(
            "coverage_ratio >= 0 AND coverage_ratio <= 1",
            name=op.f("ck_credit_subscores_coverage_range"),
        ),
        sa.CheckConstraint("max_score = 100", name=op.f("ck_credit_subscores_max_score_expected")),
        sa.CheckConstraint(
            "normalized_score >= 0 AND normalized_score <= 100",
            name=op.f("ck_credit_subscores_normalized_score_range"),
        ),
        sa.CheckConstraint(
            "raw_score >= 0 AND raw_score <= 100", name=op.f("ck_credit_subscores_raw_score_range")
        ),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 1", name=op.f("ck_credit_subscores_weight_range")
        ),
        sa.CheckConstraint(
            "weighted_score IS NULL OR (weighted_score >= 0 AND weighted_score <= 100)",
            name=op.f("ck_credit_subscores_weighted_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_subscores_credit_assessment_id_credit_assessments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_subscores")),
        sa.UniqueConstraint(
            "credit_assessment_id",
            "component_name",
            name="uq_credit_subscores_assessment_component",
        ),
    )
    op.create_index(
        "ix_credit_subscores_assessment_id",
        "credit_subscores",
        ["credit_assessment_id"],
        unique=False,
    )
    op.create_table(
        "credit_assessment_inputs",
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_financial_value_id", sa.Uuid(), nullable=True),
        sa.Column("financial_ratio_id", sa.Uuid(), nullable=True),
        sa.Column("financial_trend_id", sa.Uuid(), nullable=True),
        sa.Column("financial_anomaly_id", sa.Uuid(), nullable=True),
        sa.Column("company_profile_id", sa.Uuid(), nullable=True),
        sa.Column("domain_classification_id", sa.Uuid(), nullable=True),
        sa.Column("input_role", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(normalized_financial_value_id, financial_ratio_id, "
            "financial_trend_id, financial_anomaly_id, company_profile_id, "
            "domain_classification_id) = 1",
            name=op.f("ck_credit_assessment_inputs_exactly_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_credit_assessment_inputs_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_assessment_inputs_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_classification_id"],
            ["domain_classifications.id"],
            name=op.f(
                "fk_credit_assessment_inputs_domain_classification_id_domain_classifications"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["financial_anomaly_id"],
            ["financial_anomalies.id"],
            name=op.f("fk_credit_assessment_inputs_financial_anomaly_id_financial_anomalies"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_ratio_id"],
            ["financial_ratios.id"],
            name=op.f("fk_credit_assessment_inputs_financial_ratio_id_financial_ratios"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_trend_id"],
            ["financial_trends.id"],
            name=op.f("fk_credit_assessment_inputs_financial_trend_id_financial_trends"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_financial_value_id"],
            ["normalized_financial_values.id"],
            name=op.f(
                "fk_credit_assessment_inputs_normalized_financial_value_id_normalized_financial_values"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_assessment_inputs")),
        sa.UniqueConstraint(
            "credit_assessment_id", "input_role", name="uq_credit_assessment_inputs_role"
        ),
    )
    op.create_index(
        "ix_credit_assessment_inputs_assessment_id",
        "credit_assessment_inputs",
        ["credit_assessment_id"],
        unique=False,
    )
    op.create_table(
        "credit_rule_results",
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_input_id", sa.Uuid(), nullable=True),
        sa.Column(
            "component",
            sa.Enum(
                "FINANCIAL_STRENGTH",
                "REPAYMENT_CAPACITY",
                "BUSINESS_STABILITY",
                "DATA_QUALITY",
                "INDUSTRY_CONTEXT",
                name="creditcomponent",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rule_code", sa.String(length=120), nullable=False),
        sa.Column("rule_version", sa.String(length=100), nullable=False),
        sa.Column("input_metric", sa.String(length=120), nullable=False),
        sa.Column("input_value", sa.Numeric(precision=38, scale=10), nullable=True),
        sa.Column("input_status", sa.String(length=30), nullable=False),
        sa.Column("score_impact", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("max_score_impact", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "reason_type",
            sa.Enum(
                "POSITIVE",
                "NEGATIVE",
                "NEUTRAL",
                "REVIEW",
                name="creditreasontype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "NEEDS_REVIEW",
                "INSUFFICIENT_DATA",
                "CONFLICTING",
                "UNAVAILABLE",
                "FAILED",
                name="creditassessmentstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_credit_rule_results_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_rule_results_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_input_id"],
            ["credit_assessment_inputs.id"],
            name=op.f("fk_credit_rule_results_credit_assessment_input_id_credit_assessment_inputs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_rule_results")),
        sa.UniqueConstraint(
            "credit_assessment_id", "rule_code", name="uq_credit_rule_results_assessment_code"
        ),
    )
    op.create_index(
        "ix_credit_rule_results_assessment_type",
        "credit_rule_results",
        ["credit_assessment_id", "reason_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credit_rule_results_assessment_type", table_name="credit_rule_results")
    op.drop_table("credit_rule_results")
    op.drop_index(
        "ix_credit_assessment_inputs_assessment_id", table_name="credit_assessment_inputs"
    )
    op.drop_table("credit_assessment_inputs")
    op.drop_index("ix_credit_subscores_assessment_id", table_name="credit_subscores")
    op.drop_table("credit_subscores")
    op.drop_index("ix_credit_assessments_document_scope", table_name="credit_assessments")
    op.drop_table("credit_assessments")
    # ### end Alembic commands ###
