"""credit_fusion

Revision ID: 0013_credit_fusion
Revises: 0012_credit_ml_evaluation
Create Date: 2026-09-24 23:02:19.644351
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0013_credit_fusion"
down_revision: str | None = "0012_credit_ml_evaluation"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_fusion_experiments",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("ml_model_id", sa.Uuid(), nullable=True),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=True),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("rule_score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("rule_risk_index", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("ml_probability", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("rule_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("ml_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "experimental_hybrid_risk_index", sa.Numeric(precision=10, scale=8), nullable=True
        ),
        sa.Column("experimental_strength_score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("experimental_band", sa.String(length=60), nullable=True),
        sa.Column("rule_ml_gap", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("fusion_confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "production_use_permitted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "fusion_not_executed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("fallback_source", sa.String(length=60), nullable=True),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("risk_band_version", sa.String(length=100), nullable=False),
        sa.Column("fusion_engine_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("readiness_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experimental_hybrid_risk_index IS NULL OR "
            "(experimental_hybrid_risk_index >= 0 AND "
            "experimental_hybrid_risk_index <= 1)",
            name=op.f("ck_credit_fusion_experiments_hybrid_risk_range"),
        ),
        sa.CheckConstraint(
            "fusion_confidence >= 0 AND fusion_confidence <= 1",
            name=op.f("ck_credit_fusion_experiments_fusion_confidence_range"),
        ),
        sa.CheckConstraint(
            "ml_probability IS NULL OR (ml_probability >= 0 AND ml_probability <= 1)",
            name=op.f("ck_credit_fusion_experiments_ml_probability_range"),
        ),
        sa.CheckConstraint(
            "rule_risk_index IS NULL OR (rule_risk_index >= 0 AND rule_risk_index <= 1)",
            name=op.f("ck_credit_fusion_experiments_rule_risk_index_range"),
        ),
        sa.CheckConstraint(
            "rule_score IS NULL OR (rule_score >= 0 AND rule_score <= 100)",
            name=op.f("ck_credit_fusion_experiments_rule_score_range"),
        ),
        sa.CheckConstraint(
            "rule_weight >= 0 AND rule_weight <= 1 AND ml_weight >= 0 AND ml_weight <= 1",
            name=op.f("ck_credit_fusion_experiments_weights_range"),
        ),
        sa.CheckConstraint(
            "rule_weight + ml_weight = 1",
            name=op.f("ck_credit_fusion_experiments_weights_sum_to_one"),
        ),
        sa.CheckConstraint(
            "strategy IN ('WEIGHTED_BLEND', 'CONSENSUS_GATED')",
            name=op.f("ck_credit_fusion_experiments_strategy_valid"),
        ),
        sa.CheckConstraint(
            "mode IN ('DISABLED', 'EXPERIMENTAL', 'FUTURE_PRODUCTION')",
            name=op.f("ck_credit_fusion_experiments_mode_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('EXPERIMENTAL_RESULT', 'RULE_ONLY_FALLBACK', 'REVIEW_REQUIRED', "
            "'INSUFFICIENT_DATA', 'BLOCKED_BY_READINESS', 'BLOCKED_BY_DRIFT', "
            "'BLOCKED_BY_DISAGREEMENT', 'BLOCKED_BY_ARTIFACT_INTEGRITY', "
            "'NO_RELIABLE_OUTPUT')",
            name=op.f("ck_credit_fusion_experiments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_credit_fusion_experiments_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_credit_fusion_experiments_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_fusion_experiments_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_credit_fusion_experiments_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["credit_ml_evaluation_runs.id"],
            name=op.f("fk_credit_fusion_experiments_evaluation_run_id_credit_ml_evaluation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["credit_ml_feature_snapshots.id"],
            name=op.f(
                "fk_credit_fusion_experiments_feature_snapshot_id_credit_ml_feature_snapshots"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["ml_model_id"],
            ["ml_models.id"],
            name=op.f("fk_credit_fusion_experiments_ml_model_id_ml_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_fusion_experiments")),
        sa.UniqueConstraint(
            "credit_assessment_id",
            "ml_model_id",
            "input_hash",
            "policy_version",
            "strategy",
            name="uq_credit_fusion_experiment_input",
        ),
    )
    op.create_index(
        "ix_credit_fusion_experiments_document_id",
        "credit_fusion_experiments",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_credit_fusion_experiments_status", "credit_fusion_experiments", ["status"], unique=False
    )
    op.create_table(
        "credit_fusion_contributions",
        sa.Column("fusion_experiment_id", sa.Uuid(), nullable=False),
        sa.Column("contribution_type", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=60), nullable=False),
        sa.Column("raw_value", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("normalized_value", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("weighted_contribution", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_credit_fusion_contributions_confidence_range"),
        ),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 1", name=op.f("ck_credit_fusion_contributions_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["fusion_experiment_id"],
            ["credit_fusion_experiments.id"],
            name=op.f(
                "fk_credit_fusion_contributions_fusion_experiment_id_credit_fusion_experiments"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_fusion_contributions")),
        sa.UniqueConstraint(
            "fusion_experiment_id", "contribution_type", name="uq_credit_fusion_contribution_type"
        ),
    )
    op.create_index(
        "ix_credit_fusion_contributions_experiment_id",
        "credit_fusion_contributions",
        ["fusion_experiment_id"],
        unique=False,
    )
    op.create_table(
        "credit_fusion_inputs",
        sa.Column("fusion_experiment_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("ml_model_id", sa.Uuid(), nullable=True),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=True),
        sa.Column("ml_prediction_reference", sa.String(length=200), nullable=True),
        sa.Column("input_role", sa.String(length=60), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_fusion_inputs_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["credit_ml_evaluation_runs.id"],
            name=op.f("fk_credit_fusion_inputs_evaluation_run_id_credit_ml_evaluation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["credit_ml_feature_snapshots.id"],
            name=op.f("fk_credit_fusion_inputs_feature_snapshot_id_credit_ml_feature_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["fusion_experiment_id"],
            ["credit_fusion_experiments.id"],
            name=op.f("fk_credit_fusion_inputs_fusion_experiment_id_credit_fusion_experiments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ml_model_id"],
            ["ml_models.id"],
            name=op.f("fk_credit_fusion_inputs_ml_model_id_ml_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_fusion_inputs")),
        sa.UniqueConstraint(
            "fusion_experiment_id", "input_role", name="uq_credit_fusion_input_role"
        ),
    )
    op.create_index(
        "ix_credit_fusion_inputs_experiment_id",
        "credit_fusion_inputs",
        ["fusion_experiment_id"],
        unique=False,
    )
    op.create_table(
        "credit_fusion_reasons",
        sa.Column("fusion_experiment_id", sa.Uuid(), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("impact_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=True),
        sa.Column("source_reference_type", sa.String(length=60), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fusion_experiment_id"],
            ["credit_fusion_experiments.id"],
            name=op.f("fk_credit_fusion_reasons_fusion_experiment_id_credit_fusion_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_fusion_reasons")),
    )
    op.create_index(
        "ix_credit_fusion_reasons_experiment_id",
        "credit_fusion_reasons",
        ["fusion_experiment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credit_fusion_reasons_experiment_id", table_name="credit_fusion_reasons")
    op.drop_table("credit_fusion_reasons")
    op.drop_index("ix_credit_fusion_inputs_experiment_id", table_name="credit_fusion_inputs")
    op.drop_table("credit_fusion_inputs")
    op.drop_index(
        "ix_credit_fusion_contributions_experiment_id", table_name="credit_fusion_contributions"
    )
    op.drop_table("credit_fusion_contributions")
    op.drop_index("ix_credit_fusion_experiments_status", table_name="credit_fusion_experiments")
    op.drop_index(
        "ix_credit_fusion_experiments_document_id", table_name="credit_fusion_experiments"
    )
    op.drop_table("credit_fusion_experiments")
    # ### end Alembic commands ###
