"""five_cs

Revision ID: 0014_five_cs
Revises: 0013_credit_fusion
Create Date: 2026-09-25 09:50:08.911133
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0014_five_cs"
down_revision: str | None = "0013_credit_fusion"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "five_cs_assessments",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("financial_analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("financial_trend_run_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("domain_classification_id", sa.Uuid(), nullable=True),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("overall_completeness", sa.Float(), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("summary_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','NEEDS_REVIEW','PARTIAL','UNAVAILABLE','CONFLICTING')",
            name=op.f("ck_five_cs_assessments_status_valid"),
        ),
        sa.CheckConstraint(
            "overall_completeness >= 0 AND overall_completeness <= 1",
            name=op.f("ck_five_cs_assessments_completeness_range"),
        ),
        sa.CheckConstraint(
            "overall_confidence >= 0 AND overall_confidence <= 1",
            name=op.f("ck_five_cs_assessments_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_five_cs_assessments_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_five_cs_assessments_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_five_cs_assessments_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_five_cs_assessments_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_five_cs_assessments_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_classification_id"],
            ["domain_classifications.id"],
            name=op.f("fk_five_cs_assessments_domain_classification_id_domain_classifications"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_analysis_run_id"],
            ["financial_analysis_runs.id"],
            name=op.f("fk_five_cs_assessments_financial_analysis_run_id_financial_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_trend_run_id"],
            ["financial_trend_runs.id"],
            name=op.f("fk_five_cs_assessments_financial_trend_run_id_financial_trend_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_assessments")),
        sa.UniqueConstraint(
            "document_id",
            "statement_scope",
            "input_hash",
            "policy_version",
            "engine_version",
            name="uq_five_cs_assessments_input",
        ),
    )
    op.create_index(
        "ix_five_cs_assessments_document_scope",
        "five_cs_assessments",
        ["document_id", "statement_scope"],
        unique=False,
    )
    op.create_index(
        "ix_five_cs_assessments_status", "five_cs_assessments", ["status"], unique=False
    )
    op.create_table(
        "five_cs_sections",
        sa.Column("five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("section", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("positive_count", sa.Integer(), nullable=False),
        sa.Column("negative_count", sa.Integer(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("summary_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "section IN ('CHARACTER','CAPACITY','CAPITAL','COLLATERAL','CONDITIONS')",
            name=op.f("ck_five_cs_sections_section_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','NEEDS_REVIEW','PARTIAL','UNAVAILABLE','CONFLICTING')",
            name=op.f("ck_five_cs_sections_status_valid"),
        ),
        sa.CheckConstraint(
            "completeness_score >= 0 AND completeness_score <= 1",
            name=op.f("ck_five_cs_sections_completeness_range"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_five_cs_sections_confidence_range"),
        ),
        sa.CheckConstraint(
            "positive_count >= 0 AND negative_count >= 0 AND review_count >= 0",
            name=op.f("ck_five_cs_sections_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f("fk_five_cs_sections_five_cs_assessment_id_five_cs_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_sections")),
        sa.UniqueConstraint(
            "five_cs_assessment_id", "section", name="uq_five_cs_sections_assessment_section"
        ),
    )
    op.create_index(
        "ix_five_cs_sections_assessment_id",
        "five_cs_sections",
        ["five_cs_assessment_id"],
        unique=False,
    )
    op.create_table(
        "five_cs_evidence",
        sa.Column("five_cs_section_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=60), nullable=False),
        sa.Column("observation_code", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("document_page_id", sa.Uuid(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "impact IN ('POSITIVE','NEGATIVE','NEUTRAL','REVIEW')",
            name=op.f("ck_five_cs_evidence_impact_valid"),
        ),
        sa.CheckConstraint(
            "source_type IS NULL OR source_type IN ('COMPANY_PROFILE','EXTRACTED_FIELD','FINANCIAL_VALUE','FINANCIAL_RATIO','FINANCIAL_TREND','FINANCIAL_ANOMALY','CREDIT_ASSESSMENT','CREDIT_SUBSCORE','DOMAIN_CLASSIFICATION','DOCUMENT_PAGE')",
            name=op.f("ck_five_cs_evidence_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','NEEDS_REVIEW','PARTIAL','UNAVAILABLE','CONFLICTING')",
            name=op.f("ck_five_cs_evidence_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_five_cs_evidence_confidence_range"),
        ),
        sa.CheckConstraint(
            "page_number IS NULL OR page_number >= 1",
            name=op.f("ck_five_cs_evidence_page_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
            name=op.f("fk_five_cs_evidence_document_page_id_document_pages"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_section_id"],
            ["five_cs_sections.id"],
            name=op.f("fk_five_cs_evidence_five_cs_section_id_five_cs_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_evidence")),
        sa.UniqueConstraint(
            "five_cs_section_id",
            "observation_code",
            "source_reference_id",
            name="uq_five_cs_evidence_observation_source",
        ),
    )
    op.create_index(
        "ix_five_cs_evidence_observation_code",
        "five_cs_evidence",
        ["observation_code"],
        unique=False,
    )
    op.create_index(
        "ix_five_cs_evidence_section_id", "five_cs_evidence", ["five_cs_section_id"], unique=False
    )
    op.create_table(
        "five_cs_review_items",
        sa.Column("five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("five_cs_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("section", sa.String(length=30), nullable=False),
        sa.Column("reason_code", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_five_cs_review_items_priority_valid"),
        ),
        sa.CheckConstraint(
            "section IN ('CHARACTER','CAPACITY','CAPITAL','COLLATERAL','CONDITIONS')",
            name=op.f("ck_five_cs_review_items_section_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESOLVED','DISMISSED')",
            name=op.f("ck_five_cs_review_items_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f("fk_five_cs_review_items_five_cs_assessment_id_five_cs_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_evidence_id"],
            ["five_cs_evidence.id"],
            name=op.f("fk_five_cs_review_items_five_cs_evidence_id_five_cs_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_review_items")),
        sa.UniqueConstraint(
            "five_cs_assessment_id", "reason_code", name="uq_five_cs_review_items_reason"
        ),
    )
    op.create_index(
        "ix_five_cs_review_items_assessment_id",
        "five_cs_review_items",
        ["five_cs_assessment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_five_cs_review_items_assessment_id", table_name="five_cs_review_items")
    op.drop_table("five_cs_review_items")
    op.drop_index("ix_five_cs_evidence_section_id", table_name="five_cs_evidence")
    op.drop_index("ix_five_cs_evidence_observation_code", table_name="five_cs_evidence")
    op.drop_table("five_cs_evidence")
    op.drop_index("ix_five_cs_sections_assessment_id", table_name="five_cs_sections")
    op.drop_table("five_cs_sections")
    op.drop_index("ix_five_cs_assessments_status", table_name="five_cs_assessments")
    op.drop_index("ix_five_cs_assessments_document_scope", table_name="five_cs_assessments")
    op.drop_table("five_cs_assessments")
    # ### end Alembic commands ###
