# ruff: noqa: E501
"""external_research

Revision ID: 0015_external_research
Revises: 0014_five_cs
Create Date: 2026-09-25 10:22:12.075673
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0015_external_research"
down_revision: str | None = "0014_five_cs"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_runs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("domain_classification_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("query_builder_version", sa.String(length=100), nullable=False),
        sa.Column("source_policy_version", sa.String(length=100), nullable=False),
        sa.Column("freshness_policy_version", sa.String(length=100), nullable=False),
        sa.Column("evidence_extractor_version", sa.String(length=100), nullable=False),
        sa.Column("finding_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coverage_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','SEARCHING','FETCHING','EXTRACTING','COMPLETED','PARTIAL','NEEDS_REVIEW','FAILED')",
            name=op.f("ck_research_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "refresh_number >= 0", name=op.f("ck_research_runs_refresh_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_research_runs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_research_runs_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_classification_id"],
            ["domain_classifications.id"],
            name=op.f("fk_research_runs_domain_classification_id_domain_classifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
        sa.UniqueConstraint(
            "company_id", "input_hash", "refresh_number", name="uq_research_runs_input_refresh"
        ),
    )
    op.create_index(
        "ix_research_runs_company_created",
        "research_runs",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_research_runs_status", "research_runs", ["status"], unique=False)
    op.create_table(
        "research_findings",
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column("finding_code", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("candidate_section", sa.String(length=30), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("first_published_at", sa.Date(), nullable=True),
        sa.Column("latest_published_at", sa.Date(), nullable=True),
        sa.Column("contradiction_code", sa.String(length=100), nullable=True),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('COMPANY','PROMOTER','LEGAL','RATINGS','INDUSTRY','SECTOR')",
            name=op.f("ck_research_findings_category_valid"),
        ),
        sa.CheckConstraint(
            "impact IN ('POSITIVE','NEGATIVE','NEUTRAL','MIXED','REVIEW')",
            name=op.f("ck_research_findings_impact_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','CORROBORATED','SINGLE_SOURCE','NEEDS_REVIEW','CONFLICTING','STALE')",
            name=op.f("ck_research_findings_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_research_findings_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_findings_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_findings")),
        sa.UniqueConstraint(
            "research_run_id",
            "finding_code",
            "entity_name",
            "event_date",
            name="uq_research_findings_event",
        ),
    )
    op.create_index(
        "ix_research_findings_category", "research_findings", ["category"], unique=False
    )
    op.create_index(
        "ix_research_findings_run", "research_findings", ["research_run_id"], unique=False
    )
    op.create_table(
        "research_queries",
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("query_text", sa.String(length=1000), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IN ('COMPANY','PROMOTER','LEGAL','RATINGS','INDUSTRY','SECTOR')",
            name=op.f("ck_research_queries_scope_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','COMPLETED','PARTIAL','FAILED','NO_VERIFIED_FINDINGS')",
            name=op.f("ck_research_queries_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_queries_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_queries")),
        sa.UniqueConstraint("research_run_id", "query_hash", name="uq_research_queries_run_hash"),
    )
    op.create_index(
        "ix_research_queries_run", "research_queries", ["research_run_id"], unique=False
    )
    op.create_table(
        "research_sources",
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column("research_query_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_tier", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("original_url", sa.String(length=2048), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("freshness_status", sa.String(length=20), nullable=False),
        sa.Column("entity_match_status", sa.String(length=30), nullable=False),
        sa.Column("entity_match_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("duplicate_of_source_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "freshness_status IN ('CURRENT','STALE','HISTORICAL','UNKNOWN')",
            name=op.f("ck_research_sources_freshness_valid"),
        ),
        sa.CheckConstraint(
            "source_type IN ('OFFICIAL','RATING_AGENCY','REGULATOR','GOVERNMENT','INDUSTRY_BODY','REPUTABLE_NEWS','OTHER')",
            name=op.f("ck_research_sources_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('RETRIEVED','REJECTED','DUPLICATE','FAILED','NEEDS_REVIEW')",
            name=op.f("ck_research_sources_status_valid"),
        ),
        sa.CheckConstraint(
            "entity_match_score >= 0 AND entity_match_score <= 1",
            name=op.f("ck_research_sources_entity_match_range"),
        ),
        sa.CheckConstraint(
            "length(trim(canonical_url)) > 0",
            name=op.f("ck_research_sources_canonical_url_nonempty"),
        ),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1",
            name=op.f("ck_research_sources_quality_range"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_source_id"],
            ["research_sources.id"],
            name=op.f("fk_research_sources_duplicate_of_source_id_research_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["research_query_id"],
            ["research_queries.id"],
            name=op.f("fk_research_sources_research_query_id_research_queries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_sources_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_sources")),
        sa.UniqueConstraint("research_run_id", "canonical_url", name="uq_research_sources_run_url"),
    )
    op.create_index(
        "ix_research_sources_publisher", "research_sources", ["publisher"], unique=False
    )
    op.create_index(
        "ix_research_sources_run", "research_sources", ["research_run_id"], unique=False
    )
    op.create_index("ix_research_sources_status", "research_sources", ["status"], unique=False)
    op.create_table(
        "research_evidence",
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column("research_source_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("event_code", sa.String(length=120), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("candidate_section", sa.String(length=30), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('COMPANY','PROMOTER','LEGAL','RATINGS','INDUSTRY','SECTOR')",
            name=op.f("ck_research_evidence_category_valid"),
        ),
        sa.CheckConstraint(
            "impact IN ('POSITIVE','NEGATIVE','NEUTRAL','MIXED','REVIEW')",
            name=op.f("ck_research_evidence_impact_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','NEEDS_REVIEW','CONFLICTING','STALE')",
            name=op.f("ck_research_evidence_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_research_evidence_confidence_range"),
        ),
        sa.CheckConstraint(
            "length(evidence_text) <= 2000", name=op.f("ck_research_evidence_evidence_length")
        ),
        sa.CheckConstraint(
            "length(trim(evidence_text)) > 0", name=op.f("ck_research_evidence_evidence_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_evidence_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_source_id"],
            ["research_sources.id"],
            name=op.f("fk_research_evidence_research_source_id_research_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_evidence")),
        sa.UniqueConstraint(
            "research_source_id", "evidence_hash", name="uq_research_evidence_source_hash"
        ),
    )
    op.create_index(
        "ix_research_evidence_category", "research_evidence", ["category"], unique=False
    )
    op.create_index(
        "ix_research_evidence_run", "research_evidence", ["research_run_id"], unique=False
    )
    op.create_table(
        "research_finding_sources",
        sa.Column("research_finding_id", sa.Uuid(), nullable=False),
        sa.Column("research_source_id", sa.Uuid(), nullable=False),
        sa.Column("research_evidence_id", sa.Uuid(), nullable=False),
        sa.Column("is_independent", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_research_finding_sources_research_evidence_id_research_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_finding_id"],
            ["research_findings.id"],
            name=op.f("fk_research_finding_sources_research_finding_id_research_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_source_id"],
            ["research_sources.id"],
            name=op.f("fk_research_finding_sources_research_source_id_research_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_finding_sources")),
        sa.UniqueConstraint(
            "research_finding_id", "research_source_id", name="uq_research_finding_sources_link"
        ),
    )
    op.create_index(
        "ix_research_finding_sources_finding",
        "research_finding_sources",
        ["research_finding_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_research_finding_sources_finding", table_name="research_finding_sources")
    op.drop_table("research_finding_sources")
    op.drop_index("ix_research_evidence_run", table_name="research_evidence")
    op.drop_index("ix_research_evidence_category", table_name="research_evidence")
    op.drop_table("research_evidence")
    op.drop_index("ix_research_sources_status", table_name="research_sources")
    op.drop_index("ix_research_sources_run", table_name="research_sources")
    op.drop_index("ix_research_sources_publisher", table_name="research_sources")
    op.drop_table("research_sources")
    op.drop_index("ix_research_queries_run", table_name="research_queries")
    op.drop_table("research_queries")
    op.drop_index("ix_research_findings_run", table_name="research_findings")
    op.drop_index("ix_research_findings_category", table_name="research_findings")
    op.drop_table("research_findings")
    op.drop_index("ix_research_runs_status", table_name="research_runs")
    op.drop_index("ix_research_runs_company_created", table_name="research_runs")
    op.drop_table("research_runs")
    # ### end Alembic commands ###
