"""research_enriched_credit_recommendation

Revision ID: 0016_research_enriched
Revises: 0015_external_research
Create Date: 2026-09-25 16:48:36.220080
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0016_research_enriched"
down_revision: str | None = "0015_external_research"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TABLE five_cs_evidence DROP CONSTRAINT ck_five_cs_evidence_source_type_valid")
    op.execute(
        "ALTER TABLE five_cs_evidence ADD CONSTRAINT ck_five_cs_evidence_source_type_valid "
        "CHECK (source_type IS NULL OR source_type IN ('COMPANY_PROFILE','EXTRACTED_FIELD',"
        "'FINANCIAL_VALUE','FINANCIAL_RATIO','FINANCIAL_TREND','FINANCIAL_ANOMALY',"
        "'CREDIT_ASSESSMENT','CREDIT_SUBSCORE','DOMAIN_CLASSIFICATION','DOCUMENT_PAGE',"
        "'RESEARCH_FINDING'))"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_recommendation_preparations",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("research_run_id", sa.Uuid(), nullable=True),
        sa.Column("fusion_experiment_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column("overall_completeness", sa.Float(), nullable=False),
        sa.Column("critical_risk_count", sa.Integer(), nullable=False),
        sa.Column("risk_count", sa.Integer(), nullable=False),
        sa.Column("strength_count", sa.Integer(), nullable=False),
        sa.Column("review_item_count", sa.Integer(), nullable=False),
        sa.Column("missing_evidence_count", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("summary_version", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('READY_FOR_DECISION_REVIEW','CONDITIONAL_REVIEW_REQUIRED','INSUFFICIENT_EVIDENCE','CRITICAL_RISK_REVIEW','DATA_CONFLICT_REVIEW','NOT_READY')",
            name=op.f("ck_credit_recommendation_preparations_status_valid"),
        ),
        sa.CheckConstraint(
            "critical_risk_count >= 0 AND risk_count >= 0 AND strength_count >= 0 AND review_item_count >= 0 AND missing_evidence_count >= 0",
            name=op.f("ck_credit_recommendation_preparations_counts_nonnegative"),
        ),
        sa.CheckConstraint(
            "overall_completeness >= 0 AND overall_completeness <= 1",
            name=op.f("ck_credit_recommendation_preparations_completeness_range"),
        ),
        sa.CheckConstraint(
            "overall_confidence >= 0 AND overall_confidence <= 1",
            name=op.f("ck_credit_recommendation_preparations_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_credit_recommendation_preparations_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_credit_recommendation_preparations_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f(
                "fk_credit_recommendation_preparations_credit_assessment_id_credit_assessments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_credit_recommendation_preparations_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f(
                "fk_credit_recommendation_preparations_five_cs_assessment_id_five_cs_assessments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["fusion_experiment_id"],
            ["credit_fusion_experiments.id"],
            name=op.f(
                "fk_credit_recommendation_preparations_fusion_experiment_id_credit_fusion_experiments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_credit_recommendation_preparations_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_recommendation_preparations")),
        sa.UniqueConstraint(
            "document_id",
            "input_hash",
            "policy_version",
            "engine_version",
            name="uq_credit_recommendation_input",
        ),
    )
    op.create_index(
        "ix_credit_recommendations_document",
        "credit_recommendation_preparations",
        ["document_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_credit_recommendations_status",
        "credit_recommendation_preparations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "five_cs_refresh_runs",
        sa.Column("base_five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("refreshed_five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("research_run_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_policy_version", sa.String(length=100), nullable=False),
        sa.Column("refresh_engine_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("updated_sections", sa.String(length=255), nullable=False),
        sa.Column("new_review_item_count", sa.Integer(), nullable=False),
        sa.Column("resolved_review_item_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('COMPLETED','NEEDS_REVIEW','FAILED')",
            name=op.f("ck_five_cs_refresh_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["base_five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f("fk_five_cs_refresh_runs_base_five_cs_assessment_id_five_cs_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["refreshed_five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f(
                "fk_five_cs_refresh_runs_refreshed_five_cs_assessment_id_five_cs_assessments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_five_cs_refresh_runs_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_refresh_runs")),
        sa.UniqueConstraint(
            "base_five_cs_assessment_id",
            "research_run_id",
            "input_hash",
            name="uq_five_cs_refresh_input",
        ),
    )
    op.create_index(
        "ix_five_cs_refresh_base",
        "five_cs_refresh_runs",
        ["base_five_cs_assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_five_cs_refresh_refreshed",
        "five_cs_refresh_runs",
        ["refreshed_five_cs_assessment_id"],
        unique=False,
    )
    op.create_table(
        "credit_recommendation_factors",
        sa.Column("recommendation_preparation_id", sa.Uuid(), nullable=False),
        sa.Column("factor_code", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_reference_id", sa.Uuid(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('STRENGTH','RISK','CRITICAL_RISK','MISSING_EVIDENCE','REVIEW_REQUIRED','EXPERIMENTAL_CONTEXT')",
            name=op.f("ck_credit_recommendation_factors_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_credit_recommendation_factors_severity_valid"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_credit_recommendation_factors_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_preparation_id"],
            ["credit_recommendation_preparations.id"],
            name=op.f(
                "fk_credit_recommendation_factors_recommendation_preparation_id_credit_recommendation_preparations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_recommendation_factors")),
        sa.UniqueConstraint(
            "recommendation_preparation_id",
            "factor_code",
            "source_type",
            "source_reference_id",
            name="uq_credit_recommendation_factor",
        ),
    )
    op.create_index(
        "ix_credit_recommendation_factors_category",
        "credit_recommendation_factors",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_credit_recommendation_factors_preparation",
        "credit_recommendation_factors",
        ["recommendation_preparation_id"],
        unique=False,
    )
    op.create_table(
        "credit_recommendation_review_items",
        sa.Column("recommendation_preparation_id", sa.Uuid(), nullable=False),
        sa.Column("review_code", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('DATA','FINANCIAL','CHARACTER','CAPACITY','CAPITAL','COLLATERAL','CONDITIONS','RESEARCH','EXPERIMENTAL')",
            name=op.f("ck_credit_recommendation_review_items_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_preparation_id"],
            ["credit_recommendation_preparations.id"],
            name=op.f(
                "fk_credit_recommendation_review_items_recommendation_preparation_id_credit_recommendation_preparations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_recommendation_review_items")),
        sa.UniqueConstraint(
            "recommendation_preparation_id", "review_code", name="uq_credit_recommendation_review"
        ),
    )
    op.create_index(
        "ix_credit_recommendation_reviews_preparation",
        "credit_recommendation_review_items",
        ["recommendation_preparation_id"],
        unique=False,
    )
    op.create_table(
        "five_cs_research_evidence_links",
        sa.Column("five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("five_cs_section_id", sa.Uuid(), nullable=False),
        sa.Column("five_cs_evidence_id", sa.Uuid(), nullable=False),
        sa.Column("research_finding_id", sa.Uuid(), nullable=False),
        sa.Column("research_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("mapping_code", sa.String(length=120), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "impact IN ('POSITIVE','NEGATIVE','NEUTRAL','MIXED','REVIEW')",
            name=op.f("ck_five_cs_research_evidence_links_impact_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED','NEEDS_REVIEW','CONFLICTING','STALE')",
            name=op.f("ck_five_cs_research_evidence_links_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f(
                "fk_five_cs_research_evidence_links_five_cs_assessment_id_five_cs_assessments"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_evidence_id"],
            ["five_cs_evidence.id"],
            name=op.f("fk_five_cs_research_evidence_links_five_cs_evidence_id_five_cs_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_section_id"],
            ["five_cs_sections.id"],
            name=op.f("fk_five_cs_research_evidence_links_five_cs_section_id_five_cs_sections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_evidence_id"],
            ["research_evidence.id"],
            name=op.f("fk_five_cs_research_evidence_links_research_evidence_id_research_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["research_finding_id"],
            ["research_findings.id"],
            name=op.f("fk_five_cs_research_evidence_links_research_finding_id_research_findings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_five_cs_research_evidence_links")),
        sa.UniqueConstraint(
            "five_cs_assessment_id",
            "research_finding_id",
            "mapping_code",
            name="uq_five_cs_research_mapping",
        ),
    )
    op.create_index(
        "ix_five_cs_research_links_assessment",
        "five_cs_research_evidence_links",
        ["five_cs_assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_five_cs_research_links_finding",
        "five_cs_research_evidence_links",
        ["research_finding_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_five_cs_research_links_finding", table_name="five_cs_research_evidence_links")
    op.drop_index(
        "ix_five_cs_research_links_assessment", table_name="five_cs_research_evidence_links"
    )
    op.drop_table("five_cs_research_evidence_links")
    op.drop_index(
        "ix_credit_recommendation_reviews_preparation",
        table_name="credit_recommendation_review_items",
    )
    op.drop_table("credit_recommendation_review_items")
    op.drop_index(
        "ix_credit_recommendation_factors_preparation", table_name="credit_recommendation_factors"
    )
    op.drop_index(
        "ix_credit_recommendation_factors_category", table_name="credit_recommendation_factors"
    )
    op.drop_table("credit_recommendation_factors")
    op.drop_index("ix_five_cs_refresh_refreshed", table_name="five_cs_refresh_runs")
    op.drop_index("ix_five_cs_refresh_base", table_name="five_cs_refresh_runs")
    op.drop_table("five_cs_refresh_runs")
    op.drop_index(
        "ix_credit_recommendations_status", table_name="credit_recommendation_preparations"
    )
    op.drop_index(
        "ix_credit_recommendations_document", table_name="credit_recommendation_preparations"
    )
    op.drop_table("credit_recommendation_preparations")
    op.execute("ALTER TABLE five_cs_evidence DROP CONSTRAINT ck_five_cs_evidence_source_type_valid")
    op.execute(
        "ALTER TABLE five_cs_evidence ADD CONSTRAINT ck_five_cs_evidence_source_type_valid "
        "CHECK (source_type IS NULL OR source_type IN ('COMPANY_PROFILE','EXTRACTED_FIELD',"
        "'FINANCIAL_VALUE','FINANCIAL_RATIO','FINANCIAL_TREND','FINANCIAL_ANOMALY',"
        "'CREDIT_ASSESSMENT','CREDIT_SUBSCORE','DOMAIN_CLASSIFICATION','DOCUMENT_PAGE'))"
    )
    # ### end Alembic commands ###
