"""credit_decision_support

Revision ID: 0017_credit_decision_support
Revises: 0016_research_enriched
Create Date: 2026-09-25 17:25:03.595896
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0017_credit_decision_support"
down_revision: str | None = "0016_research_enriched"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_decision_support",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("credit_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("five_cs_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_preparation_id", sa.Uuid(), nullable=False),
        sa.Column("research_run_id", sa.Uuid(), nullable=True),
        sa.Column("fusion_experiment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "statement_scope",
            sa.Enum(
                "STANDALONE",
                "CONSOLIDATED",
                "UNKNOWN",
                name="financialscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("system_recommendation", sa.String(length=40), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("blocking_gate_count", sa.Integer(), nullable=False),
        sa.Column("review_gate_count", sa.Integer(), nullable=False),
        sa.Column("exception_count", sa.Integer(), nullable=False),
        sa.Column("production_ml_used", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("summary_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("human_decision", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "human_decision IS NULL OR human_decision IN ('APPROVED','DECLINED','RETURNED_FOR_INFORMATION')",
            name=op.f("ck_credit_decision_support_human_decision_valid"),
        ),
        sa.CheckConstraint(
            "system_recommendation IN ('FAVORABLE_REVIEW','CONDITIONAL_REVIEW','MANUAL_REVIEW_REQUIRED','ADVERSE_REVIEW','INSUFFICIENT_EVIDENCE','POLICY_EXCEPTION_REVIEW')",
            name=op.f("ck_credit_decision_support_recommendation_valid"),
        ),
        sa.CheckConstraint(
            "blocking_gate_count >= 0 AND review_gate_count >= 0 AND exception_count >= 0",
            name=op.f("ck_credit_decision_support_counts_nonnegative"),
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1 AND completeness_score BETWEEN 0 AND 1",
            name=op.f("ck_credit_decision_support_scores_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_credit_decision_support_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_credit_decision_support_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_assessment_id"],
            ["credit_assessments.id"],
            name=op.f("fk_credit_decision_support_credit_assessment_id_credit_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_credit_decision_support_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["five_cs_assessment_id"],
            ["five_cs_assessments.id"],
            name=op.f("fk_credit_decision_support_five_cs_assessment_id_five_cs_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["fusion_experiment_id"],
            ["credit_fusion_experiments.id"],
            name=op.f("fk_credit_decision_support_fusion_experiment_id_credit_fusion_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_preparation_id"],
            ["credit_recommendation_preparations.id"],
            name=op.f(
                "fk_credit_decision_support_recommendation_preparation_id_credit_recommendation_preparations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_credit_decision_support_research_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_decision_support")),
        sa.UniqueConstraint(
            "document_id",
            "statement_scope",
            "recommendation_preparation_id",
            "input_hash",
            "policy_version",
            "engine_version",
            name="uq_credit_decision_input",
        ),
    )
    op.create_index(
        "ix_credit_decision_document_scope",
        "credit_decision_support",
        ["document_id", "statement_scope", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_credit_decision_recommendation",
        "credit_decision_support",
        ["system_recommendation"],
        unique=False,
    )
    op.create_table(
        "credit_decision_gates",
        sa.Column("credit_decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("gate_code", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("exception_eligible", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("source_type", sa.String(length=60), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('FINANCIAL','REPAYMENT_CAPACITY','CAPITAL','COLLATERAL','CHARACTER_RESEARCH','CONDITIONS','LEGAL_REGULATORY','DATA_QUALITY','RESEARCH_COVERAGE','POLICY_EXCEPTION')",
            name=op.f("ck_credit_decision_gates_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_credit_decision_gates_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PASS','PASS_WITH_REVIEW','FAIL_REVIEW','INSUFFICIENT_DATA','CONFLICTING')",
            name=op.f("ck_credit_decision_gates_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_credit_decision_gates_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f(
                "fk_credit_decision_gates_credit_decision_support_id_credit_decision_support"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_decision_gates")),
        sa.UniqueConstraint(
            "credit_decision_support_id", "gate_code", name="uq_credit_decision_gate"
        ),
    )
    op.create_index(
        "ix_credit_decision_gates_support",
        "credit_decision_gates",
        ["credit_decision_support_id"],
        unique=False,
    )
    op.create_table(
        "credit_decision_review_items",
        sa.Column("credit_decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("review_code", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("source_type", sa.String(length=60), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_credit_decision_review_items_priority_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f(
                "fk_credit_decision_review_items_credit_decision_support_id_credit_decision_support"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_decision_review_items")),
        sa.UniqueConstraint(
            "credit_decision_support_id", "review_code", name="uq_credit_decision_review"
        ),
    )
    op.create_index(
        "ix_credit_decision_reviews_support",
        "credit_decision_review_items",
        ["credit_decision_support_id"],
        unique=False,
    )
    op.create_table(
        "credit_limit_methods",
        sa.Column("credit_decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("method_code", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("calculated_limit", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("formula_version", sa.String(length=100), nullable=False),
        sa.Column("input_summary_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','UNAVAILABLE','BLOCKED','NEEDS_REVIEW')",
            name=op.f("ck_credit_limit_methods_status_valid"),
        ),
        sa.CheckConstraint(
            "calculated_limit IS NULL OR calculated_limit >= 0",
            name=op.f("ck_credit_limit_methods_limit_nonnegative"),
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_credit_limit_methods_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f("fk_credit_limit_methods_credit_decision_support_id_credit_decision_support"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_limit_methods")),
        sa.UniqueConstraint(
            "credit_decision_support_id", "method_code", name="uq_credit_limit_method"
        ),
    )
    op.create_index(
        "ix_credit_limit_methods_support",
        "credit_limit_methods",
        ["credit_decision_support_id"],
        unique=False,
    )
    op.create_table(
        "credit_limit_preparations",
        sa.Column("credit_decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("lower_bound", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("upper_bound", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("analytical_ceiling", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("method_count", sa.Integer(), nullable=False),
        sa.Column("existing_exposure_status", sa.String(length=50), nullable=False),
        sa.Column("projected_ratios_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','PARTIAL','UNAVAILABLE','NEEDS_REVIEW')",
            name=op.f("ck_credit_limit_preparations_status_valid"),
        ),
        sa.CheckConstraint(
            "analytical_ceiling IS NULL OR analytical_ceiling >= 0",
            name=op.f("ck_credit_limit_preparations_ceiling_nonnegative"),
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_credit_limit_preparations_confidence_range"),
        ),
        sa.CheckConstraint(
            "lower_bound IS NULL OR lower_bound >= 0",
            name=op.f("ck_credit_limit_preparations_lower_nonnegative"),
        ),
        sa.CheckConstraint(
            "upper_bound IS NULL OR upper_bound >= 0",
            name=op.f("ck_credit_limit_preparations_upper_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f(
                "fk_credit_limit_preparations_credit_decision_support_id_credit_decision_support"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_limit_preparations")),
        sa.UniqueConstraint("credit_decision_support_id", name="uq_credit_limit_support"),
    )
    op.create_table(
        "credit_policy_exceptions",
        sa.Column("credit_decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("exception_code", sa.String(length=150), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("required_authority", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("source_type", sa.String(length=60), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','WAIVED','APPROVED_BY_HUMAN','REJECTED_BY_HUMAN')",
            name=op.f("ck_credit_policy_exceptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f(
                "fk_credit_policy_exceptions_credit_decision_support_id_credit_decision_support"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_policy_exceptions")),
        sa.UniqueConstraint(
            "credit_decision_support_id", "exception_code", name="uq_credit_policy_exception"
        ),
    )
    op.create_index(
        "ix_credit_policy_exceptions_support",
        "credit_policy_exceptions",
        ["credit_decision_support_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credit_policy_exceptions_support", table_name="credit_policy_exceptions")
    op.drop_table("credit_policy_exceptions")
    op.drop_table("credit_limit_preparations")
    op.drop_index("ix_credit_limit_methods_support", table_name="credit_limit_methods")
    op.drop_table("credit_limit_methods")
    op.drop_index("ix_credit_decision_reviews_support", table_name="credit_decision_review_items")
    op.drop_table("credit_decision_review_items")
    op.drop_index("ix_credit_decision_gates_support", table_name="credit_decision_gates")
    op.drop_table("credit_decision_gates")
    op.drop_index("ix_credit_decision_recommendation", table_name="credit_decision_support")
    op.drop_index("ix_credit_decision_document_scope", table_name="credit_decision_support")
    op.drop_table("credit_decision_support")
    # ### end Alembic commands ###
