"""human_credit_review

Revision ID: 0018_human_credit_review
Revises: 0017_credit_decision_support
Create Date: 2026-09-25 17:52:34.901049
"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0018_human_credit_review"
down_revision: str | None = "0017_credit_decision_support"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_review_cases",
        sa.Column("decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_status", sa.String(length=40), nullable=False),
        sa.Column("primary_reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_version", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('LOW','NORMAL','HIGH','URGENT')",
            name=op.f("ck_credit_review_cases_priority_valid"),
        ),
        sa.CheckConstraint(
            "workflow_status IN ('PENDING_REVIEW','ASSIGNED','IN_REVIEW','AWAITING_INFORMATION','AWAITING_EXCEPTION_APPROVAL','READY_FOR_DECISION','REFERRED_TO_COMMITTEE','DECIDED','CLOSED','CANCELLED','STALE','UPDATED_ANALYSIS_AVAILABLE')",
            name=op.f("ck_credit_review_cases_workflow_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_credit_review_cases_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_credit_review_cases_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f("fk_credit_review_cases_decision_support_id_credit_decision_support"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_credit_review_cases_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["primary_reviewer_id"],
            ["users.id"],
            name=op.f("fk_credit_review_cases_primary_reviewer_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_review_cases")),
        sa.UniqueConstraint(
            "decision_support_id", "input_hash", name="uq_credit_review_case_input"
        ),
    )
    op.create_index(
        "ix_credit_review_cases_reviewer",
        "credit_review_cases",
        ["primary_reviewer_id", "workflow_status"],
        unique=False,
    )
    op.create_index(
        "ix_credit_review_cases_workflow",
        "credit_review_cases",
        ["workflow_status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "credit_committee_packages",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("package_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prepared_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("summary_version", sa.String(length=100), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','READY','SUPERSEDED')",
            name=op.f("ck_credit_committee_packages_status_valid"),
        ),
        sa.CheckConstraint(
            "package_version > 0", name=op.f("ck_credit_committee_packages_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f("fk_credit_committee_packages_decision_support_id_credit_decision_support"),
        ),
        sa.ForeignKeyConstraint(
            ["prepared_by_user_id"],
            ["users.id"],
            name=op.f("fk_credit_committee_packages_prepared_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_committee_packages_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_committee_packages")),
        sa.UniqueConstraint(
            "review_case_id", "input_hash", name="uq_credit_committee_package_input"
        ),
        sa.UniqueConstraint(
            "review_case_id", "package_version", name="uq_credit_committee_package_version"
        ),
    )
    op.create_index(
        op.f("ix_credit_committee_packages_review_case_id"),
        "credit_committee_packages",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_human_decisions",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("decision_rationale", sa.Text(), nullable=False),
        sa.Column("decision_authority_role", sa.String(length=50), nullable=False),
        sa.Column("approved_limit", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("conditions_json", sa.JSON(), nullable=True),
        sa.Column("override_rationale", sa.Text(), nullable=True),
        sa.Column("decision_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("decision_version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("superseded_decision_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "decision IN ('APPROVED','DECLINED','RETURNED_FOR_INFORMATION','REFERRED_TO_COMMITTEE')",
            name=op.f("ck_credit_human_decisions_decision_valid"),
        ),
        sa.CheckConstraint(
            "approved_limit IS NULL OR approved_limit >= 0",
            name=op.f("ck_credit_human_decisions_approved_limit_nonnegative"),
        ),
        sa.CheckConstraint(
            "approved_limit IS NULL OR currency IS NOT NULL",
            name=op.f("ck_credit_human_decisions_approved_limit_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_credit_human_decisions_decided_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f("fk_credit_human_decisions_decision_support_id_credit_decision_support"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_human_decisions_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_decision_id"],
            ["credit_human_decisions.id"],
            name=op.f("fk_credit_human_decisions_superseded_decision_id_credit_human_decisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_human_decisions")),
        sa.UniqueConstraint(
            "review_case_id", "decision_version", name="uq_credit_human_decision_version"
        ),
    )
    op.create_index(
        "uq_credit_human_decision_current",
        "credit_human_decisions",
        ["review_case_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "credit_information_requests",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("request_code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RECEIVED','PARTIALLY_RECEIVED','CLOSED','CANCELLED')",
            name=op.f("ck_credit_information_requests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_credit_information_requests_requested_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_information_requests_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_information_requests")),
    )
    op.create_index(
        op.f("ix_credit_information_requests_review_case_id"),
        "credit_information_requests",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_policy_exception_actions",
        sa.Column("policy_exception_id", sa.Uuid(), nullable=False),
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("authority_role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('APPROVE_EXCEPTION','REJECT_EXCEPTION','REQUEST_INFORMATION','REFER_HIGHER')",
            name=op.f("ck_credit_policy_exception_actions_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_credit_policy_exception_actions_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_exception_id"],
            ["credit_policy_exceptions.id"],
            name=op.f(
                "fk_credit_policy_exception_actions_policy_exception_id_credit_policy_exceptions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_policy_exception_actions_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_policy_exception_actions")),
    )
    op.create_index(
        op.f("ix_credit_policy_exception_actions_policy_exception_id"),
        "credit_policy_exception_actions",
        ["policy_exception_id"],
        unique=False,
    )
    op.create_table(
        "credit_review_assignments",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
            name=op.f("fk_credit_review_assignments_assigned_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_review_assignments_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_credit_review_assignments_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_review_assignments")),
    )
    op.create_index(
        op.f("ix_credit_review_assignments_review_case_id"),
        "credit_review_assignments",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_review_checklist_actions",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("decision_review_item_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('ACKNOWLEDGED','RESOLVED','NEEDS_INFORMATION','ESCALATED','NOT_APPLICABLE')",
            name=op.f("ck_credit_review_checklist_actions_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_review_item_id"],
            ["credit_decision_review_items.id"],
            name=op.f(
                "fk_credit_review_checklist_actions_decision_review_item_id_credit_decision_review_items"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_review_checklist_actions_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_credit_review_checklist_actions_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_review_checklist_actions")),
    )
    op.create_index(
        op.f("ix_credit_review_checklist_actions_review_case_id"),
        "credit_review_checklist_actions",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_review_comments",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column("comment_type", sa.String(length=30), nullable=False),
        sa.Column("comment_text", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=30), nullable=False),
        sa.Column("source_reference_type", sa.String(length=80), nullable=True),
        sa.Column("source_reference_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "comment_type IN ('GENERAL','RISK_NOTE','EVIDENCE_NOTE','INFORMATION_REQUEST','EXCEPTION_NOTE','COMMITTEE_NOTE','DECISION_RATIONALE')",
            name=op.f("ck_credit_review_comments_comment_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_credit_review_comments_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_credit_review_comments_review_case_id_credit_review_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_review_comments")),
    )
    op.create_index(
        op.f("ix_credit_review_comments_review_case_id"),
        "credit_review_comments",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_review_evidence_acknowledgements",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_reference_id", sa.Uuid(), nullable=False),
        sa.Column("acknowledgement_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "acknowledgement_status IN ('REVIEWED','ACCEPTED_FOR_REVIEW','QUESTIONED','CONFLICT_NOTED','NOT_APPLICABLE')",
            name=op.f("ck_credit_review_evidence_acknowledgements_ack_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f(
                "fk_credit_review_evidence_acknowledgements_review_case_id_credit_review_cases"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_credit_review_evidence_acknowledgements_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_review_evidence_acknowledgements")),
    )
    op.create_index(
        op.f("ix_credit_review_evidence_acknowledgements_review_case_id"),
        "credit_review_evidence_acknowledgements",
        ["review_case_id"],
        unique=False,
    )
    op.create_table(
        "credit_committee_package_sections",
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("section_code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("structured_payload_json", sa.JSON(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["credit_committee_packages.id"],
            name=op.f("fk_credit_committee_package_sections_package_id_credit_committee_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_committee_package_sections")),
        sa.UniqueConstraint("package_id", "section_code", name="uq_credit_committee_section"),
    )
    op.create_index(
        op.f("ix_credit_committee_package_sections_package_id"),
        "credit_committee_package_sections",
        ["package_id"],
        unique=False,
    )
    op.create_table(
        "credit_decision_overrides",
        sa.Column("human_decision_id", sa.Uuid(), nullable=False),
        sa.Column("override_type", sa.String(length=50), nullable=False),
        sa.Column("system_value", sa.Text(), nullable=False),
        sa.Column("human_value", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "override_type IN ('SYSTEM_RECOMMENDATION_OVERRIDE','LIMIT_OVERRIDE','POLICY_EXCEPTION_OVERRIDE')",
            name=op.f("ck_credit_decision_overrides_override_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["human_decision_id"],
            ["credit_human_decisions.id"],
            name=op.f("fk_credit_decision_overrides_human_decision_id_credit_human_decisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_decision_overrides")),
    )
    op.create_index(
        op.f("ix_credit_decision_overrides_human_decision_id"),
        "credit_decision_overrides",
        ["human_decision_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "reviewer_role", sa.String(length=50), server_default="CREDIT_ANALYST", nullable=False
        ),
    )
    op.create_check_constraint(
        op.f("ck_users_reviewer_role_valid"),
        "users",
        "reviewer_role IN ('CREDIT_ANALYST','SENIOR_CREDIT_REVIEWER','CREDIT_MANAGER','CREDIT_COMMITTEE_MEMBER','ADMIN')",
    )
    op.drop_constraint(
        op.f("ck_credit_policy_exceptions_status_valid"), "credit_policy_exceptions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_credit_policy_exceptions_status_valid"),
        "credit_policy_exceptions",
        "status IN ('OPEN','WAIVED','APPROVED_BY_HUMAN','REJECTED_BY_HUMAN','MORE_INFORMATION_REQUIRED','REFERRED_TO_HIGHER_AUTHORITY')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_credit_policy_exceptions_status_valid"), "credit_policy_exceptions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_credit_policy_exceptions_status_valid"),
        "credit_policy_exceptions",
        "status IN ('OPEN','WAIVED','APPROVED_BY_HUMAN','REJECTED_BY_HUMAN')",
    )
    op.drop_constraint(op.f("ck_users_reviewer_role_valid"), "users", type_="check")
    op.drop_column("users", "reviewer_role")
    op.drop_index(
        op.f("ix_credit_decision_overrides_human_decision_id"),
        table_name="credit_decision_overrides",
    )
    op.drop_table("credit_decision_overrides")
    op.drop_index(
        op.f("ix_credit_committee_package_sections_package_id"),
        table_name="credit_committee_package_sections",
    )
    op.drop_table("credit_committee_package_sections")
    op.drop_index(
        op.f("ix_credit_review_evidence_acknowledgements_review_case_id"),
        table_name="credit_review_evidence_acknowledgements",
    )
    op.drop_table("credit_review_evidence_acknowledgements")
    op.drop_index(
        op.f("ix_credit_review_comments_review_case_id"), table_name="credit_review_comments"
    )
    op.drop_table("credit_review_comments")
    op.drop_index(
        op.f("ix_credit_review_checklist_actions_review_case_id"),
        table_name="credit_review_checklist_actions",
    )
    op.drop_table("credit_review_checklist_actions")
    op.drop_index(
        op.f("ix_credit_review_assignments_review_case_id"), table_name="credit_review_assignments"
    )
    op.drop_table("credit_review_assignments")
    op.drop_index(
        op.f("ix_credit_policy_exception_actions_policy_exception_id"),
        table_name="credit_policy_exception_actions",
    )
    op.drop_table("credit_policy_exception_actions")
    op.drop_index(
        op.f("ix_credit_information_requests_review_case_id"),
        table_name="credit_information_requests",
    )
    op.drop_table("credit_information_requests")
    op.drop_index(
        "uq_credit_human_decision_current",
        table_name="credit_human_decisions",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_table("credit_human_decisions")
    op.drop_index(
        op.f("ix_credit_committee_packages_review_case_id"), table_name="credit_committee_packages"
    )
    op.drop_table("credit_committee_packages")
    op.drop_index("ix_credit_review_cases_workflow", table_name="credit_review_cases")
    op.drop_index("ix_credit_review_cases_reviewer", table_name="credit_review_cases")
    op.drop_table("credit_review_cases")
    # ### end Alembic commands ###
