"""reporting_and_cam

Revision ID: 0019_reporting_and_cam
Revises: 0018_human_credit_review
Create Date: 2026-09-25 22:11:56.176975
"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0019_reporting_and_cam"
down_revision: str | None = "0018_human_credit_review"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_reports",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("decision_support_id", sa.Uuid(), nullable=False),
        sa.Column("human_decision_id", sa.Uuid(), nullable=True),
        sa.Column("committee_package_id", sa.Uuid(), nullable=True),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("template_version", sa.String(length=100), nullable=False),
        sa.Column("renderer_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("confidentiality_label", sa.String(length=40), nullable=False),
        sa.Column("generated_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("finalized_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_report_id", sa.Uuid(), nullable=True),
        sa.Column("superseded_by_report_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "report_type IN ('CAM','CREDIT_COMMITTEE_MEMO','DECISION_EVIDENCE_PACK','STRUCTURED_JSON_EXPORT')",
            name=op.f("ck_generated_reports_report_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','GENERATED','FINALIZED','SUPERSEDED','FAILED')",
            name=op.f("ck_generated_reports_status_valid"),
        ),
        sa.CheckConstraint(
            "report_version > 0", name=op.f("ck_generated_reports_version_positive")
        ),
        sa.CheckConstraint(
            "(status IN ('FINALIZED','SUPERSEDED') AND finalized_at IS NOT NULL AND finalized_by_user_id IS NOT NULL) OR (status NOT IN ('FINALIZED','SUPERSEDED') AND finalized_at IS NULL AND finalized_by_user_id IS NULL)",
            name=op.f("ck_generated_reports_finalization_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_generated_reports_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["committee_package_id"],
            ["credit_committee_packages.id"],
            name=op.f("fk_generated_reports_committee_package_id_credit_committee_packages"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_generated_reports_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["decision_support_id"],
            ["credit_decision_support.id"],
            name=op.f("fk_generated_reports_decision_support_id_credit_decision_support"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_generated_reports_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["finalized_by_user_id"],
            ["users.id"],
            name=op.f("fk_generated_reports_finalized_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
            name=op.f("fk_generated_reports_generated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["human_decision_id"],
            ["credit_human_decisions.id"],
            name=op.f("fk_generated_reports_human_decision_id_credit_human_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_generated_reports_review_case_id_credit_review_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_generated_reports_superseded_by_report_id_generated_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_generated_reports_supersedes_report_id_generated_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_reports")),
        sa.UniqueConstraint(
            "review_case_id",
            "report_type",
            "input_hash",
            "template_version",
            "renderer_version",
            name="uq_generated_report_input",
        ),
        sa.UniqueConstraint(
            "review_case_id", "report_type", "report_version", name="uq_generated_report_version"
        ),
    )
    op.create_index(
        "ix_generated_reports_case_type",
        "generated_reports",
        ["review_case_id", "report_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "report_artifacts",
        sa.Column("generated_report_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_type", sa.String(length=20), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "artifact_type IN ('REPORT','SNAPSHOT')",
            name=op.f("ck_report_artifacts_artifact_type_valid"),
        ),
        sa.CheckConstraint(
            "format IN ('PDF','JSON')", name=op.f("ck_report_artifacts_format_valid")
        ),
        sa.CheckConstraint(
            "char_length(sha256) = 64", name=op.f("ck_report_artifacts_sha256_valid")
        ),
        sa.CheckConstraint("file_size_bytes > 0", name=op.f("ck_report_artifacts_size_positive")),
        sa.ForeignKeyConstraint(
            ["generated_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_report_artifacts_generated_report_id_generated_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_artifacts")),
        sa.UniqueConstraint("generated_report_id", "format", name="uq_report_artifact_format"),
    )
    op.create_index(
        op.f("ix_report_artifacts_generated_report_id"),
        "report_artifacts",
        ["generated_report_id"],
        unique=False,
    )
    op.create_table(
        "report_finalization_actions",
        sa.Column("generated_report_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('FINALIZED','SUPERSEDED')",
            name=op.f("ck_report_finalization_actions_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_report_finalization_actions_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_report_finalization_actions_generated_report_id_generated_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_finalization_actions")),
    )
    op.create_index(
        op.f("ix_report_finalization_actions_generated_report_id"),
        "report_finalization_actions",
        ["generated_report_id"],
        unique=False,
    )
    op.create_table(
        "report_snapshots",
        sa.Column("generated_report_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "snapshot_version > 0", name=op.f("ck_report_snapshots_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["generated_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_report_snapshots_generated_report_id_generated_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshots")),
        sa.UniqueConstraint("generated_report_id", name="uq_report_snapshot_report"),
    )
    op.create_table(
        "report_source_links",
        sa.Column("generated_report_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("source_reference_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_role", sa.String(length=100), nullable=False),
        sa.Column("source_metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_report_id"],
            ["generated_reports.id"],
            name=op.f("fk_report_source_links_generated_report_id_generated_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_source_links")),
        sa.UniqueConstraint(
            "generated_report_id",
            "source_type",
            "source_reference_id",
            name="uq_report_source_link",
        ),
    )
    op.create_index(
        op.f("ix_report_source_links_generated_report_id"),
        "report_source_links",
        ["generated_report_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_report_source_links_generated_report_id"), table_name="report_source_links"
    )
    op.drop_table("report_source_links")
    op.drop_table("report_snapshots")
    op.drop_index(
        op.f("ix_report_finalization_actions_generated_report_id"),
        table_name="report_finalization_actions",
    )
    op.drop_table("report_finalization_actions")
    op.drop_index(op.f("ix_report_artifacts_generated_report_id"), table_name="report_artifacts")
    op.drop_table("report_artifacts")
    op.drop_index("ix_generated_reports_case_type", table_name="generated_reports")
    op.drop_table("generated_reports")
    # ### end Alembic commands ###
