"""rag_and_analyst_assistant

Revision ID: 0020_rag_and_analyst_assistant
Revises: 0019_reporting_and_cam
Create Date: 2026-09-25 23:04:56.147520
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0020_rag_and_analyst_assistant"
down_revision: str | None = "0019_reporting_and_cam"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_index_runs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("index_version", sa.String(length=100), nullable=False),
        sa.Column("chunk_builder_version", sa.String(length=100), nullable=False),
        sa.Column("embedding_provider", sa.String(length=100), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("new_chunk_count", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','BUILDING','COMPLETED','PARTIAL','FAILED')",
            name=op.f("ck_rag_index_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_rag_index_runs_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_index_runs")),
        sa.UniqueConstraint(
            "company_id",
            "index_version",
            "embedding_version",
            "input_hash",
            name="uq_rag_index_input",
        ),
    )
    op.create_index(
        "ix_rag_index_runs_company_created",
        "rag_index_runs",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "rag_chunks",
        sa.Column("index_run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_reference_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.String(length=150), nullable=False),
        sa.Column("section_type", sa.String(length=100), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("statement_scope", sa.String(length=30), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("source_priority", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("source_metadata_json", sa.JSON(), nullable=True),
        sa.Column("index_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "char_length(chunk_hash) = 64", name=op.f("ck_rag_chunks_chunk_hash_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_rag_chunks_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_rag_chunks_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["index_run_id"],
            ["rag_index_runs.id"],
            name=op.f("fk_rag_chunks_index_run_id_rag_index_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_chunks")),
        sa.UniqueConstraint(
            "company_id",
            "source_type",
            "source_reference_id",
            "source_version",
            "chunk_hash",
            "index_version",
            name="uq_rag_chunk_source_version",
        ),
    )
    op.create_index(
        "ix_rag_chunks_company_current", "rag_chunks", ["company_id", "is_current"], unique=False
    )
    op.create_index(
        "ix_rag_chunks_source", "rag_chunks", ["source_type", "source_reference_id"], unique=False
    )
    op.create_table(
        "rag_embeddings",
        sa.Column("rag_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_provider", sa.String(length=100), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_version", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("embedding_json", sa.JSON(), nullable=False),
        sa.Column("embedding_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("dimension > 0", name=op.f("ck_rag_embeddings_dimension_positive")),
        sa.ForeignKeyConstraint(
            ["rag_chunk_id"],
            ["rag_chunks.id"],
            name=op.f("fk_rag_embeddings_rag_chunk_id_rag_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_embeddings")),
        sa.UniqueConstraint("rag_chunk_id", "embedding_version", name="uq_rag_embedding_version"),
    )
    op.create_index(
        op.f("ix_rag_embeddings_rag_chunk_id"), "rag_embeddings", ["rag_chunk_id"], unique=False
    )
    op.create_table(
        "analyst_chat_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("review_case_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_analyst_chat_sessions_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_analyst_chat_sessions_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["credit_review_cases.id"],
            name=op.f("fk_analyst_chat_sessions_review_case_id_credit_review_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_analyst_chat_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyst_chat_sessions")),
    )
    op.create_table(
        "analyst_chat_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("query_type", sa.String(length=50), nullable=True),
        sa.Column("answer_status", sa.String(length=40), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("model_provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "role IN ('USER','ASSISTANT')", name=op.f("ck_analyst_chat_messages_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analyst_chat_sessions.id"],
            name=op.f("fk_analyst_chat_messages_session_id_analyst_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyst_chat_messages")),
    )
    op.create_index(
        "ix_analyst_messages_session_created",
        "analyst_chat_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "rag_query_runs",
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("user_message_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("query_type", sa.String(length=50), nullable=False),
        sa.Column("filters_json", sa.JSON(), nullable=True),
        sa.Column("retrieval_policy_version", sa.String(length=100), nullable=False),
        sa.Column("chunk_index_version", sa.String(length=100), nullable=False),
        sa.Column("model_provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('COMPLETED','INSUFFICIENT_EVIDENCE','CONFLICTING_EVIDENCE','FAILED')",
            name=op.f("ck_rag_query_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_rag_query_runs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_rag_query_runs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analyst_chat_sessions.id"],
            name=op.f("fk_rag_query_runs_session_id_analyst_chat_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id"],
            ["analyst_chat_messages.id"],
            name=op.f("fk_rag_query_runs_user_message_id_analyst_chat_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_query_runs")),
    )
    op.create_index(
        "ix_rag_queries_company_created",
        "rag_query_runs",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "rag_answers",
        sa.Column("rag_query_run_id", sa.Uuid(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("answer_status", sa.String(length=40), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("unsupported_claim_count", sa.Integer(), nullable=False),
        sa.Column("citation_coverage_ratio", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "answer_status IN ('ANSWERED','PARTIAL','INSUFFICIENT_EVIDENCE','CONFLICTING_EVIDENCE','REQUIRES_HUMAN_REVIEW','FAILED')",
            name=op.f("ck_rag_answers_answer_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["rag_query_run_id"],
            ["rag_query_runs.id"],
            name=op.f("fk_rag_answers_rag_query_run_id_rag_query_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_answers")),
        sa.UniqueConstraint("rag_query_run_id", name="uq_rag_answer_query"),
    )
    op.create_table(
        "rag_retrieval_results",
        sa.Column("rag_query_run_id", sa.Uuid(), nullable=False),
        sa.Column("rag_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=False),
        sa.Column("keyword_score", sa.Float(), nullable=False),
        sa.Column("combined_score", sa.Float(), nullable=False),
        sa.Column("selected_for_context", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rag_chunk_id"],
            ["rag_chunks.id"],
            name=op.f("fk_rag_retrieval_results_rag_chunk_id_rag_chunks"),
        ),
        sa.ForeignKeyConstraint(
            ["rag_query_run_id"],
            ["rag_query_runs.id"],
            name=op.f("fk_rag_retrieval_results_rag_query_run_id_rag_query_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_retrieval_results")),
        sa.UniqueConstraint("rag_query_run_id", "rank", name="uq_rag_retrieval_rank"),
    )
    op.create_index(
        op.f("ix_rag_retrieval_results_rag_query_run_id"),
        "rag_retrieval_results",
        ["rag_query_run_id"],
        unique=False,
    )
    op.create_table(
        "rag_answer_citations",
        sa.Column("rag_answer_id", sa.Uuid(), nullable=False),
        sa.Column("rag_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("citation_index", sa.Integer(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_reference_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rag_answer_id"],
            ["rag_answers.id"],
            name=op.f("fk_rag_answer_citations_rag_answer_id_rag_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rag_chunk_id"],
            ["rag_chunks.id"],
            name=op.f("fk_rag_answer_citations_rag_chunk_id_rag_chunks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_answer_citations")),
        sa.UniqueConstraint("rag_answer_id", "citation_index", name="uq_rag_answer_citation_index"),
    )
    op.create_index(
        op.f("ix_rag_answer_citations_rag_answer_id"),
        "rag_answer_citations",
        ["rag_answer_id"],
        unique=False,
    )
    op.create_table(
        "rag_answer_feedback",
        sa.Column("rag_answer_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "rating IN ('HELPFUL','NOT_HELPFUL','INCORRECT','MISSING_SOURCE')",
            name=op.f("ck_rag_answer_feedback_rating_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["rag_answer_id"],
            ["rag_answers.id"],
            name=op.f("fk_rag_answer_feedback_rag_answer_id_rag_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rag_answer_feedback_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_answer_feedback")),
        sa.UniqueConstraint("rag_answer_id", "user_id", name="uq_rag_feedback_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rag_answer_feedback")
    op.drop_index(op.f("ix_rag_answer_citations_rag_answer_id"), table_name="rag_answer_citations")
    op.drop_table("rag_answer_citations")
    op.drop_index(
        op.f("ix_rag_retrieval_results_rag_query_run_id"), table_name="rag_retrieval_results"
    )
    op.drop_table("rag_retrieval_results")
    op.drop_table("rag_answers")
    op.drop_index("ix_rag_queries_company_created", table_name="rag_query_runs")
    op.drop_table("rag_query_runs")
    op.drop_index("ix_analyst_messages_session_created", table_name="analyst_chat_messages")
    op.drop_table("analyst_chat_messages")
    op.drop_table("analyst_chat_sessions")
    op.drop_index(op.f("ix_rag_embeddings_rag_chunk_id"), table_name="rag_embeddings")
    op.drop_table("rag_embeddings")
    op.drop_index("ix_rag_chunks_source", table_name="rag_chunks")
    op.drop_index("ix_rag_chunks_company_current", table_name="rag_chunks")
    op.drop_table("rag_chunks")
    op.drop_index("ix_rag_index_runs_company_created", table_name="rag_index_runs")
    op.drop_table("rag_index_runs")
    # ### end Alembic commands ###
