"""stock_universe_peer_market_data

Revision ID: 0021_stock_universe_peer_market_data
Revises: 0020_rag_and_analyst_assistant
Create Date: 2026-09-27 18:46:22.950896
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0021_stock_universe_peer_market_data"
down_revision: str | None = "0020_rag_and_analyst_assistant"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column("alembic_version", "version_num", type_=sa.String(length=64))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listed_companies",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("isin", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("sub_domain", sa.String(length=100), nullable=True),
        sa.Column("business_description", sa.Text(), nullable=True),
        sa.Column("products_json", sa.JSON(), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=True),
        sa.Column("classification_status", sa.String(length=30), nullable=False),
        sa.Column("entity_match_status", sa.String(length=30), nullable=False),
        sa.Column("source_provider", sa.String(length=100), nullable=False),
        sa.Column("source_version", sa.String(length=100), nullable=False),
        sa.Column("universe_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listed_companies")),
        sa.UniqueConstraint("isin", name=op.f("uq_listed_companies_isin")),
    )
    op.create_index(
        "ix_listed_companies_taxonomy",
        "listed_companies",
        ["sector", "industry", "domain", "sub_domain"],
        unique=False,
    )
    op.create_table(
        "market_data_runs",
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("symbol_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','PARTIAL','FAILED')",
            name=op.f("ck_market_data_runs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_runs")),
        sa.UniqueConstraint("input_hash", name=op.f("uq_market_data_runs_input_hash")),
    )
    op.create_table(
        "stock_listings",
        sa.Column("listed_company_id", sa.Uuid(), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("exchange_security_id", sa.String(length=50), nullable=True),
        sa.Column("listing_status", sa.String(length=20), nullable=False),
        sa.Column("security_type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("source_provider", sa.String(length=100), nullable=False),
        sa.Column("source_version", sa.String(length=100), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("last_price_date", sa.Date(), nullable=True),
        sa.Column("price_data_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "exchange IN ('NSE','BSE')", name=op.f("ck_stock_listings_exchange_valid")
        ),
        sa.CheckConstraint(
            "listing_status IN ('ACTIVE','SUSPENDED','DELISTED','UNKNOWN')",
            name=op.f("ck_stock_listings_listing_status_valid"),
        ),
        sa.CheckConstraint(
            "price_data_status IN ('CURRENT','STALE','MISSING','PARTIAL')",
            name=op.f("ck_stock_listings_price_data_status_valid"),
        ),
        sa.CheckConstraint(
            "security_type IN ('EQUITY','SME_EQUITY','OTHER')",
            name=op.f("ck_stock_listings_security_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["listed_company_id"],
            ["listed_companies.id"],
            name=op.f("fk_stock_listings_listed_company_id_listed_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_listings")),
        sa.UniqueConstraint("exchange", "symbol", name="uq_stock_listing_exchange_symbol"),
    )
    op.create_index(
        op.f("ix_stock_listings_listed_company_id"),
        "stock_listings",
        ["listed_company_id"],
        unique=False,
    )
    op.create_table(
        "market_data_errors",
        sa.Column("market_data_run_id", sa.Uuid(), nullable=False),
        sa.Column("stock_listing_id", sa.Uuid(), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_data_run_id"],
            ["market_data_runs.id"],
            name=op.f("fk_market_data_errors_market_data_run_id_market_data_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_listing_id"],
            ["stock_listings.id"],
            name=op.f("fk_market_data_errors_stock_listing_id_stock_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_errors")),
    )
    op.create_table(
        "stock_prices",
        sa.Column("stock_listing_id", sa.Uuid(), nullable=False),
        sa.Column("market_data_run_id", sa.Uuid(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_adjusted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "low <= open AND open <= high AND low <= close AND close <= high",
            name=op.f("ck_stock_prices_ohlc_valid"),
        ),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0",
            name=op.f("ck_stock_prices_prices_positive"),
        ),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_stock_prices_volume_nonnegative")),
        sa.ForeignKeyConstraint(
            ["market_data_run_id"],
            ["market_data_runs.id"],
            name=op.f("fk_stock_prices_market_data_run_id_market_data_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_listing_id"],
            ["stock_listings.id"],
            name=op.f("fk_stock_prices_stock_listing_id_stock_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_prices")),
        sa.UniqueConstraint(
            "stock_listing_id",
            "trade_date",
            "provider",
            "provider_version",
            name="uq_stock_price_provider_day",
        ),
    )
    op.create_index(
        "ix_stock_prices_listing_date",
        "stock_prices",
        ["stock_listing_id", "trade_date"],
        unique=False,
    )
    op.create_table(
        "peer_groups",
        sa.Column("source_company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("domain_classification_id", sa.Uuid(), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=100), nullable=True),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("engine_version", sa.String(length=100), nullable=False),
        sa.Column("universe_provider", sa.String(length=100), nullable=False),
        sa.Column("universe_version", sa.String(length=100), nullable=False),
        sa.Column("universe_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('READY','PARTIAL','NEEDS_REVIEW','INSUFFICIENT_CLASSIFICATION','NO_PEERS_FOUND','SEGMENT_REVIEW_REQUIRED')",
            name=op.f("ck_peer_groups_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_peer_groups_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_peer_groups_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["domain_classification_id"],
            ["domain_classifications.id"],
            name=op.f("fk_peer_groups_domain_classification_id_domain_classifications"),
        ),
        sa.ForeignKeyConstraint(
            ["source_company_id"],
            ["companies.id"],
            name=op.f("fk_peer_groups_source_company_id_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_peer_groups")),
        sa.UniqueConstraint(
            "document_id",
            "domain_classification_id",
            "policy_version",
            "universe_snapshot_hash",
            "input_hash",
            name="uq_peer_group_input",
        ),
    )
    op.create_table(
        "peer_group_members",
        sa.Column("peer_group_id", sa.Uuid(), nullable=False),
        sa.Column("listed_company_id", sa.Uuid(), nullable=False),
        sa.Column("stock_listing_id", sa.Uuid(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("sector_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("industry_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("domain_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("sub_domain_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("business_similarity_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("product_overlap_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("review_required", sa.Boolean(), nullable=False),
        sa.Column("rationale_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("rank > 0", name=op.f("ck_peer_group_members_rank_positive")),
        sa.CheckConstraint(
            "similarity_score BETWEEN 0 AND 1", name=op.f("ck_peer_group_members_similarity_range")
        ),
        sa.ForeignKeyConstraint(
            ["listed_company_id"],
            ["listed_companies.id"],
            name=op.f("fk_peer_group_members_listed_company_id_listed_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["peer_group_id"],
            ["peer_groups.id"],
            name=op.f("fk_peer_group_members_peer_group_id_peer_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_listing_id"],
            ["stock_listings.id"],
            name=op.f("fk_peer_group_members_stock_listing_id_stock_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_peer_group_members")),
        sa.UniqueConstraint("peer_group_id", "listed_company_id", name="uq_peer_group_company"),
        sa.UniqueConstraint("peer_group_id", "rank", name="uq_peer_group_rank"),
    )
    op.create_index(
        op.f("ix_peer_group_members_peer_group_id"),
        "peer_group_members",
        ["peer_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_peer_group_members_peer_group_id"), table_name="peer_group_members")
    op.drop_table("peer_group_members")
    op.drop_table("peer_groups")
    op.drop_index("ix_stock_prices_listing_date", table_name="stock_prices")
    op.drop_table("stock_prices")
    op.drop_table("market_data_errors")
    op.drop_index(op.f("ix_stock_listings_listed_company_id"), table_name="stock_listings")
    op.drop_table("stock_listings")
    op.drop_table("market_data_runs")
    op.drop_index("ix_listed_companies_taxonomy", table_name="listed_companies")
    op.drop_table("listed_companies")
    # ### end Alembic commands ###
