"""stock intelligence score ranking

Revision ID: 0024_stock_intelligence_score_ranking
Revises: 0023_stock_ml_dataset_models
Create Date: 2026-09-29 17:44:05.054825
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0024_stock_intelligence_score_ranking"
down_revision: str | None = "0023_stock_ml_dataset_models"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_ranking_runs",
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("ranking_policy_version", sa.String(length=100), nullable=False),
        sa.Column("watchlist_policy_version", sa.String(length=100), nullable=False),
        sa.Column("universe_hash", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("eligible_company_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','PARTIAL','INSUFFICIENT_DATA','NEEDS_REVIEW','UNAVAILABLE')",
            name=op.f("ck_stock_ranking_runs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_ranking_runs")),
        sa.UniqueConstraint("input_hash", name="uq_stock_ranking_input_hash"),
    )
    op.create_index("ix_stock_ranking_as_of", "stock_ranking_runs", ["as_of_date"], unique=False)
    op.create_table(
        "stock_intelligence_runs",
        sa.Column("listed_company_id", sa.Uuid(), nullable=False),
        sa.Column("stock_listing_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("score_version", sa.String(length=100), nullable=False),
        sa.Column("fusion_policy_version", sa.String(length=100), nullable=False),
        sa.Column("normalization_policy_version", sa.String(length=100), nullable=False),
        sa.Column("ranking_policy_version", sa.String(length=100), nullable=False),
        sa.Column("watchlist_policy_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("coverage", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("available_weight", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("available_component_count", sa.Integer(), nullable=False),
        sa.Column("missing_component_count", sa.Integer(), nullable=False),
        sa.Column("band", sa.String(length=60), nullable=True),
        sa.Column("agreement_score", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("top_positive_drivers", sa.JSON(), nullable=False),
        sa.Column("top_negative_drivers", sa.JSON(), nullable=False),
        sa.Column("contradictions", sa.JSON(), nullable=False),
        sa.Column("missing_evidence", sa.JSON(), nullable=False),
        sa.Column("production_use_permitted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','PARTIAL','INSUFFICIENT_DATA','NEEDS_REVIEW','UNAVAILABLE')",
            name=op.f("ck_stock_intelligence_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_stock_intelligence_runs_confidence_valid")
        ),
        sa.CheckConstraint(
            "coverage BETWEEN 0 AND 1", name=op.f("ck_stock_intelligence_runs_coverage_valid")
        ),
        sa.CheckConstraint(
            "production_use_permitted = false",
            name=op.f("ck_stock_intelligence_runs_production_disabled"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score BETWEEN 0 AND 100)",
            name=op.f("ck_stock_intelligence_runs_score_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["listed_company_id"],
            ["listed_companies.id"],
            name=op.f("fk_stock_intelligence_runs_listed_company_id_listed_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_listing_id"],
            ["stock_listings.id"],
            name=op.f("fk_stock_intelligence_runs_stock_listing_id_stock_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_runs")),
        sa.UniqueConstraint("input_hash", name="uq_stock_intelligence_input_hash"),
    )
    op.create_index(
        "ix_stock_intelligence_company_date",
        "stock_intelligence_runs",
        ["listed_company_id", "as_of_date"],
        unique=False,
    )
    op.create_index(
        "ix_stock_intelligence_listing_date",
        "stock_intelligence_runs",
        ["stock_listing_id", "as_of_date"],
        unique=False,
    )
    op.create_index(
        "ix_stock_intelligence_score_version",
        "stock_intelligence_runs",
        ["score_version"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_components",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("component_name", sa.String(length=40), nullable=False),
        sa.Column("raw_score", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("normalized_score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("configured_weight", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("effective_weight", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("contribution", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "component_name IN ('ML_SIGNAL','VALUATION','FUNDAMENTAL_QUALITY','GROWTH',"
            "'PROFITABILITY','BALANCE_SHEET','MOMENTUM','RISK','PEER_RELATIVE',"
            "'SECTOR_RELATIVE','DATA_QUALITY')",
            name=op.f("ck_stock_intelligence_components_component_name_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('AVAILABLE','PARTIAL','INSUFFICIENT_DATA','NEEDS_REVIEW','UNAVAILABLE')",
            name=op.f("ck_stock_intelligence_components_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1",
            name=op.f("ck_stock_intelligence_components_confidence_valid"),
        ),
        sa.CheckConstraint(
            "normalized_score IS NULL OR (normalized_score BETWEEN 0 AND 100)",
            name=op.f("ck_stock_intelligence_components_normalized_score_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["stock_intelligence_runs.id"],
            name=op.f("fk_stock_intelligence_components_run_id_stock_intelligence_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_components")),
        sa.UniqueConstraint("run_id", "component_name", name="uq_stock_intelligence_component"),
    )
    op.create_index(
        "ix_stock_intelligence_component_run",
        "stock_intelligence_components",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "stock_ranking_members",
        sa.Column("ranking_run_id", sa.Uuid(), nullable=False),
        sa.Column("stock_intelligence_run_id", sa.Uuid(), nullable=False),
        sa.Column("listed_company_id", sa.Uuid(), nullable=False),
        sa.Column("stock_listing_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("coverage", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("percentile", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("rank_status", sa.String(length=30), nullable=False),
        sa.Column("research_priority", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "research_priority IN ('RESEARCH_PRIORITY_HIGH','RESEARCH_PRIORITY_MEDIUM',"
            "'RESEARCH_PRIORITY_LOW','INSUFFICIENT_DATA')",
            name=op.f("ck_stock_ranking_members_research_priority_valid"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_stock_ranking_members_confidence_valid")
        ),
        sa.CheckConstraint(
            "coverage BETWEEN 0 AND 1", name=op.f("ck_stock_ranking_members_coverage_valid")
        ),
        sa.CheckConstraint(
            "percentile BETWEEN 0 AND 100", name=op.f("ck_stock_ranking_members_percentile_valid")
        ),
        sa.CheckConstraint("rank > 0", name=op.f("ck_stock_ranking_members_rank_positive")),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_stock_ranking_members_score_valid")
        ),
        sa.ForeignKeyConstraint(
            ["listed_company_id"],
            ["listed_companies.id"],
            name=op.f("fk_stock_ranking_members_listed_company_id_listed_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["ranking_run_id"],
            ["stock_ranking_runs.id"],
            name=op.f("fk_stock_ranking_members_ranking_run_id_stock_ranking_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_intelligence_run_id"],
            ["stock_intelligence_runs.id"],
            name=op.f("fk_stock_ranking_members_stock_intelligence_run_id_stock_intelligence_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_listing_id"],
            ["stock_listings.id"],
            name=op.f("fk_stock_ranking_members_stock_listing_id_stock_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_ranking_members")),
        sa.UniqueConstraint("ranking_run_id", "stock_listing_id", name="uq_stock_ranking_member"),
    )
    op.create_index(
        "ix_stock_ranking_member_run", "stock_ranking_members", ["ranking_run_id"], unique=False
    )
    op.create_table(
        "stock_intelligence_component_inputs",
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("feature_name", sa.String(length=100), nullable=False),
        sa.Column("source_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("source_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["stock_intelligence_components.id"],
            name=op.f(
                "fk_stock_intelligence_component_inputs_component_id_stock_intelligence_components"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_component_inputs")),
        sa.UniqueConstraint(
            "component_id",
            "source_type",
            "source_id",
            "feature_name",
            name="uq_stock_intelligence_component_input",
        ),
    )
    op.create_index(
        "ix_stock_intelligence_input_component",
        "stock_intelligence_component_inputs",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_intelligence_input_source",
        "stock_intelligence_component_inputs",
        ["source_type", "source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_stock_intelligence_input_source", table_name="stock_intelligence_component_inputs"
    )
    op.drop_index(
        "ix_stock_intelligence_input_component", table_name="stock_intelligence_component_inputs"
    )
    op.drop_table("stock_intelligence_component_inputs")
    op.drop_index("ix_stock_ranking_member_run", table_name="stock_ranking_members")
    op.drop_table("stock_ranking_members")
    op.drop_index("ix_stock_intelligence_component_run", table_name="stock_intelligence_components")
    op.drop_table("stock_intelligence_components")
    op.drop_index("ix_stock_intelligence_score_version", table_name="stock_intelligence_runs")
    op.drop_index("ix_stock_intelligence_listing_date", table_name="stock_intelligence_runs")
    op.drop_index("ix_stock_intelligence_company_date", table_name="stock_intelligence_runs")
    op.drop_table("stock_intelligence_runs")
    op.drop_index("ix_stock_ranking_as_of", table_name="stock_ranking_runs")
    op.drop_table("stock_ranking_runs")
    # ### end Alembic commands ###
