"""stock_intelligence_validation

Revision ID: 0025_stock_intelligence_validation
Revises: 0024_stock_intelligence_score_ranking
Create Date: 2026-09-29 18:24:23.423809
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0025_stock_intelligence_validation"
down_revision: str | None = "0024_stock_intelligence_score_ranking"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_intelligence_validation_runs",
        sa.Column("validation_version", sa.String(length=100), nullable=False),
        sa.Column("validation_policy_version", sa.String(length=100), nullable=False),
        sa.Column("ablation_policy_version", sa.String(length=100), nullable=False),
        sa.Column("robustness_policy_version", sa.String(length=100), nullable=False),
        sa.Column("score_version", sa.String(length=100), nullable=False),
        sa.Column("label_policy_version", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_status", sa.String(length=50), nullable=False),
        sa.Column("historical_date_count", sa.Integer(), nullable=False),
        sa.Column("eligible_row_count", sa.Integer(), nullable=False),
        sa.Column("censored_row_count", sa.Integer(), nullable=False),
        sa.Column("mean_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("median_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_top_bottom_spread", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "result_status IN ('INSUFFICIENT_DATA','PIPELINE_VALIDATED',"
            "'RESEARCH_DIAGNOSTICS_AVAILABLE')",
            name=op.f("ck_stock_intelligence_validation_runs_result_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','PARTIAL','INSUFFICIENT_DATA','FAILED')",
            name=op.f("ck_stock_intelligence_validation_runs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_validation_runs")),
        sa.UniqueConstraint("input_hash", name="uq_stock_validation_input_hash"),
    )
    op.create_index(
        "ix_stock_validation_dates",
        "stock_intelligence_validation_runs",
        ["start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "ix_stock_validation_version",
        "stock_intelligence_validation_runs",
        ["validation_version"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_ablation_runs",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_name", sa.String(length=80), nullable=False),
        sa.Column("ablation_policy_version", sa.String(length=100), nullable=False),
        sa.Column("removed_components_json", sa.JSON(), nullable=False),
        sa.Column("weights_json", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','PARTIAL','INSUFFICIENT_DATA','FAILED')",
            name=op.f("ck_stock_intelligence_ablation_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_ablation_runs_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_ablation_runs")),
        sa.UniqueConstraint("input_hash", name="uq_stock_ablation_input_hash"),
    )
    op.create_index(
        op.f("ix_stock_intelligence_ablation_runs_validation_run_id"),
        "stock_intelligence_ablation_runs",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_component_correlations",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("component_a", sa.String(length=40), nullable=False),
        sa.Column("component_b", sa.String(length=40), nullable=False),
        sa.Column("correlation", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("redundancy_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_component_correlations_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_component_correlations")),
        sa.UniqueConstraint(
            "validation_run_id", "component_a", "component_b", name="uq_stock_component_correlation"
        ),
    )
    op.create_index(
        op.f("ix_stock_intelligence_component_correlations_validation_run_id"),
        "stock_intelligence_component_correlations",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_component_validation",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("component_name", sa.String(length=40), nullable=False),
        sa.Column("valid_period_count", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("mean_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("median_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("std_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("minimum_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("maximum_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_component_validation_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_component_validation")),
        sa.UniqueConstraint(
            "validation_run_id", "component_name", name="uq_stock_component_validation"
        ),
    )
    op.create_index(
        op.f("ix_stock_intelligence_component_validation_validation_run_id"),
        "stock_intelligence_component_validation",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_segment_validation",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("segment_type", sa.String(length=40), nullable=False),
        sa.Column("segment_value", sa.String(length=120), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("period_count", sa.Integer(), nullable=False),
        sa.Column("spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("top_bottom_spread", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("top_bucket_hit_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("median_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("std_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("positive_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_segment_validation_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_segment_validation")),
        sa.UniqueConstraint(
            "validation_run_id", "segment_type", "segment_value", name="uq_stock_segment_validation"
        ),
    )
    op.create_index(
        op.f("ix_stock_intelligence_segment_validation_validation_run_id"),
        "stock_intelligence_segment_validation",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_sensitivity_runs",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_name", sa.String(length=80), nullable=False),
        sa.Column("robustness_policy_version", sa.String(length=100), nullable=False),
        sa.Column("weights_json", sa.JSON(), nullable=False),
        sa.Column("baseline_rank_correlation", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("top_k_overlap", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_absolute_rank_change", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("spearman_delta", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("spread_delta", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_sensitivity_runs_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_sensitivity_runs")),
        sa.UniqueConstraint(
            "validation_run_id", "experiment_name", name="uq_stock_sensitivity_run"
        ),
    )
    op.create_index(
        op.f("ix_stock_intelligence_sensitivity_runs_validation_run_id"),
        "stock_intelligence_sensitivity_runs",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_validation_periods",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("ranking_run_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("eligible_company_count", sa.Integer(), nullable=False),
        sa.Column("bucket_method", sa.String(length=20), nullable=False),
        sa.Column("spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("kendall", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("top_bottom_spread", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("top_bucket_hit_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("monotonicity_score", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("monotonicity_status", sa.String(length=30), nullable=False),
        sa.Column("mean_score", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("median_score", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("score_std", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_confidence", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_coverage", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ranking_run_id"],
            ["stock_ranking_runs.id"],
            name=op.f("fk_stock_intelligence_validation_periods_ranking_run_id_stock_ranking_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_validation_periods_validation_run_id_stock_intelligence_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_validation_periods")),
        sa.UniqueConstraint("validation_run_id", "as_of_date", name="uq_stock_validation_period"),
    )
    op.create_index(
        "ix_stock_validation_period_run",
        "stock_intelligence_validation_periods",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_ablation_metrics",
        sa.Column("ablation_run_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=80), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("valid_period_count", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ablation_run_id"],
            ["stock_intelligence_ablation_runs.id"],
            name=op.f(
                "fk_stock_intelligence_ablation_metrics_ablation_run_id_stock_intelligence_ablation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_ablation_metrics")),
        sa.UniqueConstraint("ablation_run_id", "metric_name", name="uq_stock_ablation_metric"),
    )
    op.create_index(
        op.f("ix_stock_intelligence_ablation_metrics_ablation_run_id"),
        "stock_intelligence_ablation_metrics",
        ["ablation_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_validation_members",
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("validation_period_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_row_id", sa.Uuid(), nullable=False),
        sa.Column("score_run_id", sa.Uuid(), nullable=False),
        sa.Column("ranking_run_id", sa.Uuid(), nullable=False),
        sa.Column("listed_company_id", sa.Uuid(), nullable=False),
        sa.Column("stock_listing_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("coverage", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("percentile", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("future_relative_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("future_rank_target", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("label_class", sa.String(length=20), nullable=False),
        sa.Column("label_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_row_id"], ["stock_ml_dataset_rows.id"]),
        sa.ForeignKeyConstraint(["listed_company_id"], ["listed_companies.id"]),
        sa.ForeignKeyConstraint(["ranking_run_id"], ["stock_ranking_runs.id"]),
        sa.ForeignKeyConstraint(["score_run_id"], ["stock_intelligence_runs.id"]),
        sa.ForeignKeyConstraint(["stock_listing_id"], ["stock_listings.id"]),
        sa.ForeignKeyConstraint(
            ["validation_period_id"],
            ["stock_intelligence_validation_periods.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["stock_intelligence_validation_runs.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "validation_run_id", "dataset_row_id", name="uq_stock_validation_member"
        ),
    )
    op.create_index(
        "ix_stock_validation_member_period",
        "stock_intelligence_validation_members",
        ["validation_period_id"],
        unique=False,
    )
    op.create_table(
        "stock_intelligence_validation_buckets",
        sa.Column("validation_period_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_name", sa.String(length=20), nullable=False),
        sa.Column("bucket_order", sa.Integer(), nullable=False),
        sa.Column("company_count", sa.Integer(), nullable=False),
        sa.Column("mean_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("median_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("positive_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("std_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("minimum_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("maximum_relative_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_period_id"],
            ["stock_intelligence_validation_periods.id"],
            name=op.f(
                "fk_stock_intelligence_validation_buckets_validation_period_id_stock_intelligence_validation_periods"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_intelligence_validation_buckets")),
        sa.UniqueConstraint(
            "validation_period_id", "bucket_name", name="uq_stock_validation_bucket"
        ),
    )
    op.create_index(
        op.f("ix_stock_intelligence_validation_buckets_validation_period_id"),
        "stock_intelligence_validation_buckets",
        ["validation_period_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_intelligence_validation_buckets_validation_period_id"),
        table_name="stock_intelligence_validation_buckets",
    )
    op.drop_table("stock_intelligence_validation_buckets")
    op.drop_index(
        op.f("ix_stock_intelligence_ablation_metrics_ablation_run_id"),
        table_name="stock_intelligence_ablation_metrics",
    )
    op.drop_table("stock_intelligence_ablation_metrics")
    op.drop_index(
        "ix_stock_validation_member_period",
        table_name="stock_intelligence_validation_members",
    )
    op.drop_table("stock_intelligence_validation_members")
    op.drop_index(
        "ix_stock_validation_period_run", table_name="stock_intelligence_validation_periods"
    )
    op.drop_table("stock_intelligence_validation_periods")
    op.drop_index(
        op.f("ix_stock_intelligence_sensitivity_runs_validation_run_id"),
        table_name="stock_intelligence_sensitivity_runs",
    )
    op.drop_table("stock_intelligence_sensitivity_runs")
    op.drop_index(
        op.f("ix_stock_intelligence_segment_validation_validation_run_id"),
        table_name="stock_intelligence_segment_validation",
    )
    op.drop_table("stock_intelligence_segment_validation")
    op.drop_index(
        op.f("ix_stock_intelligence_component_validation_validation_run_id"),
        table_name="stock_intelligence_component_validation",
    )
    op.drop_table("stock_intelligence_component_validation")
    op.drop_index(
        op.f("ix_stock_intelligence_component_correlations_validation_run_id"),
        table_name="stock_intelligence_component_correlations",
    )
    op.drop_table("stock_intelligence_component_correlations")
    op.drop_index(
        op.f("ix_stock_intelligence_ablation_runs_validation_run_id"),
        table_name="stock_intelligence_ablation_runs",
    )
    op.drop_table("stock_intelligence_ablation_runs")
    op.drop_index("ix_stock_validation_version", table_name="stock_intelligence_validation_runs")
    op.drop_index("ix_stock_validation_dates", table_name="stock_intelligence_validation_runs")
    op.drop_table("stock_intelligence_validation_runs")
    # ### end Alembic commands ###
