"""stock_monitoring_governance

Revision ID: 0026_stock_monitoring_governance
Revises: 0025_stock_intelligence_validation
Create Date: 2026-09-30 00:00:11.806663
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0026_stock_monitoring_governance"
down_revision: str | None = "0025_stock_intelligence_validation"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_monitoring_runs",
        sa.Column("monitoring_version", sa.String(length=100), nullable=False),
        sa.Column("drift_policy_version", sa.String(length=100), nullable=False),
        sa.Column("governance_policy_version", sa.String(length=100), nullable=False),
        sa.Column("window_policy_version", sa.String(length=100), nullable=False),
        sa.Column("recalibration_readiness_version", sa.String(length=100), nullable=False),
        sa.Column("reference_start_date", sa.Date(), nullable=False),
        sa.Column("reference_end_date", sa.Date(), nullable=False),
        sa.Column("current_start_date", sa.Date(), nullable=False),
        sa.Column("current_end_date", sa.Date(), nullable=False),
        sa.Column("reference_universe_hash", sa.String(length=64), nullable=False),
        sa.Column("current_universe_hash", sa.String(length=64), nullable=False),
        sa.Column("changed_member_count", sa.Integer(), nullable=False),
        sa.Column("comparability_status", sa.String(length=30), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("overall_health_status", sa.String(length=30), nullable=False),
        sa.Column("recalibration_readiness_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "comparability_status IN ('COMPARABLE','PARTIALLY_COMPARABLE','INCOMPARABLE')",
            name=op.f("ck_stock_monitoring_runs_comparability_valid"),
        ),
        sa.CheckConstraint(
            "overall_health_status IN ('HEALTHY','WATCH','REVIEW_REQUIRED','INSUFFICIENT_DATA')",
            name=op.f("ck_stock_monitoring_runs_health_valid"),
        ),
        sa.CheckConstraint(
            "recalibration_readiness_status IN ('NOT_INDICATED','MONITOR','RESEARCH_REVIEW_RECOMMENDED','INSUFFICIENT_DATA')",
            name=op.f("ck_stock_monitoring_runs_readiness_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','PARTIAL','INSUFFICIENT_DATA','FAILED')",
            name=op.f("ck_stock_monitoring_runs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_monitoring_runs")),
        sa.UniqueConstraint("input_hash", name="uq_stock_monitoring_input_hash"),
    )
    op.create_index(
        "ix_stock_monitoring_status",
        "stock_monitoring_runs",
        ["status", "overall_health_status", "recalibration_readiness_status"],
        unique=False,
    )
    op.create_index(
        "ix_stock_monitoring_windows",
        "stock_monitoring_runs",
        ["reference_start_date", "reference_end_date", "current_start_date", "current_end_date"],
        unique=False,
    )
    op.create_table(
        "stock_component_monitoring",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("component_name", sa.String(length=40), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("reference_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("psi", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("availability_reference", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("availability_current", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("availability_delta", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_component_monitoring_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_component_monitoring")),
        sa.UniqueConstraint(
            "monitoring_run_id", "component_name", name="uq_stock_component_monitoring"
        ),
    )
    op.create_index(
        "ix_stock_component_monitoring_component",
        "stock_component_monitoring",
        ["component_name"],
        unique=False,
    )
    op.create_table(
        "stock_feature_drift",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("feature_name", sa.String(length=100), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("reference_mean", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("current_mean", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("reference_std", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("current_std", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("psi", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("psi_bin_count", sa.Integer(), nullable=False),
        sa.Column("ks_statistic", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("ks_pvalue", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_missing_rate", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("current_missing_rate", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("missing_rate_delta", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('INFO','LOW','MODERATE','HIGH')",
            name=op.f("ck_stock_feature_drift_severity_valid"),
        ),
        sa.CheckConstraint(
            "psi IS NULL OR psi >= 0", name=op.f("ck_stock_feature_drift_psi_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_feature_drift_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_feature_drift")),
        sa.UniqueConstraint("monitoring_run_id", "feature_name", name="uq_stock_feature_drift"),
    )
    op.create_index(
        "ix_stock_feature_drift_feature", "stock_feature_drift", ["feature_name"], unique=False
    )
    op.create_table(
        "stock_governance_assessments",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("health_status", sa.String(length=30), nullable=False),
        sa.Column("recalibration_readiness_status", sa.String(length=50), nullable=False),
        sa.Column("high_severity_count", sa.Integer(), nullable=False),
        sa.Column("moderate_severity_count", sa.Integer(), nullable=False),
        sa.Column("stale_provider_count", sa.Integer(), nullable=False),
        sa.Column("high_drift_feature_count", sa.Integer(), nullable=False),
        sa.Column("model_drift_count", sa.Integer(), nullable=False),
        sa.Column("score_drift_status", sa.String(length=40), nullable=False),
        sa.Column("ranking_stability_status", sa.String(length=40), nullable=False),
        sa.Column("reasons_for_review", sa.JSON(), nullable=False),
        sa.Column("reasons_against_review", sa.JSON(), nullable=False),
        sa.Column("insufficient_evidence", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_governance_assessments_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_governance_assessments")),
        sa.UniqueConstraint("monitoring_run_id", name="uq_stock_governance_run"),
    )
    op.create_table(
        "stock_model_monitoring",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("lifecycle", sa.String(length=40), nullable=False),
        sa.Column("reference_prediction_count", sa.Integer(), nullable=False),
        sa.Column("current_prediction_count", sa.Integer(), nullable=False),
        sa.Column("reference_probability_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_probability_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column(
            "reference_probability_median", sa.Numeric(precision=16, scale=10), nullable=True
        ),
        sa.Column("current_probability_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_probability_std", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_probability_std", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_probability_min", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_probability_min", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_probability_max", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_probability_max", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("probability_psi", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("reference_positive_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_positive_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("diagnostic_metric_name", sa.String(length=80), nullable=True),
        sa.Column("reference_metric", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("current_metric", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("metric_delta", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("maturity_status", sa.String(length=30), nullable=False),
        sa.Column("comparability_status", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_model_monitoring_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_model_monitoring")),
    )
    op.create_index(
        "ix_stock_model_monitoring_model",
        "stock_model_monitoring",
        ["model_name", "model_version"],
        unique=False,
    )
    op.create_table(
        "stock_monitoring_findings",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_name", sa.String(length=120), nullable=True),
        sa.Column("reference_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("current_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("delta", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("drift_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('INFO','LOW','MODERATE','HIGH')",
            name=op.f("ck_stock_monitoring_findings_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OBSERVED','WATCH','REVIEW_REQUIRED','INSUFFICIENT_DATA')",
            name=op.f("ck_stock_monitoring_findings_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_monitoring_findings_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_monitoring_findings")),
    )
    op.create_index(
        "ix_stock_monitoring_finding_category",
        "stock_monitoring_findings",
        ["monitoring_run_id", "category", "severity"],
        unique=False,
    )
    op.create_table(
        "stock_provider_monitoring",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("provider_type", sa.String(length=40), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=False),
        sa.Column("provider_classification", sa.String(length=20), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("freshness_age_days", sa.Integer(), nullable=True),
        sa.Column("freshness_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "freshness_status IN ('CURRENT','AGING','STALE','MISSING')",
            name=op.f("ck_stock_provider_monitoring_freshness_status_valid"),
        ),
        sa.CheckConstraint(
            "provider_classification IN ('DEVELOPMENT','LIVE')",
            name=op.f("ck_stock_provider_monitoring_provider_classification_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_provider_monitoring_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_provider_monitoring")),
    )
    op.create_index(
        "ix_stock_provider_monitoring_type",
        "stock_provider_monitoring",
        ["provider_type"],
        unique=False,
    )
    op.create_table(
        "stock_ranking_monitoring",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("reference_ranking_id", sa.Uuid(), nullable=False),
        sa.Column("current_ranking_id", sa.Uuid(), nullable=False),
        sa.Column("common_company_count", sa.Integer(), nullable=False),
        sa.Column("actual_top_k", sa.Integer(), nullable=False),
        sa.Column("rank_spearman", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("top_k_overlap", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("mean_absolute_rank_change", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "rank_spearman IS NULL OR rank_spearman BETWEEN -1 AND 1",
            name=op.f("ck_stock_ranking_monitoring_rank_spearman_range"),
        ),
        sa.CheckConstraint(
            "top_k_overlap IS NULL OR top_k_overlap BETWEEN 0 AND 1",
            name=op.f("ck_stock_ranking_monitoring_top_k_overlap_range"),
        ),
        sa.CheckConstraint(
            "turnover IS NULL OR turnover BETWEEN 0 AND 1",
            name=op.f("ck_stock_ranking_monitoring_turnover_range"),
        ),
        sa.ForeignKeyConstraint(
            ["current_ranking_id"],
            ["stock_ranking_runs.id"],
            name=op.f("fk_stock_ranking_monitoring_current_ranking_id_stock_ranking_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_ranking_monitoring_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reference_ranking_id"],
            ["stock_ranking_runs.id"],
            name=op.f("fk_stock_ranking_monitoring_reference_ranking_id_stock_ranking_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_ranking_monitoring")),
    )
    op.create_index(
        op.f("ix_stock_ranking_monitoring_monitoring_run_id"),
        "stock_ranking_monitoring",
        ["monitoring_run_id"],
        unique=False,
    )
    op.create_table(
        "stock_score_monitoring",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("score_version", sa.String(length=100), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("reference_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_std", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_std", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_min", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_min", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("reference_max", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("current_max", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("score_psi", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("confidence_reference_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("confidence_current_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("confidence_reference_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("confidence_current_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column(
            "confidence_reference_below_rate", sa.Numeric(precision=16, scale=10), nullable=True
        ),
        sa.Column(
            "confidence_current_below_rate", sa.Numeric(precision=16, scale=10), nullable=True
        ),
        sa.Column("coverage_reference_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("coverage_current_mean", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("coverage_reference_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("coverage_current_median", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column(
            "coverage_reference_below_rate", sa.Numeric(precision=16, scale=10), nullable=True
        ),
        sa.Column("coverage_current_below_rate", sa.Numeric(precision=16, scale=10), nullable=True),
        sa.Column("band_distribution_reference", sa.JSON(), nullable=False),
        sa.Column("band_distribution_current", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "score_psi IS NULL OR score_psi >= 0",
            name=op.f("ck_stock_score_monitoring_psi_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["stock_monitoring_runs.id"],
            name=op.f("fk_stock_score_monitoring_monitoring_run_id_stock_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_score_monitoring")),
    )
    op.create_index(
        op.f("ix_stock_score_monitoring_monitoring_run_id"),
        "stock_score_monitoring",
        ["monitoring_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_score_monitoring_monitoring_run_id"), table_name="stock_score_monitoring"
    )
    op.drop_table("stock_score_monitoring")
    op.drop_index(
        op.f("ix_stock_ranking_monitoring_monitoring_run_id"), table_name="stock_ranking_monitoring"
    )
    op.drop_table("stock_ranking_monitoring")
    op.drop_index("ix_stock_provider_monitoring_type", table_name="stock_provider_monitoring")
    op.drop_table("stock_provider_monitoring")
    op.drop_index("ix_stock_monitoring_finding_category", table_name="stock_monitoring_findings")
    op.drop_table("stock_monitoring_findings")
    op.drop_index("ix_stock_model_monitoring_model", table_name="stock_model_monitoring")
    op.drop_table("stock_model_monitoring")
    op.drop_table("stock_governance_assessments")
    op.drop_index("ix_stock_feature_drift_feature", table_name="stock_feature_drift")
    op.drop_table("stock_feature_drift")
    op.drop_index(
        "ix_stock_component_monitoring_component", table_name="stock_component_monitoring"
    )
    op.drop_table("stock_component_monitoring")
    op.drop_index("ix_stock_monitoring_windows", table_name="stock_monitoring_runs")
    op.drop_index("ix_stock_monitoring_status", table_name="stock_monitoring_runs")
    op.drop_table("stock_monitoring_runs")
    # ### end Alembic commands ###
