"""production_runtime_and_jobs

Revision ID: 0028_production_runtime_and_jobs
Revises: 0027_company_intelligence_360_report
Create Date: 2026-10-05 18:00:15.211096
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0028_production_runtime_and_jobs"
down_revision: str | None = "0027_company_intelligence_360_report"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint(op.f("ck_users_reviewer_role_valid"), "users", type_="check")
    op.create_check_constraint(
        op.f("ck_users_reviewer_role_valid"),
        "users",
        "reviewer_role IN ('CREDIT_ANALYST','SENIOR_CREDIT_REVIEWER','CREDIT_MANAGER',"
        "'CREDIT_COMMITTEE_MEMBER','ADMIN','VIEWER','RESEARCH_ANALYST')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_company_access",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_user_company_access_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_company_access_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_company_access")),
        sa.UniqueConstraint("user_id", "company_id", name="uq_user_company_access"),
    )
    op.create_index(
        op.f("ix_user_company_access_company_id"),
        "user_company_access",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_company_access_user_id"), "user_company_access", ["user_id"], unique=False
    )
    op.create_table(
        "background_jobs",
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_job_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("queue_name", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("lease_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','QUEUED','RUNNING','RETRYING','COMPLETED',"
            "'FAILED','CANCELLED','TIMED_OUT')",
            name=op.f("ck_background_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts BETWEEN 1 AND 5 AND timeout_seconds > 0",
            name=op.f("ck_background_jobs_limits_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_background_jobs_analysis_job_id_analysis_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_background_jobs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_background_jobs_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_jobs")),
        sa.UniqueConstraint("job_type", "input_hash", name="uq_background_jobs_input"),
    )
    op.create_index(
        "ix_background_jobs_claim",
        "background_jobs",
        ["status", "scheduled_at", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_company_id"), "background_jobs", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_created_by"), "background_jobs", ["created_by"], unique=False
    )
    op.create_table(
        "job_attempts",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["background_jobs.id"], name=op.f("fk_job_attempts_job_id_background_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint("job_id", "attempt_number", name="uq_job_attempt_number"),
    )
    op.create_index(op.f("ix_job_attempts_job_id"), "job_attempts", ["job_id"], unique=False)
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column(
        "users",
        sa.Column("account_status", sa.String(length=20), server_default="ACTIVE", nullable=False),
    )
    op.add_column(
        "users", sa.Column("token_version", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f("ck_users_account_status_valid"),
        "users",
        "account_status IN ('ACTIVE','DISABLED','LOCKED','PENDING')",
    )


def downgrade() -> None:
    # New role accounts must be explicitly reconciled before rollback; never elevate them.
    op.drop_constraint(op.f("ck_users_reviewer_role_valid"), "users", type_="check")
    op.create_check_constraint(
        op.f("ck_users_reviewer_role_valid"),
        "users",
        "reviewer_role IN ('CREDIT_ANALYST','SENIOR_CREDIT_REVIEWER','CREDIT_MANAGER',"
        "'CREDIT_COMMITTEE_MEMBER','ADMIN')",
    )
    op.drop_constraint(op.f("ck_users_account_status_valid"), "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    op.drop_column("users", "account_status")
    op.drop_column("users", "password_hash")
    op.drop_index(op.f("ix_job_attempts_job_id"), table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_index(op.f("ix_background_jobs_created_by"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_company_id"), table_name="background_jobs")
    op.drop_index("ix_background_jobs_claim", table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index(op.f("ix_user_company_access_user_id"), table_name="user_company_access")
    op.drop_index(op.f("ix_user_company_access_company_id"), table_name="user_company_access")
    op.drop_table("user_company_access")
    # ### end Alembic commands ###
