"use client";

import { downloadArtifact } from "@/lib/http";
import { useRuntimeActor } from "@/lib/use-runtime-actor";
import { FormEvent, useState } from "react";
import { creditReportDownloadUrl, finalizeCreditReport, generateCreditReport, getCreditReportEvidence, getCreditReportSnapshot, listCreditReports } from "@/lib/api";
import type { GeneratedReport, ReportEvidenceLink, ReportSnapshot } from "@/types/api";

export function CreditReports() {
  const [caseId, setCaseId] = useState("");
  const [actorId, setActorId] = useRuntimeActor();
  const [committeeId, setCommitteeId] = useState("");
  const [reportType, setReportType] = useState<GeneratedReport["report_type"]>("CAM");
  const [format, setFormat] = useState<"PDF" | "JSON">("PDF");
  const [reports, setReports] = useState<GeneratedReport[]>([]);
  const [preview, setPreview] = useState<ReportSnapshot | null>(null);
  const [evidence, setEvidence] = useState<ReportEvidenceLink[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function refresh() {
    if (!caseId) return;
    setReports(await listCreditReports(caseId));
  }
  async function generate(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try {
      await generateCreditReport(caseId, { actor_user_id: actorId, report_type: reportType, format, committee_package_id: committeeId || null });
      await refresh();
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Report generation failed"); }
    finally { setBusy(false); }
  }
  async function finalize(reportId: string) {
    setBusy(true); setError("");
    try { await finalizeCreditReport(reportId, actorId, "Finalized from the controlled report workspace"); await refresh(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Report finalization failed"); }
    finally { setBusy(false); }
  }
  async function inspect(reportId: string) {
    try { const [snapshot, links] = await Promise.all([getCreditReportSnapshot(reportId, actorId), getCreditReportEvidence(reportId, actorId)]); setPreview(snapshot); setEvidence(links); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Report preview failed"); }
  }

  return <>
    <section><h2>Generate a report</h2><form onSubmit={generate}>
      <label>Review case ID</label><input value={caseId} onChange={(event) => setCaseId(event.target.value)} required />
      <label>Acting user ID</label><input value={actorId} onChange={(event) => setActorId(event.target.value)} required />
      <label>Report type</label><select value={reportType} onChange={(event) => setReportType(event.target.value as GeneratedReport["report_type"])}><option value="CAM">Credit appraisal memorandum</option><option value="CREDIT_COMMITTEE_MEMO">Credit committee memo</option><option value="DECISION_EVIDENCE_PACK">Decision evidence pack</option><option value="STRUCTURED_JSON_EXPORT">Structured JSON export</option></select>
      <label>Format</label><select value={format} onChange={(event) => setFormat(event.target.value as "PDF" | "JSON")}><option value="PDF">PDF</option><option value="JSON">JSON</option></select>
      {reportType === "CREDIT_COMMITTEE_MEMO" ? <><label>Committee package ID</label><input value={committeeId} onChange={(event) => setCommitteeId(event.target.value)} required /></> : null}
      <button disabled={busy}>Generate fixed snapshot</button><button type="button" disabled={busy || !caseId} onClick={() => void refresh()}>Load versions</button>
    </form>{error ? <p className="error">{error}</p> : null}</section>
    <section><h2>Report versions</h2>{reports.length ? <div className="card-grid">{reports.map((report) => <article className="research-card" key={report.id}><h3>{report.report_type.replaceAll("_", " ")}</h3><p><strong>Version {report.report_version}</strong> · {report.status}</p><p className="muted">Generated by {report.generated_by_user_id}<br />Generated {new Date(report.generated_at).toLocaleString()}<br />Finalized by {report.finalized_by_user_id ?? "Not finalized"}<br />Template {report.template_version}<br />Renderer {report.renderer_version}<br />SHA-256 {report.artifact?.sha256 ?? "Unavailable"}</p>{report.superseded_by_report_id ? <p className="validation-warning">Superseded by {report.superseded_by_report_id}</p> : null}<button onClick={() => void inspect(report.id)}>Preview and evidence</button> {report.status === "GENERATED" ? <button disabled={busy} onClick={() => void finalize(report.id)}>Finalize</button> : null} {report.artifact ? <button className="button" onClick={() => void downloadArtifact(creditReportDownloadUrl(report.id, actorId), `credit-report.${report.artifact?.format ?? "pdf"}`).catch(cause => setError(cause instanceof Error ? cause.message : "Download failed"))}>Download {report.artifact.format}</button> : null}</article>)}</div> : <p>No report versions loaded.</p>}</section>
    {preview ? <section><h2>Snapshot preview</h2>{preview.payload.updated_analysis_available === true ? <div className="validation-warning"><strong>Updated analysis available</strong><span>This report remains bound to its recorded source versions.</span></div> : null}<p>Snapshot v{preview.snapshot_version}<br />Payload hash: {preview.payload_hash}<br />Evidence links: {evidence.length}</p><pre className="snapshot-preview">{JSON.stringify(preview.payload, null, 2)}</pre></section> : null}
  </>;
}
