"use client";
import {useState} from "react";
import {buildFeatures,buildRelativeMetrics,buildStockMLDataset,buildStockMLSplits,buildValuation,discoverPeers,getFundamentals,getRelativeMetrics,getStockMLMetrics,getStockMLModels,getStockMLRuns,syncFundamentals,syncMarketData,syncStockUniverse,trainStockMLModels} from "@/lib/api";
import type {FeatureResult,Fundamental,MarketDataRun,PeerGroup,RelativeMetric,StockMLDataset,StockMLMetric,StockMLModel,StockMLRun,StockMLSplit,ValuationResult} from "@/types/api";
type Tab="Peers"|"Market Data"|"Fundamentals"|"Valuation"|"Relative Metrics"|"Feature Store"|"ML Research";
const tabs:Tab[]=["Peers","Market Data","Fundamentals","Valuation","Relative Metrics","Feature Store","ML Research"];
export function StockIntelligence(){
 const[tab,setTab]=useState<Tab>("Peers"),[actor,setActor]=useState(""),[documentId,setDocument]=useState(""),[companyId,setCompany]=useState(""),[listingId,setListing]=useState(""),[asOf,setAsOf]=useState("2026-09-25"),[peers,setPeers]=useState<PeerGroup|null>(null),[market,setMarket]=useState<MarketDataRun|null>(null),[fundamentals,setFundamentals]=useState<Fundamental[]>([]),[valuation,setValuation]=useState<ValuationResult|null>(null),[relative,setRelative]=useState<RelativeMetric[]>([]),[features,setFeatures]=useState<FeatureResult|null>(null),[mlDataset,setMlDataset]=useState<StockMLDataset|null>(null),[mlSplits,setMlSplits]=useState<StockMLSplit[]>([]),[mlRuns,setMlRuns]=useState<StockMLRun[]>([]),[mlMetrics,setMlMetrics]=useState<StockMLMetric[]>([]),[mlModels,setMlModels]=useState<StockMLModel[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function run(action:()=>Promise<void>){setBusy(true);setError("");try{await action()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}}
 return <><section><h2>Analysis inputs</h2><form><label>Uploaded document ID</label><input value={documentId} onChange={e=>setDocument(e.target.value)}/><label>Listed company ID</label><input value={companyId} onChange={e=>setCompany(e.target.value)}/><label>Primary listing ID</label><input value={listingId} onChange={e=>setListing(e.target.value)}/><label>As-of date</label><input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/><label>Acting user ID</label><input value={actor} onChange={e=>setActor(e.target.value)}/></form><div className="tab-row">{tabs.map(x=><button key={x} className={tab===x?"active-tab":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error?<p className="error">{error}</p>:null}{message?<p className="success">{message}</p>:null}</section>
 {tab==="Peers"?<section><h2>Peer discovery</h2><button disabled={busy||!actor} onClick={()=>void run(async()=>{await syncStockUniverse(actor);setMessage("Universe synchronized")})}>Sync universe</button> <button disabled={busy||!documentId||!actor} onClick={()=>void run(async()=>setPeers(await discoverPeers(documentId,actor)))}>Discover peers</button>{peers?<div className="card-grid">{peers.peers.map(p=><article className="research-card" key={p.company_id}><h3>{p.rank}. {p.company_name}</h3><p>{p.exchange}: {p.symbol}<br/>Similarity {Math.round(Number(p.similarity_score)*100)}%</p><p>{p.rationale.join(" · ")}</p></article>)}</div>:null}</section>:null}
 {tab==="Market Data"?<section><h2>Market data</h2><button disabled={busy||!actor} onClick={()=>void run(async()=>setMarket(await syncMarketData(actor,"2025-08-01",asOf)))}>Sync historical OHLCV</button>{market?<p>{market.status}: {market.success_count} synchronized</p>:null}</section>:null}
 {tab==="Fundamentals"?<section><h2>Reported fundamentals</h2><button disabled={busy||!actor} onClick={()=>void run(async()=>{await syncFundamentals(actor,companyId?[companyId]:undefined);if(companyId)setFundamentals(await getFundamentals(companyId,actor))})}>Sync and load</button><div className="card-grid">{fundamentals.map(x=><article className="research-card" key={x.id}><h3>{x.metric_code.replaceAll("_"," ")}</h3><p>{x.value} {x.unit}<br/>{x.period} · {x.scope}</p><p className="muted">Available {x.availability_date}<br/>{x.provider} · {x.provenance}</p></article>)}</div></section>:null}
 {tab==="Valuation"?<section><h2>Valuation metrics</h2><button disabled={busy||!listingId||!actor} onClick={()=>void run(async()=>setValuation(await buildValuation(listingId,actor,asOf)))}>Build valuation</button>{valuation?<div className="card-grid">{valuation.metrics.map(x=><article className="research-card" key={x.code}><h3>{x.code.replaceAll("_"," ")}</h3><p>{x.value??"Unavailable"}</p><p className="muted">{x.status}</p></article>)}</div>:null}</section>:null}
 {tab==="Relative Metrics"?<section><h2>Peer, industry, and sector context</h2><button disabled={busy||!actor||!companyId} onClick={()=>void run(async()=>{await buildRelativeMetrics(actor,asOf);setRelative(await getRelativeMetrics(companyId,actor));setMessage("Relative metrics built")})}>Build and load relative metrics</button><div className="card-grid">{relative.map((x,index)=><article className="research-card" key={`${x.group_type}-${x.metric_code}-${index}`}><h3>{x.metric_code.replaceAll("_"," ")}</h3><p>{x.group_type.replaceAll("_"," ")} · {x.group}<br/>Value {x.value??"Unavailable"}<br/>Percentile {x.percentile??"Unavailable"}</p><p className="muted">Rank {x.rank??"Unavailable"} of {x.group_size} · {x.status}</p></article>)}</div><p>No investment direction is inferred from percentiles.</p></section>:null}
 {tab==="Feature Store"?<section><h2>Historical feature store</h2><button disabled={busy||!listingId||!actor} onClick={()=>void run(async()=>setFeatures(await buildFeatures(listingId,actor,asOf)))}>Build as-of features</button>{features?<div className="card-grid">{features.features.map(x=><article className="research-card" key={x.name}><h3>{x.name.replaceAll("_"," ")}</h3><p>{x.value??"Unavailable"}</p><p className="muted">{x.group} · {x.status} · {x.source_count} sources</p></article>)}</div>:null}</section>:null}
 {tab==="ML Research"?<section><h2>Stock ML research</h2><button disabled={busy||!actor} onClick={()=>void run(async()=>setMlDataset(await buildStockMLDataset(actor,"2024-01-01",asOf)))}>Build research dataset</button> <button disabled={busy||!actor||!mlDataset} onClick={()=>void run(async()=>{if(mlDataset)setMlSplits(await buildStockMLSplits(mlDataset.id,actor))})}>Build walk-forward splits</button> <button disabled={busy||!actor||!mlSplits.length} onClick={()=>void run(async()=>{for(const split of mlSplits)await trainStockMLModels(split.id,actor);if(mlDataset){const runs=await getStockMLRuns(mlDataset.id,actor);setMlRuns(runs);const models=await getStockMLModels(actor);const selected=models.find(x=>x.selected_for_research);if(selected)setMlMetrics(await getStockMLMetrics(selected.run_id,actor));setMlModels(models)}})}>Train all walk-forward baselines</button>{mlDataset?<article className="research-card"><h3>{mlDataset.dataset_version}</h3><p>{mlDataset.row_count} rows · {mlDataset.company_count} companies · {mlDataset.feature_count} features<br/>{mlDataset.start_date} to {mlDataset.end_date}<br/>Positive {mlDataset.positive_count} · Negative {mlDataset.negative_count} · Neutral {mlDataset.neutral_count} · Censored {mlDataset.censored_count}</p><p className="muted">{mlDataset.label_policy_version} · {mlDataset.readiness}</p></article>:null}<div className="card-grid">{mlSplits.map(x=><article className="research-card" key={x.id}><h3>Split {x.split_index}</h3><p>Train {x.train_start} to {x.train_end}<br/>Validation {x.validation_start}<br/>Test {x.test_start}</p><p className="muted">Embargo {x.embargo_days} days · {x.purged_count} purged</p></article>)}{mlRuns.map(x=><article className="research-card" key={x.id}><h3>{x.model_name.replaceAll("_"," ")}</h3><p>{x.model_version}<br/>{x.lifecycle}</p><p className="muted">Seed {x.random_state} · {x.status}</p></article>)}{mlMetrics.map((x,index)=><article className="research-card" key={`${x.partition}-${x.name}-${index}`}><h3>{x.name.replaceAll("_"," ")}</h3><p>{x.value??"Structured result"}</p><p className="muted">{x.partition}</p></article>)}</div>{mlModels.length?<p>{mlModels.filter(x=>x.selected_for_research).length} research candidate selected from aggregate out-of-sample metrics. Production use remains disabled.</p>:null}<div className="validation-warning"><strong>Research diagnostics only</strong><span>Stock ML outputs are research diagnostics only and are not investment recommendations.</span></div></section>:null}
 <div className="validation-warning"><strong>Analytical data only</strong><span>No BUY, SELL, HOLD, target price, return forecast, or investment recommendation is generated.</span></div></>}
