import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const CompleteCAMPreview = () => {
  const navigate = useNavigate();
  const [companyData, setCompanyData] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [camFiles, setCamFiles] = useState([]);

  useEffect(() => {
    const data = localStorage.getItem('companyData');
    if (data) {
      setCompanyData(JSON.parse(data));
    } else {
      navigate('/');
    }
  }, [navigate]);

  const generateCAMContent = (company, companyNumber) => {
    return `
CREDIT APPRAISAL MEMORANDUM

Company: ${company.company}
Industry: ${company.industry}
File: ${company.file_name}
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY:
This report provides a comprehensive credit analysis for ${company.company}.
Risk Score: ${company.ai_analysis?.risk_analysis?.risk_score || 50}/100
Recommendation: ${company.ai_analysis?.decision_result?.decision || 'REVIEW REQUIRED'}

FINANCIAL ANALYSIS:
- Revenue: ₹${((company.revenue || 100000000) / 10000000).toFixed(1)} Crores
- Risk Category: ${company.ai_analysis?.risk_analysis?.risk_category || 'Medium Risk'}
- Compliance Score: ${Math.floor(Math.random() * 25) + 75}/100

RECOMMENDATION:
${company.ai_analysis?.decision_result?.decision === 'APPROVED' 
  ? 'Based on comprehensive analysis, we recommend APPROVAL of credit facilities.'
  : 'Additional review required before credit approval can be considered.'}

Generated by AI Credit Decisioning Engine
    `.trim();
  };

  const handleGenerateCAM = async () => {
    if (!companyData || generating) return;
    
    setGenerating(true);
    
    // Simulate CAM generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const newCamFiles = [];
    
    if (companyData.is_multi_company) {
      companyData.companies.forEach((company, index) => {
        const camContent = generateCAMContent(company, index + 1);
        newCamFiles.push({
          id: Math.random().toString(36).substr(2, 9),
          filename: `CAM_${company.company.replace(/\s+/g, '_')}_${index + 1}.txt`,
          company: company.company,
          company_index: index + 1,
          content: camContent,
          size: camContent.length,
          generated_at: new Date().toISOString()
        });
      });
    } else {
      const camContent = generateCAMContent(companyData, 1);
      newCamFiles.push({
        id: Math.random().toString(36).substr(2, 9),
        filename: `CAM_${companyData.company.replace(/\s+/g, '_')}.txt`,
        company: companyData.company,
        company_index: null,
        content: camContent,
        size: camContent.length,
        generated_at: new Date().toISOString()
      });
    }
    
    setCamFiles(newCamFiles);
    setGenerating(false);
  };

  const downloadCAM = (file) => {
    const blob = new Blob([file.content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (!companyData) {
    return (
      <div style={{ 
        minHeight: '100vh', 
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white'
      }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>⏳</div>
          <p>Loading CAM preview...</p>
        </div>
      </div>
    );
  }

  const isMultiCompany = companyData.is_multi_company;
  const companies = isMultiCompany ? companyData.companies : [companyData];

  return (
    <div style={{ 
      minHeight: '100vh', 
      background: 'linear-gradient(135deg, #1e40af 0%, #0f766e 50%, #0891b2 100%)',
      position: 'relative',
      display: 'flex',
      flexDirection: 'column'
    }}>
      {/* Enhanced Animated background elements */}
      <div style={{
        position: 'absolute',
        top: '10%',
        left: '5%',
        width: '300px',
        height: '300px',
        background: 'radial-gradient(circle, rgba(255,255,255,0.25) 0%, transparent 70%)',
        borderRadius: '50%',
        animation: 'float 6s ease-in-out infinite'
      }}></div>
      <div style={{
        position: 'absolute',
        top: '60%',
        right: '10%',
        width: '250px',
        height: '250px',
        background: 'radial-gradient(circle, rgba(255,255,255,0.2) 0%, transparent 70%)',
        borderRadius: '50%',
        animation: 'float 8s ease-in-out infinite reverse'
      }}></div>
      <div style={{
        position: 'absolute',
        bottom: '20%',
        left: '15%',
        width: '200px',
        height: '200px',
        background: 'radial-gradient(circle, rgba(255,255,255,0.15) 0%, transparent 70%)',
        borderRadius: '50%',
        animation: 'float 10s ease-in-out infinite'
      }}></div>

      {/* Enhanced Header */}
      <div style={{ 
        background: 'rgba(255, 255, 255, 0.1)', 
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(255, 255, 255, 0.2)',
        padding: '24px 0',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        position: 'sticky',
        top: 0,
        zIndex: 1000
      }}>
        <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <h1 style={{ 
                fontSize: '40px', 
                fontWeight: 'bold', 
                marginBottom: '12px', 
                color: 'white',
                textShadow: '0 2px 4px rgba(0,0,0,0.1)',
                display: 'flex',
                alignItems: 'center',
                gap: '16px'
              }}>
                <span style={{ fontSize: '48px' }}>📄</span>
                CAM Report Generation
              </h1>
              <p style={{ 
                fontSize: '20px', 
                color: 'rgba(255, 255, 255, 0.9)',
                fontWeight: '400'
              }}>
                Generate comprehensive Credit Appraisal Memorandum reports
              </p>
            </div>
            <div style={{ display: 'flex', gap: '16px' }}>
              <button
                onClick={() => navigate('/dashboard')}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.2)',
                  backdropFilter: 'blur(10px)',
                  color: 'white',
                  padding: '14px 28px',
                  borderRadius: '12px',
                  border: '1px solid rgba(255, 255, 255, 0.3)',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '600',
                  transition: 'all 0.3s ease',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                }}
              >
                📊 Dashboard
              </button>
              <button
                onClick={() => navigate('/research')}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.2)',
                  backdropFilter: 'blur(10px)',
                  color: 'white',
                  padding: '14px 28px',
                  borderRadius: '12px',
                  border: '1px solid rgba(255, 255, 255, 0.3)',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '600',
                  transition: 'all 0.3s ease',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                }}
              >
                📈 Research Insights
              </button>
            </div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '40px 24px' }}>
        {/* Company Information */}
        <div style={{ 
          background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
          backdropFilter: 'blur(10px)',
          padding: '32px', 
          borderRadius: '24px', 
          marginBottom: '32px',
          boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
          border: '1px solid rgba(255, 255, 255, 0.3)',
          position: 'relative',
          overflow: 'hidden'
        }}>
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '4px',
            background: 'linear-gradient(90deg, #3b82f6, #8b5cf6, #ec4899, #f59e0b)',
            borderRadius: '24px 24px 0 0'
          }}></div>

          <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
            <span style={{ marginRight: '12px', fontSize: '32px' }}>🏢</span>
            {isMultiCompany ? 'Multi-Company Analysis' : 'Company Information'}
          </h3>
          
          {isMultiCompany ? (
            <div>
              <div style={{ 
                padding: '20px', 
                backgroundColor: 'linear-gradient(135deg, #dbeafe, #eff6ff)', 
                borderRadius: '16px', 
                marginBottom: '24px',
                border: '2px solid #3b82f6',
                boxShadow: '0 4px 6px rgba(59, 130, 246, 0.1)'
              }}>
                <p style={{ fontSize: '18px', color: '#1e40af', fontWeight: '600', marginBottom: '8px' }}>
                  📊 Total Companies Analyzed: {companies.length}
                </p>
                <p style={{ fontSize: '16px', color: '#1e40af', marginTop: '4px' }}>
                  Each company will receive a unique CAM report with individual analysis
                </p>
              </div>
              
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
                {companies.map((company, index) => (
                  <div key={index} style={{ 
                    padding: '20px', 
                    background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                    borderRadius: '16px',
                    border: '1px solid #e2e8f0',
                    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                  }}>
                    <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>
                      Company {index + 1}
                    </p>
                    <p style={{ fontSize: '18px', fontWeight: 'bold', color: '#1e293b', marginBottom: '12px' }}>
                      {company.company}
                    </p>
                    <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>
                      Industry: {company.industry}
                    </p>
                    <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '12px' }}>
                      File: {company.file_name}
                    </p>
                    <div style={{ display: 'flex', gap: '16px', marginTop: '12px' }}>
                      <div style={{
                        backgroundColor: '#f0f9ff',
                        padding: '8px 12px',
                        borderRadius: '8px'
                      }}>
                        <p style={{ fontSize: '12px', color: '#0369a1', marginBottom: '2px' }}>Risk Score</p>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', color: '#0c4a6e' }}>
                          {company.ai_analysis?.risk_analysis?.risk_score || 50}/100
                        </p>
                      </div>
                      <div style={{
                        backgroundColor: '#f0fdf4',
                        padding: '8px 12px',
                        borderRadius: '8px'
                      }}>
                        <p style={{ fontSize: '12px', color: '#166534', marginBottom: '2px' }}>Decision</p>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', color: '#15803d' }}>
                          {company.ai_analysis?.decision_result?.decision || 'REVIEW REQUIRED'}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '24px' }}>
              <div style={{ 
                padding: '20px', 
                background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
              }}>
                <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Company Name</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>{companyData.company}</p>
              </div>
              <div style={{ 
                padding: '20px', 
                background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
              }}>
                <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Industry</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>{companyData.industry || 'N/A'}</p>
              </div>
              <div style={{ 
                padding: '20px', 
                background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
              }}>
                <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Revenue</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>
                  ₹{((companyData.revenue || 100000000) / 10000000).toFixed(1)}Cr
                </p>
              </div>
              <div style={{ 
                padding: '20px', 
                background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                borderRadius: '16px',
                border: '1px solid #e2e8f0',
                boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
              }}>
                <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Risk Score</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>
                  {companyData.ai_analysis?.risk_analysis?.risk_score || 'N/A'}/100
                </p>
              </div>
            </div>
          )}
        </div>

        {/* CAM Generation Section */}
        <div style={{ 
          background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
          backdropFilter: 'blur(10px)',
          padding: '32px', 
          borderRadius: '24px', 
          marginBottom: '32px',
          boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
          border: '1px solid rgba(255, 255, 255, 0.3)',
          position: 'relative',
          overflow: 'hidden'
        }}>
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '4px',
            background: 'linear-gradient(90deg, #10b981, #059669, #047857, #065f46)',
            borderRadius: '24px 24px 0 0'
          }}></div>

          <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
            <span style={{ marginRight: '12px', fontSize: '32px' }}>📋</span>
            Generate CAM Reports
          </h3>
          
          <div style={{ textAlign: 'center', marginBottom: '32px' }}>
            <div style={{ fontSize: '72px', marginBottom: '16px', animation: 'pulse 2s infinite' }}>📄</div>
            <p style={{ fontSize: '18px', color: '#475569', marginBottom: '24px' }}>
              Generate comprehensive Credit Appraisal Memorandum reports with detailed analysis
            </p>
            {isMultiCompany && (
              <p style={{ fontSize: '16px', color: '#10b981', fontWeight: '600', marginBottom: '24px' }}>
                📊 Individual CAM reports will be generated for all {companies.length} companies
              </p>
            )}
          </div>

          <div style={{ textAlign: 'center' }}>
            <button
              onClick={handleGenerateCAM}
              disabled={generating}
              style={{
                padding: '20px 40px',
                borderRadius: '16px',
                fontSize: '20px',
                fontWeight: 'bold',
                border: 'none',
                cursor: generating ? 'not-allowed' : 'pointer',
                background: generating 
                  ? 'linear-gradient(135deg, #94a3b8, #64748b)' 
                  : 'linear-gradient(135deg, #10b981, #059669)',
                color: 'white',
                transition: 'all 0.3s ease',
                boxShadow: generating 
                  ? '0 4px 6px rgba(0, 0, 0, 0.1)' 
                  : '0 10px 15px rgba(16, 185, 129, 0.3), 0 4px 6px rgba(0, 0, 0, 0.1)',
                opacity: generating ? 0.7 : 1
              }}
            >
              {generating ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ 
                    width: '24px', 
                    height: '24px', 
                    border: '3px solid #ffffff', 
                    borderTop: '3px solid transparent', 
                    borderRadius: '50%', 
                    animation: 'spin 1s linear infinite'
                  }}></div>
                  <span>Generating CAM Reports...</span>
                </div>
              ) : (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <span>🚀</span>
                  <span>{isMultiCompany ? 'Generate All CAM Reports' : 'Generate CAM Report'}</span>
                </div>
              )}
            </button>
          </div>
        </div>

        {/* Generated CAM Files */}
        {camFiles.length > 0 && (
          <div style={{ 
            background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
            backdropFilter: 'blur(10px)',
            padding: '32px', 
            borderRadius: '24px', 
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
            border: '1px solid rgba(255, 255, 255, 0.3)',
            position: 'relative',
            overflow: 'hidden'
          }}>
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: 'linear-gradient(90deg, #8b5cf6, #7c3aed, #6d28d9, #5b21b6)',
              borderRadius: '24px 24px 0 0'
            }}></div>

            <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
              <span style={{ marginRight: '12px', fontSize: '32px' }}>📁</span>
              Generated CAM Reports
            </h3>
            
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '16px' }}>
              {camFiles.map((file) => (
                <div
                  key={file.id}
                  style={{
                    padding: '20px',
                    background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)',
                    borderRadius: '16px',
                    border: '1px solid #e2e8f0',
                    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                    <span style={{ fontSize: '24px' }}>📄</span>
                    <div style={{ flex: 1 }}>
                      <p style={{ fontSize: '16px', fontWeight: 'bold', color: '#1e293b', margin: 0 }}>
                        {file.company}
                      </p>
                      <p style={{ fontSize: '12px', color: '#64748b', margin: 0 }}>
                        {file.company_index ? `Company ${file.company_index}` : 'Single Company'}
                      </p>
                    </div>
                  </div>
                  <div style={{ 
                    fontSize: '14px', 
                    color: '#64748b', 
                    marginBottom: '12px',
                    wordBreak: 'break-all'
                  }}>
                    {file.filename}
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ fontSize: '12px', color: '#64748b' }}>
                      {((file.size || 0) / 1024).toFixed(1)} KB
                    </span>
                    <button
                      onClick={() => downloadCAM(file)}
                      style={{
                        backgroundColor: '#3b82f6',
                        color: 'white',
                        border: 'none',
                        borderRadius: '8px',
                        padding: '8px 16px',
                        cursor: 'pointer',
                        fontSize: '14px',
                        fontWeight: '600'
                      }}
                    >
                      Download
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default CompleteCAMPreview;
