import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, useMotionValue, useTransform } from 'framer-motion';

const TiltCard = ({ children, style, className }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const rotateX = useTransform(y, [-100, 100], [8, -8]);
  const rotateY = useTransform(x, [-100, 100], [-8, 8]);

  function handleMouseMove(event) {
    const rect = event.currentTarget.getBoundingClientRect();
    const xPct = ((event.clientX - rect.left) / rect.width - 0.5) * 200;
    const yPct = ((event.clientY - rect.top) / rect.height - 0.5) * 200;
    x.set(xPct);
    y.set(yPct);
  }

  function handleMouseLeave() { x.set(0); y.set(0); }

  return (
    <motion.div
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      style={{ ...style, rotateX, rotateY, transformStyle: "preserve-3d" }}
      className={className}
      whileHover={{ scale: 1.01, translateZ: 15 }}
      transition={{ type: "spring", stiffness: 300, damping: 20 }}
    >
      {children}
    </motion.div>
  );
};

const CompleteCAMPreview = () => {
  const navigate = useNavigate();
  const [companyData, setCompanyData] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [camFiles, setCamFiles] = useState([]);

  useEffect(() => {
    const data = localStorage.getItem('companyData');
    if (data) {
      setCompanyData(JSON.parse(data));
    } else {
      navigate('/');
    }
  }, [navigate]);

  const generateCAMContent = (company, companyNumber) => {
    return `
CREDIT APPRAISAL MEMORANDUM

Company: ${company.company}
Industry: ${company.industry}
File: ${company.file_name}
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY:
This report provides a comprehensive credit analysis for ${company.company}.
Risk Score: ${company.ai_analysis?.risk_analysis?.risk_score || 50}/100
Recommendation: ${company.ai_analysis?.decision_result?.decision || 'REVIEW REQUIRED'}

FINANCIAL ANALYSIS:
- Revenue: ₹${((company.revenue || 100000000) / 10000000).toFixed(1)} Crores
- Risk Category: ${company.ai_analysis?.risk_analysis?.risk_category || 'Medium Risk'}
- Compliance Score: ${Math.floor(Math.random() * 25) + 75}/100

RECOMMENDATION:
${company.ai_analysis?.decision_result?.decision === 'APPROVED'
      ? 'Based on comprehensive analysis, we recommend APPROVAL of credit facilities.'
      : 'Additional review required before credit approval can be considered.'}

Generated by AI Credit Decisioning Engine
    `.trim();
  };

  const handleGenerateCAM = async () => {
    if (!companyData || generating) return;
    setGenerating(true);
    await new Promise(resolve => setTimeout(resolve, 2000));
    const newCamFiles = [];
    if (companyData.is_multi_company) {
      companyData.companies.forEach((company, index) => {
        const camContent = generateCAMContent(company, index + 1);
        newCamFiles.push({
          id: Math.random().toString(36).substr(2, 9),
          filename: `CAM_${company.company.replace(/\s+/g, '_')}_${index + 1}.txt`,
          company: company.company,
          company_index: index + 1,
          content: camContent,
          size: camContent.length,
          generated_at: new Date().toISOString()
        });
      });
    } else {
      const camContent = generateCAMContent(companyData, 1);
      newCamFiles.push({
        id: Math.random().toString(36).substr(2, 9),
        filename: `CAM_${companyData.company.replace(/\s+/g, '_')}.txt`,
        company: companyData.company,
        company_index: null,
        content: camContent,
        size: camContent.length,
        generated_at: new Date().toISOString()
      });
    }
    setCamFiles(newCamFiles);
    setGenerating(false);
  };

  const downloadCAM = (file) => {
    const blob = new Blob([file.content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (!companyData) {
    return (
      <div style={{
        minHeight: '100vh',
        background: 'var(--dashboard-bg)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white'
      }}>
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
          style={{
            width: '60px', height: '60px',
            border: '4px solid rgba(255, 255, 255, 0.2)',
            borderTop: '4px solid #3b82f6',
            borderRadius: '50%'
          }}
        />
      </div>
    );
  }

  const isMultiCompany = companyData.is_multi_company;
  const companies = isMultiCompany ? companyData.companies : [companyData];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="mesh-background"
      style={{
        minHeight: '100vh',
        background: 'var(--dashboard-bg)',
        position: 'relative',
        display: 'flex', flexDirection: 'column',
        perspective: '1500px'
      }}
    >
      {/* Animated background orbs */}
      <motion.div style={{
        position: 'absolute', top: '10%', left: '5%', width: '300px', height: '300px',
        background: 'radial-gradient(circle, rgba(59,130,246,0.12) 0%, transparent 70%)', borderRadius: '50%',
      }} animate={{ y: [0, -40, 0], opacity: [0.3, 0.6, 0.3] }}
        transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }} />
      <motion.div style={{
        position: 'absolute', top: '60%', right: '10%', width: '250px', height: '250px',
        background: 'radial-gradient(circle, rgba(139,92,246,0.12) 0%, transparent 70%)', borderRadius: '50%',
      }} animate={{ y: [0, 50, 0], opacity: [0.2, 0.5, 0.2] }}
        transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }} />

      {/* Header */}
      <div style={{
        background: 'rgba(255, 255, 255, 0.05)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid var(--border-color)',
        padding: '24px 0',
        boxShadow: '0 4px 30px rgba(0, 0, 0, 0.1)',
        zIndex: 1000
      }}>
        <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <h1 style={{
                fontSize: '40px', fontWeight: 'bold', marginBottom: '12px', color: 'white',
                textShadow: '0 2px 10px rgba(0,0,0,0.2)',
                display: 'flex', alignItems: 'center', gap: '16px'
              }}>
                <motion.span
                  animate={{ rotateY: [0, 360] }}
                  transition={{ duration: 6, repeat: Infinity, ease: "linear" }}
                  style={{ fontSize: '48px', display: 'inline-block' }}
                >📄</motion.span>
                CAM Report Generation
              </h1>
              <p style={{ fontSize: '20px', color: 'rgba(255, 255, 255, 0.8)', fontWeight: '400' }}>
                Generate comprehensive Credit Appraisal Memorandum reports
              </p>
            </div>
            <div style={{ display: 'flex', gap: '12px' }}>
              {[
                { label: '📊 Dashboard', path: '/dashboard' },
                { label: '🚀 Dynamic', path: '/dynamic-dashboard' },
                { label: '📈 Research', path: '/research' },
              ].map(btn => (
                <motion.button
                  key={btn.path}
                  onClick={() => navigate(btn.path)}
                  whileHover={{ scale: 1.05, translateZ: 10 }}
                  whileTap={{ scale: 0.95 }}
                  style={{
                    background: 'var(--card-bg)',
                    backdropFilter: 'var(--glass-blur)',
                    color: 'white', padding: '12px 24px', borderRadius: '12px',
                    border: '1px solid var(--border-color)', cursor: 'pointer',
                    fontSize: '15px', fontWeight: '600',
                    boxShadow: 'var(--card-shadow)'
                  }}
                >
                  {btn.label}
                </motion.button>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '40px 24px', width: '100%' }}>
        {/* Company Information */}
        <TiltCard style={{
          background: 'var(--card-bg)',
          backdropFilter: 'var(--glass-blur)',
          padding: '32px', borderRadius: '24px', marginBottom: '32px',
          boxShadow: 'var(--card-shadow)',
          border: '1px solid var(--border-color)',
          position: 'relative', overflow: 'hidden'
        }}>
          <div style={{
            position: 'absolute', top: 0, left: 0, right: 0, height: '4px',
            background: 'linear-gradient(90deg, #3b82f6, #8b5cf6, #ec4899, #f59e0b)',
            borderRadius: '24px 24px 0 0'
          }}></div>

          <h3 style={{
            fontSize: '28px', fontWeight: 'bold', color: 'var(--text-primary)',
            marginBottom: '24px', display: 'flex', alignItems: 'center'
          }}>
            <span style={{ marginRight: '12px', fontSize: '32px' }}>🏢</span>
            {isMultiCompany ? 'Multi-Company Analysis' : 'Company Information'}
          </h3>

          {isMultiCompany ? (
            <div>
              <div style={{
                padding: '20px', background: 'rgba(59, 130, 246, 0.1)',
                borderRadius: '16px', marginBottom: '24px',
                border: '1px solid rgba(59, 130, 246, 0.2)'
              }}>
                <p style={{ fontSize: '18px', color: '#3b82f6', fontWeight: '600', marginBottom: '8px' }}>
                  📊 Total Companies Analyzed: {companies.length}
                </p>
                <p style={{ fontSize: '16px', color: 'var(--text-secondary)', marginTop: '4px' }}>
                  Each company will receive a unique CAM report
                </p>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
                {companies.map((company, index) => (
                  <motion.div
                    key={index}
                    whileHover={{ scale: 1.02 }}
                    style={{
                      padding: '20px', background: 'rgba(255, 255, 255, 0.05)',
                      borderRadius: '16px', border: '1px solid var(--border-color)'
                    }}
                  >
                    <p style={{ fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '4px' }}>
                      Company {index + 1}
                    </p>
                    <p style={{ fontSize: '18px', fontWeight: 'bold', color: 'var(--text-primary)', marginBottom: '12px' }}>
                      {company.company}
                    </p>
                    <p style={{ fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '4px' }}>
                      Industry: {company.industry}
                    </p>
                    <div style={{ display: 'flex', gap: '16px', marginTop: '12px' }}>
                      <div style={{
                        background: 'rgba(59, 130, 246, 0.1)', padding: '8px 12px',
                        borderRadius: '8px', border: '1px solid rgba(59, 130, 246, 0.2)'
                      }}>
                        <p style={{ fontSize: '12px', color: '#3b82f6', marginBottom: '2px' }}>Risk Score</p>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', color: 'var(--text-primary)' }}>
                          {company.ai_analysis?.risk_analysis?.risk_score || 50}/100
                        </p>
                      </div>
                      <div style={{
                        background: 'rgba(16, 185, 129, 0.1)', padding: '8px 12px',
                        borderRadius: '8px', border: '1px solid rgba(16, 185, 129, 0.2)'
                      }}>
                        <p style={{ fontSize: '12px', color: '#10b981', marginBottom: '2px' }}>Decision</p>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', color: 'var(--text-primary)' }}>
                          {company.ai_analysis?.decision_result?.decision || 'REVIEW'}
                        </p>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px' }}>
              {[
                { label: 'Company Name', value: companyData.company },
                { label: 'Industry', value: companyData.industry || 'N/A' },
                { label: 'Revenue', value: `₹${((companyData.revenue || 100000000) / 10000000).toFixed(1)}Cr` },
                { label: 'Risk Score', value: `${companyData.ai_analysis?.risk_analysis?.risk_score || 'N/A'}/100` },
              ].map((item, i) => (
                <motion.div
                  key={i}
                  whileHover={{ scale: 1.03, translateZ: 10 }}
                  style={{
                    padding: '20px', background: 'rgba(255, 255, 255, 0.05)',
                    borderRadius: '16px', border: '1px solid var(--border-color)'
                  }}
                >
                  <p style={{ fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '4px' }}>{item.label}</p>
                  <p style={{ fontSize: '20px', fontWeight: 'bold', color: 'var(--text-primary)' }}>{item.value}</p>
                </motion.div>
              ))}
            </div>
          )}
        </TiltCard>

        {/* CAM Generation Section */}
        <TiltCard style={{
          background: 'var(--card-bg)',
          backdropFilter: 'var(--glass-blur)',
          padding: '32px', borderRadius: '24px', marginBottom: '32px',
          boxShadow: 'var(--card-shadow)',
          border: '1px solid var(--border-color)',
          position: 'relative', overflow: 'hidden'
        }}>
          <div style={{
            position: 'absolute', top: 0, left: 0, right: 0, height: '4px',
            background: 'linear-gradient(90deg, #10b981, #059669, #047857)',
            borderRadius: '24px 24px 0 0'
          }}></div>

          <h3 style={{
            fontSize: '28px', fontWeight: 'bold', color: 'var(--text-primary)',
            marginBottom: '24px', display: 'flex', alignItems: 'center'
          }}>
            <span style={{ marginRight: '12px', fontSize: '32px' }}>📋</span>
            Generate CAM Reports
          </h3>

          <div style={{ textAlign: 'center', marginBottom: '32px' }}>
            <motion.div
              animate={{ y: [0, -15, 0] }}
              transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
              style={{ fontSize: '72px', marginBottom: '16px' }}
            >📄</motion.div>
            <p style={{ fontSize: '18px', color: 'var(--text-secondary)', marginBottom: '24px' }}>
              Generate comprehensive Credit Appraisal Memorandum reports with detailed analysis
            </p>
            {isMultiCompany && (
              <p style={{ fontSize: '16px', color: '#10b981', fontWeight: '600', marginBottom: '24px' }}>
                📊 Individual CAM reports will be generated for all {companies.length} companies
              </p>
            )}
          </div>

          <div style={{ textAlign: 'center' }}>
            <motion.button
              onClick={handleGenerateCAM}
              disabled={generating}
              whileHover={!generating ? { scale: 1.05, translateZ: 15 } : {}}
              whileTap={!generating ? { scale: 0.95 } : {}}
              style={{
                padding: '20px 50px', borderRadius: '16px', fontSize: '20px', fontWeight: 'bold',
                border: 'none', cursor: generating ? 'not-allowed' : 'pointer',
                background: generating
                  ? 'rgba(255, 255, 255, 0.1)'
                  : 'linear-gradient(135deg, #10b981, #059669)',
                color: 'white',
                boxShadow: generating ? 'none' : '0 10px 30px rgba(16, 185, 129, 0.4)',
                opacity: generating ? 0.6 : 1
              }}
            >
              {generating ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    style={{
                      width: '24px', height: '24px',
                      border: '3px solid rgba(255,255,255,0.3)',
                      borderTop: '3px solid white', borderRadius: '50%'
                    }}
                  />
                  <span>Generating CAM Reports...</span>
                </div>
              ) : (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <span>🚀</span>
                  <span>{isMultiCompany ? 'Generate All CAM Reports' : 'Generate CAM Report'}</span>
                </div>
              )}
            </motion.button>
          </div>
        </TiltCard>

        {/* Generated CAM Files */}
        {camFiles.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <TiltCard style={{
              background: 'var(--card-bg)',
              backdropFilter: 'var(--glass-blur)',
              padding: '32px', borderRadius: '24px',
              boxShadow: 'var(--card-shadow)',
              border: '1px solid var(--border-color)',
              position: 'relative', overflow: 'hidden'
            }}>
              <div style={{
                position: 'absolute', top: 0, left: 0, right: 0, height: '4px',
                background: 'linear-gradient(90deg, #8b5cf6, #7c3aed, #6d28d9)',
                borderRadius: '24px 24px 0 0'
              }}></div>

              <h3 style={{
                fontSize: '28px', fontWeight: 'bold', color: 'var(--text-primary)',
                marginBottom: '24px', display: 'flex', alignItems: 'center'
              }}>
                <span style={{ marginRight: '12px', fontSize: '32px' }}>📁</span>
                Generated CAM Reports
              </h3>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '16px' }}>
                {camFiles.map((file, index) => (
                  <motion.div
                    key={file.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    whileHover={{ scale: 1.02, translateZ: 10 }}
                    style={{
                      padding: '20px', background: 'rgba(255, 255, 255, 0.05)',
                      borderRadius: '16px', border: '1px solid var(--border-color)'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                      <span style={{ fontSize: '24px' }}>📄</span>
                      <div style={{ flex: 1 }}>
                        <p style={{ fontSize: '16px', fontWeight: 'bold', color: 'var(--text-primary)', margin: 0 }}>
                          {file.company}
                        </p>
                        <p style={{ fontSize: '12px', color: 'var(--text-secondary)', margin: 0 }}>
                          {file.company_index ? `Company ${file.company_index}` : 'Single Company'}
                        </p>
                      </div>
                    </div>
                    <div style={{ fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '12px', wordBreak: 'break-all' }}>
                      {file.filename}
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                        {((file.size || 0) / 1024).toFixed(1)} KB
                      </span>
                      <motion.button
                        onClick={() => downloadCAM(file)}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        style={{
                          background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                          color: 'white', border: 'none', borderRadius: '10px',
                          padding: '10px 20px', cursor: 'pointer',
                          fontSize: '14px', fontWeight: '600',
                          boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)'
                        }}
                      >
                        ⬇️ Download
                      </motion.button>
                    </div>
                  </motion.div>
                ))}
              </div>
            </TiltCard>
          </motion.div>
        )}
      </div>
    </motion.div>
  );
};

export default CompleteCAMPreview;
