import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import SimpleButton from '../components/SimpleButton';

const SimpleCAMPreview = () => {
  const navigate = useNavigate();
  const [camFiles, setCamFiles] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [companyData, setCompanyData] = useState(null);

  useEffect(() => {
    // Load company data from localStorage
    const storedCompanyData = localStorage.getItem('companyData');
    if (storedCompanyData) {
      setCompanyData(JSON.parse(storedCompanyData));
    }
  }, []);

  const handleGenerateCAM = async () => {
    if (!companyData) {
      setError('No company data available. Please upload documents first.');
      return;
    }

    setGenerating(true);
    setError('');

    try {
      // Check if it's multi-company data
      if (companyData.is_multi_company && companyData.companies) {
        // Generate CAM for each company
        for (let i = 0; i < companyData.companies.length; i++) {
          const company = companyData.companies[i];
          console.log(`CAM Preview: Generating CAM for company ${i + 1}: ${company.company}`);
          
          // Generate CAM content for this specific company
          const camContent = generateCAMContent(company, i + 1);
          
          // Create and download the CAM file
          const blob = new Blob([camContent], { type: 'text/plain' });
          const url = window.URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `CAM_${company.company.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}_Company${i + 1}.txt`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          window.URL.revokeObjectURL(url);

          // Add to CAM files list
          const newCAMFile = {
            id: Date.now() + i,
            filename: link.download,
            company: company.company,
            generated_at: new Date().toISOString(),
            size: blob.size,
            company_index: i + 1
          };
          setCamFiles(prev => [...prev, newCAMFile]);
        }
      } else {
        // Single company CAM generation (existing logic)
        const camContent = generateCAMContent(companyData, 1);
        
        // Create and download the CAM file
        const blob = new Blob([camContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `CAM_${companyData.company.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);

        // Add to CAM files list
        const newCAMFile = {
          id: Date.now(),
          filename: link.download,
          company: companyData.company,
          generated_at: new Date().toISOString(),
          size: blob.size,
          company_index: 1
        };
        setCamFiles([...camFiles, newCAMFile]);
      }

    } catch (err) {
      setError('Failed to generate CAM: ' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  const generateCAMContent = (data, companyNumber) => {
    const currentDate = new Date().toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    // Generate unique CAM content based on company-specific data
    const riskFactors = data.ai_analysis?.risk_factors || [];
    const researchData = data.ai_analysis?.research_summary || {};
    
    return `
CREDIT APPRAISAL MEMORANDUM (CAM) - COMPANY ${companyNumber}
===============================================================

Company: ${data.company}
Industry: ${data.industry || 'N/A'}
File: ${data.file_name || 'N/A'}
Date: ${currentDate}
Generated by: AI Credit Decisioning Engine

EXECUTIVE SUMMARY
=================
This Credit Appraisal Memorandum provides a comprehensive analysis of ${data.company}'s creditworthiness based on financial performance, risk assessment, and industry dynamics. The analysis is specifically tailored to Company ${companyNumber} with unique risk factors and market considerations.

FINANCIAL OVERVIEW
==================
Revenue: ₹${(data.revenue / 10000000).toFixed(2)} Crores
Profit: ₹${(data.profit / 10000000).toFixed(2)} Crores
Total Assets: ₹${(data.assets / 10000000).toFixed(2)} Crores
Total Liabilities: ₹${(data.liabilities / 10000000).toFixed(2)} Crores

Financial Ratios:
- Profit Margin: ${data.financial_ratios?.profit_margin?.toFixed(2) || 'N/A'}%
- Debt-to-Assets Ratio: ${data.financial_ratios?.debt_to_assets?.toFixed(2) || 'N/A'}%
- Return on Assets: ${data.financial_ratios?.return_on_assets?.toFixed(2) || 'N/A'}%
- Working Capital Ratio: ${data.financial_ratios?.working_capital_ratio?.toFixed(2) || 'N/A'}%

COMPANY-SPECIFIC RISK ASSESSMENT
=================================
Risk Score: ${data.ai_analysis?.risk_analysis?.risk_score || 'N/A'}/100
Risk Category: ${data.ai_analysis?.risk_analysis?.risk_category || 'N/A'}
Confidence Score: ${((data.ai_analysis?.risk_analysis?.confidence_score || 0) * 100).toFixed(1)}%

Key Risk Factors for ${data.company}:
${riskFactors.map((factor, index) => {
  const factorText = typeof factor === 'string' ? factor : factor.description;
  const severity = typeof factor === 'object' ? factor.severity : 'Medium';
  const category = typeof factor === 'object' ? factor.category : 'Risk';
  const recommendation = typeof factor === 'object' ? factor.recommendation : 'Monitor closely';
  
  return `${index + 1}. [${severity}] ${category}: ${factorText}
   Recommendation: ${recommendation}`;
}).join('\n') || 'No significant risk factors identified.'}

UNIQUE CREDIT DECISION
======================
Recommended Decision: ${data.ai_analysis?.decision_result?.decision || 'N/A'}
Confidence Level: ${((data.ai_analysis?.decision_result?.confidence_score || 0) * 100).toFixed(1)}%

Loan Analysis for ${data.company}:
- Approved Loan Amount: ₹${(data.ai_analysis?.loan_analysis?.approved_loan_amount / 10000000).toFixed(2)} Crores
- Interest Rate: ${data.ai_analysis?.loan_analysis?.interest_rate || 'N/A'}%
- Recommended Tenure: ${data.ai_analysis?.loan_analysis?.recommended_tenure || 'N/A'} months
- Loan-to-Revenue Ratio: ${((data.ai_analysis?.loan_analysis?.approved_loan_amount / data.revenue) * 100).toFixed(1)}%

COMPANY-SPECIFIC DECISION REASONING
===================================
${data.ai_analysis?.decision_result?.reasoning || 'No reasoning provided.'}

TAILORED RECOMMENDED ACTIONS
=============================
${data.ai_analysis?.decision_result?.recommended_actions?.map((action, index) => 
  `${index + 1}. ${action}`
).join('\n') || 'No specific actions recommended.'}

UNIQUE INDUSTRY ANALYSIS
=========================
Industry: ${data.industry || 'N/A'}
Market Position: ${researchData.industry_analysis?.market_position || 'N/A'}
Industry Outlook: ${researchData.industry_analysis?.outlook || 'N/A'}
Growth Rate: ${researchData.industry_analysis?.growth_rate || 'N/A'}

Industry-Specific Trends for ${data.industry}:
${researchData.industry_analysis?.trends?.map((trend, index) => 
  `${index + 1}. ${trend}`
).join('\n') || 'No specific trends identified.'}

COMPANY-SPECIFIC RESEARCH INSIGHTS
==================================
News Sentiment: ${researchData.news_sentiment?.sentiment || 'N/A'}
Sentiment Score: ${researchData.news_sentiment?.score?.toFixed(2) || 'N/A'}

Key Headlines for ${data.company}:
${researchData.news_sentiment?.key_headlines?.map((headline, index) => 
  `${index + 1}. ${headline}`
).join('\n') || 'No headlines available.'}

Litigation Risk: ${researchData.litigation_data?.risk_assessment || 'N/A'}
Pending Cases: ${researchData.litigation_data?.pending_cases || 'N/A'}

Market Signals for ${data.company}:
Primary Signal: ${researchData.market_signals?.primary_signal || 'N/A'}

Technical Indicators:
${researchData.market_signals?.technical_indicators?.map((indicator, index) => 
  `${index + 1}. ${indicator}`
).join('\n') || 'No technical indicators available.'}

Analyst Recommendations:
${researchData.market_signals?.analyst_recommendations?.map((rec, index) => 
  `${index + 1}. ${rec}`
).join('\n') || 'No analyst recommendations available.'}

COMPANY ${companyNumber} CONCLUSION
===============================
Based on the comprehensive analysis, ${data.company} demonstrates ${data.ai_analysis?.decision_result?.decision === 'Approve' ? 'strong' : data.ai_analysis?.decision_result?.decision === 'Reject' ? 'weak' : 'moderate'} creditworthiness with a risk profile categorized as ${data.ai_analysis?.risk_analysis?.risk_category || 'N/A'}.

The recommended credit facility of ₹${(data.ai_analysis?.loan_analysis?.approved_loan_amount / 10000000).toFixed(2)} Crores at ${data.ai_analysis?.loan_analysis?.interest_rate || 'N/A'}% interest rate is justified based on the company's financial performance, risk parameters, and industry-specific factors.

This CAM for Company ${companyNumber} was generated using AI-powered analysis algorithms with company-specific data and should be reviewed by credit committee before final approval.

===============================================================
End of Credit Appraisal Memorandum for ${data.company}
Generated: ${new Date().toISOString()}
Company Index: ${companyNumber}
    `.trim();
  };

  if (generating) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f0f9ff' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ 
            width: '48px', 
            height: '48px', 
            border: '4px solid #e5e7eb', 
            borderTop: '4px solid #2563eb', 
            borderRadius: '50%', 
            animation: 'spin 1s linear infinite',
            margin: '0 auto 16px'
          }}></div>
          <p style={{ fontSize: '18px', color: '#4b5563' }}>Generating CAM Report...</p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ 
      minHeight: '100vh', 
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      position: 'relative'
    }}>
      {/* Animated background elements */}
      <div style={{
        position: 'absolute',
        top: '10%',
        left: '5%',
        width: '200px',
        height: '200px',
        background: 'radial-gradient(circle, rgba(255,255,255,0.1) 0%, transparent 70%)',
        borderRadius: '50%',
        animation: 'float 6s ease-in-out infinite'
      }}></div>
      <div style={{
        position: 'absolute',
        top: '60%',
        right: '10%',
        width: '150px',
        height: '150px',
        background: 'radial-gradient(circle, rgba(255,255,255,0.1) 0%, transparent 70%)',
        borderRadius: '50%',
        animation: 'float 8s ease-in-out infinite reverse'
      }}></div>

      {/* Header */}
      <div style={{ 
        background: 'rgba(255, 255, 255, 0.1)', 
        backdropFilter: 'blur(10px)',
        borderBottom: '1px solid rgba(255, 255, 255, 0.2)',
        padding: '32px 0',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
      }}>
        <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <h1 style={{ 
                fontSize: '40px', 
                fontWeight: 'bold', 
                marginBottom: '12px', 
                color: 'white',
                textShadow: '0 2px 4px rgba(0,0,0,0.1)',
                display: 'flex',
                alignItems: 'center',
                gap: '16px'
              }}>
                <span style={{ fontSize: '48px' }}>📄</span>
                CAM Report Generation
              </h1>
              <p style={{ 
                fontSize: '20px', 
                color: 'rgba(255, 255, 255, 0.9)',
                fontWeight: '400'
              }}>
                Generate comprehensive Credit Appraisal Memorandum reports
              </p>
            </div>
            <div style={{ display: 'flex', gap: '16px' }}>
              <button
                onClick={() => navigate('/dashboard')}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.2)',
                  backdropFilter: 'blur(10px)',
                  color: 'white',
                  padding: '14px 28px',
                  borderRadius: '12px',
                  border: '1px solid rgba(255, 255, 255, 0.3)',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '600',
                  transition: 'all 0.3s ease',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                }}
                onMouseEnter={(e) => {
                  e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.3)';
                  e.target.style.transform = 'translateY(-2px)';
                }}
                onMouseLeave={(e) => {
                  e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.2)';
                  e.target.style.transform = 'translateY(0)';
                }}
              >
                📊 Dashboard
              </button>
              <button
                onClick={() => navigate('/research')}
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.2)',
                  backdropFilter: 'blur(10px)',
                  color: 'white',
                  padding: '14px 28px',
                  borderRadius: '12px',
                  border: '1px solid rgba(255, 255, 255, 0.3)',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '600',
                  transition: 'all 0.3s ease',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                }}
                onMouseEnter={(e) => {
                  e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.3)';
                  e.target.style.transform = 'translateY(-2px)';
                }}
                onMouseLeave={(e) => {
                  e.target.style.backgroundColor = 'rgba(255, 255, 255, 0.2)';
                  e.target.style.transform = 'translateY(0)';
                }}
              >
                📈 Research Insights
              </button>
            </div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '40px 24px' }}>
        {/* Company Information */}
        {companyData && (
          <div style={{ 
            background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
            backdropFilter: 'blur(10px)',
            padding: '32px', 
            borderRadius: '24px', 
            marginBottom: '32px',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            border: '1px solid rgba(255, 255, 255, 0.3)',
            position: 'relative',
            overflow: 'hidden'
          }}>
            {/* Decorative gradient overlay */}
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: 'linear-gradient(90deg, #3b82f6, #8b5cf6, #ec4899, #f59e0b)',
              borderRadius: '24px 24px 0 0'
            }}></div>

            <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
              <span style={{ marginRight: '12px', fontSize: '32px' }}>🏢</span>
              {companyData.is_multi_company ? 'Multi-Company Analysis' : 'Company Information'}
            </h3>
            
            {companyData.is_multi_company ? (
              <div>
                <div style={{ 
                  padding: '20px', 
                  backgroundColor: 'linear-gradient(135deg, #dbeafe, #eff6ff)', 
                  borderRadius: '16px', 
                  marginBottom: '24px',
                  border: '2px solid #3b82f6',
                  boxShadow: '0 4px 6px rgba(59, 130, 246, 0.1)'
                }}>
                  <p style={{ fontSize: '18px', color: '#1e40af', fontWeight: '600', marginBottom: '8px' }}>
                    📊 Total Companies Analyzed: {companyData.total_companies}
                  </p>
                  <p style={{ fontSize: '16px', color: '#1e40af', marginTop: '4px' }}>
                    Each company will receive a unique CAM report with individual analysis
                  </p>
                </div>
                
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
                  {companyData.companies.map((company, index) => (
                    <div key={index} style={{ 
                      padding: '20px', 
                      background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                      borderRadius: '16px',
                      border: '1px solid #e2e8f0',
                      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
                      transition: 'all 0.3s ease'
                    }}
                    onMouseEnter={(e) => {
                      e.target.style.transform = 'translateY(-4px)';
                      e.target.style.boxShadow = '0 10px 15px rgba(0, 0, 0, 0.1)';
                    }}
                    onMouseLeave={(e) => {
                      e.target.style.transform = 'translateY(0)';
                      e.target.style.boxShadow = '0 4px 6px rgba(0, 0, 0, 0.05)';
                    }}>
                      <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>
                        Company {index + 1}
                      </p>
                      <p style={{ fontSize: '18px', fontWeight: 'bold', color: '#1e293b', marginBottom: '12px' }}>
                        {company.company}
                      </p>
                      <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>
                        Industry: {company.industry}
                      </p>
                      <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '12px' }}>
                        File: {company.file_name}
                      </p>
                      <div style={{ display: 'flex', gap: '16px', marginTop: '12px' }}>
                        <div style={{
                          backgroundColor: '#f0f9ff',
                          padding: '8px 12px',
                          borderRadius: '8px'
                        }}>
                          <p style={{ fontSize: '12px', color: '#0369a1', marginBottom: '2px' }}>Risk Score</p>
                          <p style={{ fontSize: '16px', fontWeight: 'bold', color: '#0c4a6e' }}>
                            {company.ai_analysis.risk_analysis.risk_score}/100
                          </p>
                        </div>
                        <div style={{
                          backgroundColor: '#f0fdf4',
                          padding: '8px 12px',
                          borderRadius: '8px'
                        }}>
                          <p style={{ fontSize: '12px', color: '#166534', marginBottom: '2px' }}>Decision</p>
                          <p style={{ fontSize: '16px', fontWeight: 'bold', color: '#15803d' }}>
                            {company.ai_analysis.decision_result.decision}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '24px' }}>
                <div style={{ 
                  padding: '20px', 
                  background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                  borderRadius: '16px',
                  border: '1px solid #e2e8f0',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                }}>
                  <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Company Name</p>
                  <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>{companyData.company}</p>
                </div>
                <div style={{ 
                  padding: '20px', 
                  background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                  borderRadius: '16px',
                  border: '1px solid #e2e8f0',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                }}>
                  <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Industry</p>
                  <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>{companyData.industry || 'N/A'}</p>
                </div>
                <div style={{ 
                  padding: '20px', 
                  background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                  borderRadius: '16px',
                  border: '1px solid #e2e8f0',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                }}>
                  <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Revenue</p>
                  <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>
                    ₹{(companyData.revenue / 10000000).toFixed(1)}Cr
                  </p>
                </div>
                <div style={{ 
                  padding: '20px', 
                  background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)', 
                  borderRadius: '16px',
                  border: '1px solid #e2e8f0',
                  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)'
                }}>
                  <p style={{ fontSize: '14px', color: '#64748b', marginBottom: '4px' }}>Risk Score</p>
                  <p style={{ fontSize: '20px', fontWeight: 'bold', color: '#1e293b' }}>
                    {companyData.ai_analysis?.risk_analysis?.risk_score || 'N/A'}/100
                  </p>
                </div>
              </div>
            )}
          </div>
        )}

        {/* CAM Generation Section */}
        <div style={{ 
          background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
          backdropFilter: 'blur(10px)',
          padding: '32px', 
          borderRadius: '24px', 
          marginBottom: '32px',
          boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
          border: '1px solid rgba(255, 255, 255, 0.3)',
          position: 'relative',
          overflow: 'hidden'
        }}>
          {/* Decorative gradient overlay */}
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '4px',
            background: 'linear-gradient(90deg, #10b981, #059669, #047857, #065f46)',
            borderRadius: '24px 24px 0 0'
          }}></div>

          <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
            <span style={{ marginRight: '12px', fontSize: '32px' }}>📋</span>
            Generate CAM Reports
          </h3>
          
          <div style={{ textAlign: 'center', marginBottom: '32px' }}>
            <div style={{ fontSize: '72px', marginBottom: '16px', animation: 'pulse 2s infinite' }}>📄</div>
            <p style={{ fontSize: '18px', color: '#475569', marginBottom: '24px' }}>
              Generate comprehensive Credit Appraisal Memorandum reports with detailed analysis
            </p>
            {companyData?.is_multi_company && (
              <p style={{ fontSize: '16px', color: '#10b981', fontWeight: '600', marginBottom: '24px' }}>
                📊 Individual CAM reports will be generated for all {companyData.total_companies} companies
              </p>
            )}
          </div>

          <div style={{ textAlign: 'center' }}>
            <button
              onClick={handleGenerateCAM}
              disabled={generating || !companyData}
              style={{
                padding: '20px 40px',
                borderRadius: '16px',
                fontSize: '20px',
                fontWeight: 'bold',
                border: 'none',
                cursor: generating || !companyData ? 'not-allowed' : 'pointer',
                background: generating || !companyData 
                  ? 'linear-gradient(135deg, #94a3b8, #64748b)' 
                  : 'linear-gradient(135deg, #10b981, #059669)',
                color: 'white',
                transition: 'all 0.3s ease',
                boxShadow: generating || !companyData 
                  ? '0 4px 6px rgba(0, 0, 0, 0.1)' 
                  : '0 10px 15px rgba(16, 185, 129, 0.3), 0 4px 6px rgba(0, 0, 0, 0.1)',
                opacity: generating ? 0.7 : 1,
                position: 'relative',
                overflow: 'hidden'
              }}
              onMouseEnter={(e) => {
                if (!(generating || !companyData)) {
                  e.target.style.background = 'linear-gradient(135deg, #059669, #047857)';
                  e.target.style.transform = 'translateY(-4px)';
                  e.target.style.boxShadow = '0 20px 25px rgba(16, 185, 129, 0.4), 0 10px 10px rgba(0, 0, 0, 0.1)';
                }
              }}
              onMouseLeave={(e) => {
                if (!(generating || !companyData)) {
                  e.target.style.background = 'linear-gradient(135deg, #10b981, #059669)';
                  e.target.style.transform = 'translateY(0)';
                  e.target.style.boxShadow = '0 10px 15px rgba(16, 185, 129, 0.3), 0 4px 6px rgba(0, 0, 0, 0.1)';
                }
              }}
            >
              {generating ? (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ 
                    width: '24px', 
                    height: '24px', 
                    border: '3px solid #ffffff', 
                    borderTop: '3px solid transparent', 
                    borderRadius: '50%', 
                    animation: 'spin 1s linear infinite'
                  }}></div>
                  <span>Generating CAM Reports...</span>
                </div>
              ) : (
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <span>�</span>
                  <span>{companyData?.is_multi_company ? 'Generate All CAM Reports' : 'Generate CAM Report'}</span>
                </div>
              )}
            </button>
            <p style={{ fontSize: '16px', color: '#64748b', marginTop: '20px' }}>
              {companyData?.is_multi_company 
                ? 'Individual CAM reports will be generated for each company with unique analysis'
                : 'Comprehensive CAM report will be generated with detailed credit analysis'
              }
            </p>
          </div>

          {error && (
            <div style={{ 
              marginTop: '24px',
              padding: '16px',
              backgroundColor: '#fef2f2',
              border: '2px solid #ef4444',
              borderRadius: '12px',
              color: '#991b1b',
              fontWeight: '600',
              textAlign: 'center',
              boxShadow: '0 4px 6px rgba(239, 68, 68, 0.1)'
            }}>
              ⚠️ {error}
            </div>
          )}
        </div>

        {/* Generated CAM Files */}
        {camFiles.length > 0 && (
          <div style={{ 
            background: 'linear-gradient(135deg, rgba(255,255,255,0.95), rgba(248,250,252,0.95))',
            backdropFilter: 'blur(10px)',
            padding: '32px', 
            borderRadius: '24px', 
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            border: '1px solid rgba(255, 255, 255, 0.3)',
            position: 'relative',
            overflow: 'hidden'
          }}>
            {/* Decorative gradient overlay */}
            <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: 'linear-gradient(90deg, #8b5cf6, #7c3aed, #6d28d9, #5b21b6)',
              borderRadius: '24px 24px 0 0'
            }}></div>

            <h3 style={{ fontSize: '28px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px', display: 'flex', alignItems: 'center' }}>
              <span style={{ marginRight: '12px', fontSize: '32px' }}>📁</span>
              Generated CAM Reports
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {camFiles.map((file) => (
                <div
                  key={file.id}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '16px',
                    backgroundColor: '#f9fafb',
                    borderRadius: '8px',
                    border: '1px solid #e5e7eb'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ fontSize: '24px' }}>📄</div>
                    <div>
                      <p style={{ fontWeight: '600', color: '#111827' }}>{file.filename}</p>
                      <p style={{ fontSize: '14px', color: '#6b7280' }}>
                        {file.company} • {new Date(file.generated_at).toLocaleDateString()}
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => handleGenerateCAM()}
                    style={{
                      backgroundColor: '#2563eb',
                      color: 'white',
                      padding: '8px 16px',
                      borderRadius: '6px',
                      border: 'none',
                      cursor: 'pointer',
                      fontSize: '14px',
                      fontWeight: '600'
                    }}
                  >
                    Download
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div style={{ 
            marginTop: '24px', 
            padding: '16px', 
            backgroundColor: '#fef2f2', 
            border: '1px solid #fecaca',
            borderRadius: '8px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <div style={{ fontSize: '24px' }}>⚠️</div>
              <div>
                <p style={{ color: '#991b1b', fontWeight: '600' }}>Error</p>
                <p style={{ color: '#b91c1c', fontSize: '14px' }}>{error}</p>
              </div>
            </div>
          </div>
        )}
      </div>

      </div>
  );
};

export default SimpleCAMPreview;
