from enum import StrEnum


class AnalysisJobStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CANCELLED = "CANCELLED"


class AnalysisStage(StrEnum):
    CREATED = "CREATED"
    DOCUMENT_INGESTION = "DOCUMENT_INGESTION"
    DOCUMENT_PARSING = "DOCUMENT_PARSING"
    COMPANY_EXTRACTION = "COMPANY_EXTRACTION"
    DOMAIN_CLASSIFICATION = "DOMAIN_CLASSIFICATION"
    FINANCIAL_EXTRACTION = "FINANCIAL_EXTRACTION"
    FINANCIAL_VALIDATION = "FINANCIAL_VALIDATION"
    FINANCIAL_TREND_ANALYSIS = "FINANCIAL_TREND_ANALYSIS"
    CREDIT_ANALYSIS = "CREDIT_ANALYSIS"
    RESEARCH = "RESEARCH"
    PEER_DISCOVERY = "PEER_DISCOVERY"
    STOCK_ANALYSIS = "STOCK_ANALYSIS"
    REPORT_GENERATION = "REPORT_GENERATION"


class DocumentStatus(StrEnum):
    REGISTERED = "REGISTERED"
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class ParserStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class PageExtractionMethod(StrEnum):
    NATIVE_TEXT = "NATIVE_TEXT"
    OCR = "OCR"
    BLANK = "BLANK"
    FAILED = "FAILED"


class DocumentExtractionMethod(StrEnum):
    NATIVE_TEXT = "NATIVE_TEXT"
    OCR = "OCR"
    HYBRID = "HYBRID"
    BLANK = "BLANK"
    FAILED = "FAILED"


class FieldStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CONFLICTING = "CONFLICTING"
    UNAVAILABLE = "UNAVAILABLE"


class ProfileStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CONFLICTING = "CONFLICTING"


class IdentityMatchStatus(StrEnum):
    MATCHED = "MATCHED"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    MISMATCH = "MISMATCH"
    UNAVAILABLE = "UNAVAILABLE"


class MLRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ClassificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"


class FinancialStatementType(StrEnum):
    BALANCE_SHEET = "BALANCE_SHEET"
    INCOME_STATEMENT = "INCOME_STATEMENT"
    CASH_FLOW_STATEMENT = "CASH_FLOW_STATEMENT"


class FinancialScope(StrEnum):
    STANDALONE = "STANDALONE"
    CONSOLIDATED = "CONSOLIDATED"
    UNKNOWN = "UNKNOWN"


class FinancialStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CONFLICTING = "CONFLICTING"
    UNAVAILABLE = "UNAVAILABLE"
    UNMAPPED = "UNMAPPED"


class NormalizationStatus(StrEnum):
    NORMALIZED = "NORMALIZED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    INVALID_VALUE = "INVALID_VALUE"


class ValueOrigin(StrEnum):
    EXTRACTED = "EXTRACTED"
    DERIVED = "DERIVED"


class ValidationSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ValidationStatus(StrEnum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"


class RatioStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_MEANINGFUL = "NOT_MEANINGFUL"
    CONFLICTING = "CONFLICTING"


class TrendMetricSourceType(StrEnum):
    NORMALIZED_VALUE = "NORMALIZED_VALUE"
    RATIO = "RATIO"


class TrendDirection(StrEnum):
    INCREASING = "INCREASING"
    DECREASING = "DECREASING"
    STABLE = "STABLE"
    VOLATILE = "VOLATILE"
    MIXED = "MIXED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    STATE_CHANGE = "STATE_CHANGE"


class TrendStrength(StrEnum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"


class TrendStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_MEANINGFUL = "NOT_MEANINGFUL"
    CONFLICTING = "CONFLICTING"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class ChangeType(StrEnum):
    ABSOLUTE = "ABSOLUTE"
    PERCENT = "PERCENT"
    PERCENTAGE_POINT = "PERCENTAGE_POINT"
    MULTIPLE_CHANGE = "MULTIPLE_CHANGE"
    STATE_TRANSITION = "STATE_TRANSITION"


class AnomalySeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnomalyStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"


class CreditComponent(StrEnum):
    FINANCIAL_STRENGTH = "FINANCIAL_STRENGTH"
    REPAYMENT_CAPACITY = "REPAYMENT_CAPACITY"
    BUSINESS_STABILITY = "BUSINESS_STABILITY"
    DATA_QUALITY = "DATA_QUALITY"
    INDUSTRY_CONTEXT = "INDUSTRY_CONTEXT"


class CreditAssessmentStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    CONFLICTING = "CONFLICTING"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"


class CreditRiskBand(StrEnum):
    LOW_RISK = "LOW_RISK"
    MODERATE_LOW_RISK = "MODERATE_LOW_RISK"
    MODERATE_RISK = "MODERATE_RISK"
    ELEVATED_RISK = "ELEVATED_RISK"
    HIGH_RISK = "HIGH_RISK"


class CreditReasonType(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    REVIEW = "REVIEW"


class CreditOutcomeType(StrEnum):
    NO_DEFAULT = "NO_DEFAULT"
    DEFAULT = "DEFAULT"
    DELINQUENCY_30 = "DELINQUENCY_30"
    DELINQUENCY_60 = "DELINQUENCY_60"
    DELINQUENCY_90 = "DELINQUENCY_90"
    RESTRUCTURED = "RESTRUCTURED"
    WRITE_OFF = "WRITE_OFF"
    BANKRUPTCY = "BANKRUPTCY"
    INSOLVENCY = "INSOLVENCY"
    LOAN_CLOSED_PERFORMING = "LOAN_CLOSED_PERFORMING"
    UNKNOWN = "UNKNOWN"


class CreditLabelStatus(StrEnum):
    LABELED_POSITIVE = "LABELED_POSITIVE"
    LABELED_NEGATIVE = "LABELED_NEGATIVE"
    CENSORED = "CENSORED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class CreditLabelQuality(StrEnum):
    VERIFIED_REAL = "VERIFIED_REAL"
    CURATED_REAL = "CURATED_REAL"
    PROXY = "PROXY"
    SYNTHETIC = "SYNTHETIC"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CONFLICTING = "CONFLICTING"
    UNVERIFIED = "UNVERIFIED"


class DatasetEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    EXCLUDED = "EXCLUDED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class CreditDatasetSplit(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    TEST = "TEST"
    EXCLUDED = "EXCLUDED"


class CreditDatasetQuality(StrEnum):
    VALID = "VALID"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    INVALID = "INVALID"
