from __future__ import annotations

from app.models.research import ResearchFinding

CHARACTER_CODES = {
    "REGULATORY_PENALTY_ORDER": "CHARACTER_REGULATORY_ACTION_REPORTED",
    "REGULATORY_INVESTIGATION_REPORTED": "CHARACTER_REGULATORY_INVESTIGATION_REPORTED",
    "DIRECTOR_DISQUALIFICATION_REPORTED": "CHARACTER_DIRECTOR_DISQUALIFICATION_REPORTED",
    "LEGAL_ALLEGATION_REPORTED": "CHARACTER_PROMOTER_LEGAL_CASE_REPORTED",
    "LEGAL_CONVICTION_REPORTED": "CHARACTER_GOVERNANCE_EVENT_REPORTED",
}

CONDITIONS_CODES = {
    "CREDIT_RATING_DOWNGRADED": "CONDITIONS_RATING_DOWNGRADE",
    "CREDIT_RATING_UPGRADED": "CONDITIONS_RATING_UPGRADE",
    "CREDIT_RATING_AFFIRMED": "CONDITIONS_RATING_AFFIRMED",
    "CREDIT_RATING_WITHDRAWN": "CONDITIONS_RATING_WITHDRAWN",
    "RATING_OUTLOOK_CHANGED": "CONDITIONS_RATING_OUTLOOK_CHANGE",
    "INDUSTRY_DEMAND_OUTLOOK_MIXED": "CONDITIONS_MIXED_SECTOR_OUTLOOK",
    "INDUSTRY_OUTLOOK_NEGATIVE": "CONDITIONS_NEGATIVE_SECTOR_OUTLOOK",
    "INDUSTRY_OUTLOOK_POSITIVE": "CONDITIONS_POSITIVE_SECTOR_OUTLOOK",
    "SECTOR_OUTLOOK_MIXED": "CONDITIONS_MIXED_SECTOR_OUTLOOK",
    "SECTOR_OUTLOOK_NEGATIVE": "CONDITIONS_NEGATIVE_SECTOR_OUTLOOK",
    "SECTOR_OUTLOOK_POSITIVE": "CONDITIONS_POSITIVE_SECTOR_OUTLOOK",
}


def mapping_for(finding: ResearchFinding) -> tuple[str, str] | None:
    if finding.finding_code in CHARACTER_CODES:
        return "CHARACTER", CHARACTER_CODES[finding.finding_code]
    if finding.finding_code in CONDITIONS_CODES:
        return "CONDITIONS", CONDITIONS_CODES[finding.finding_code]
    return None
