from pathlib import Path
from typing import BinaryIO, Protocol


class StorageBackend(Protocol):
    def save_file(self, source: BinaryIO, stored_filename: str) -> str: ...

    def delete_file(self, uri: str) -> None: ...

    def exists(self, uri: str) -> bool: ...

    def get_file_path(self, uri: str) -> Path: ...
